### ISSUE TITLE
Can't play the local sound file when the js bundle is loaded from http server.

### ISSUE THREAD

**Issue by cpunion** [zmxv/react-native-sound#10]
I load js bundle from remote http server, it can't play the local sound file. If I change to local js bundle, it works fine.

In this case, the `error` argument in `callback` is `null`, but just no sound. If I change the file name to a non-exists file, the `error` argument is an error.

**Comment by zmxv** [comment]
This doesn't _sound_ like a react-native-sound issue. Have you verified that the js bundles are identical?

**Comment by cpunion** [comment]
It's my fault. I didn't call `play` in `callback`. Most time it works in local network env, and often fails in a  slower network environment.
