### ISSUE TITLE
Is this library supported anymore?

### ISSUE THREAD

**Issue by moaxaca** [zmxv/react-native-sound#102]
I am having issues with an iPhone 7 specifically. Everything runs perfectly in simulator then on device it never invokes the .play() callback. Its very strange. I see theres other forks with active maintenance.  Are the current contributors active? If I were to debug/fix my issues (assuming its a bug) would it be merged?

**Comment by jimthedev** [comment]
I am seeing this exact same issue. .play never gets called on the device. Simulator is 💯.

**Comment by jimthedev** [comment]
Do you have multiple players in your project by chance?

**Comment by moaxaca** [comment]
I don't. I am using it alongside react-native-audio to playback voice recordings.

**Comment by jimthedev** [comment]
I am too. Hmmm. Perhaps recorder isn't releasing the file in time?

-- 
Jim ForCy

**Comment by moaxaca** [comment]
It could be, I dumped the container just to make sure it was recording and it played back on my mac. I will inject a static file to test if its a release issue.

**Comment by jimthedev** [comment]
This ended up working for me: https://github.com/jsierles/react-native-audio/pull/155

Heads up it seems like it still isn't on npm so you'd need to install from master.

**Comment by zmxv** [comment]
Sorry for the lack of maintenance in the past few months.
I've just added @benvium as a collaborator who will help merge some of the outstanding PRs. I myself will also be more active when I get more time.

**Comment by moaxaca** [comment]
@zmxv Ty

**Comment by moaxaca** [comment]
IT WORKS !!!!!!! Thank you @jimthedev pulling both from master fixed it.

**Comment by benvium** [comment]
@moaxaca In case do you do decide to contribute to this repo, I am actively working on this repo now.
At present I'm going through backlog of tickets and PRs. I be will merging useful, working PRs in.

**Comment by benvium** [comment]
Closing this ticket as the answer to the headline is 'yes!'.

**Comment by moaxaca** [comment]
@benvium sounds good.

**Comment by jimthedev** [comment]
Is @benvium going to have npm release access?

**Comment by benvium** [comment]
@jimthedev I've asked @zmxv for this.

**Comment by jimthedev** [comment]
Ok great. Being able to refer to releases instead of master would be very helpful. Ideally semantic release would be great but just being able to get off master at this point would make tackling issues easier.

**Comment by benvium** [comment]
@jimthedev Yep, I'll semver this for sure.
