### ISSUE TITLE
Playback fails after a certain number of plays

### ISSUE THREAD

**Issue by slaterJJ** [zmxv/react-native-sound#103]
I have a list view of different items. When you click on an item it opens a modal with an option to play an audio file. If I click on different items in the list or the same audio file continuously  it allows me to play the audio in total 31 times. I have tested this and it always seem to be 31. This is using an android emulator on my android phone and breaks after less times and the audio files do not always play first try. The code is below if anyone can see something I am doing wrong.

```javascript
playSound () {
    const call = this.props.animal.common_name.toLowerCase().replace(/ |-/g, '');
    const s = new Sound('${call}.mp3', Sound.MAIN_BUNDLE, (e) => {
      if (e) {
        console.log('error', e);
      } else {
        s.play((success) => {
              if (!success) {
                console.warn('playback failed due to audio decoding errors');
              }
            });
        this.setState({audio: s, playing: true})
      }
    })
  }

  stopSound () {
    this.state.audio.stop();
    this.setState({playing: false});
  }

  componentWillUnmount () {
    this.setState({audio: null});
  }

  <View>
    {!playing && <TouchableOpacity onPress={playSound.bind(this, 'play')} style={styles.audio} >
      <Icon name='play' size={22} color={'rgb(44, 157, 51)'} />
      <Text style={styles.audioText}>Play Call</Text>
      </TouchableOpacity>}
    {playing && <TouchableOpacity onPress={stopSound.bind(this, 'stop')} style={styles.audio} >
      <Icon name='stop' size={22} color={'rgb(179, 15, 15)'} />
      <Text style={styles.audioText}>Stop Call</Text>
    </TouchableOpacity>}
  </View>```

**Comment by benvium** [comment]
You're creating a new instance of the audio player each time you call `playSound`. You need to store the `new Sound` instance on your component and call stop on that.

e.g. 
```javascript
this.mySound = new Sound(..

....
this.mySound.stop();
```

**Comment by slaterJJ** [comment]
I originally had the new Sound in component did mount and the play and stop sound separate. I have changed the code to the below and the problem still persists. We tried it on ios today and there was no errors so it is android only problem.
Here is my changed code, 

`  componentDidMount () {
    const call = this.props.animal.common_name.toLowerCase().replace(/ |-/g, '');
    this.setState({
      audio: new Sound('${call}.mp3', Sound.MAIN_BUNDLE, (e) => {
        if (e) {
          console.log('error', e);
        }
      })
    })
  }

  playSound () {
    this.setState({playing: true})
    this.state.audio.play((success) => {
        if (success) {
          this.setState({playing: false})
        } else {
          console.warn('playback failed due to audio decoding errors');
        }
      });
  }

  stopSound () {
    this.state.audio.stop();
    this.setState({playing: false});
  }

  componentWillUnmount () {
    this.setState({audio: null});
  }`

**Comment by benvium** [comment]
Thanks for the updated code. It ought to work if you .release() the file once it's done playing. Can you try:

```javascript
playSound () {
    this.setState({playing: true})
    this.state.audio.play((success) => {
        this.state.audio.release();
        if (success) {
          this.setState({playing: false, audio: null})
        } else {
          console.warn('playback failed due to audio decoding errors');
        }
      });
  }
```

**Comment by slaterJJ** [comment]
That was the issue. We went a meet up as well a mobile developer explained it was due to memory leak by us not releasing the audio file, so it just built up in the phone memory. IOS handles memory better than android which is why it worked on ios and the android phone memory is a lot less than the emulator which is why it differed there.

Thanks for your help.
