### ISSUE TITLE
How to activate AVAudioSessionCategoryAmbient

### ISSUE THREAD

**Issue by gHashTag** [zmxv/react-native-sound#104]
Audio Player starts only one track, but it is necessary that the Play button starts a greater number of tracks at once. The documentation says:
```You can play multiple sound files at the same time. Under the hood, this module uses AVAudioSessionCategoryAmbient to mix sounds on iOS.```
How to activate AVAudioSessionCategoryAmbient since the following code in the file, the application falls AppDelegate?

```#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow *window;
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
    {
        [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];
        return YES;
    }
@end
```

**Comment by benvium** [comment]
If you want to play multiple files at once, create several instances of the Sound object configured with different sound files. 
Ambient is the default category, so there's no need to set anything in the Obj-C `didFinishLaunchingWithOptions` method.

**Comment by gHashTag** [comment]
@benvium Why, then, I do not play all the tracks at once?
https://gist.github.com/gHashTag/efbc812ec486efc79d1fac883764e537
