### ISSUE TITLE
Cannot read property 'setLooping' of undefined

### ISSUE THREAD

**Issue by jenbennings** [zmxv/react-native-sound#11]
```json
    "react-native": "^0.17.0",
    "react-native-sound": "^0.7.3"
```

<img width="487" alt="screen shot 2016-01-14 at 9 00 37 pm" src="https://cloud.githubusercontent.com/assets/3468612/12345794/7d924f42-bb02-11e5-92a8-f7f863b60075.png">

Any ideas?

**Comment by zmxv** [comment]
I haven't been able to reproduce this bug on OS X. Is it possible to attach the full source?

**Comment by jenbennings** [comment]
I closed Xcode for the night and opened it again after I saw you replied. That alone seems to have resolved the issue.

**Comment by breezykermo** [comment]
I got this issue when switching between XCode projects, and forgetting to restart the React Native packager, for anyone who comes to this page with the same problem.
