### ISSUE TITLE
can not load file in rn 0.41? android

### ISSUE THREAD

**Issue by yongningfu** [zmxv/react-native-sound#113]
i am true i follow the instructions above readme guide, but it went wrong. is it can not support rn 0.41 in android?

**Comment by IljaDaderko** [comment]
@yongningfu hey, I've just installed library today on `rn0.41.2` and had no issues, can you provide a code snippet of how you are using the library?

**Comment by todbichig** [comment]
I put the audio files in android/app/src/main/res/raw and then used code that worked on ios, but it couldn't play on the Android port of the app. To try and find out what the problem is I added this code from the nmpjs site:

```
 var whoosh = new Sound('a.mp3', Sound.MAIN_BUNDLE, (error) => {
  if (error) {
    console.log('failed to load the sound', error);
    return;
  } 
  // loaded successfully 
  console.log('duration in seconds: ' + whoosh.getDuration() + 'number of channels: ' + whoosh.getNumberOfChannels());
}); 
```

In the console I got this kind of message: 

> failed to load the sound Object {message: null, code: -1}

**Comment by rogierslag** [comment]
Encountering the same here

**Comment by rogierslag** [comment]
Also problematic on react native 0.43.4

**Comment by leogeng** [comment]
Encountering the same.
react-native-cli: 2.0.1
react-native: 0.44.0

**Comment by rogierslag** [comment]
V0.10.1 should fix that I think

**Comment by benvium** [comment]
@rogierslag @leogeng 0.10.1 is indeed intended to fix this - please let me know if it helps.

**Comment by rogierslag** [comment]
Fixed it for me, thanks so much!

**Comment by paulmelnikow** [comment]
Hi! If anyone is still experiencing this issue in the latest version, could you please open an issue with more details following the issue template? Thanks!
