### ISSUE TITLE
How to make infinite random group loops?

### ISSUE THREAD

**Issue by gHashTag** [zmxv/react-native-sound#115]
I tried ```setNumberOfLoops``` but this function is not suitable because the sets amount loop, and after Returns the the beginning, and I needed after a run out a magnifying glass to return to the top with a new random group Loops.
That's where I left off:
[https://gist.github.com/gHashTag/efbc812ec486efc79d1fac883764e537](url)

**Comment by zmxv** [comment]
What do you mean by "infinite random group loops"?
Also, the gist link is broken.

**Comment by gHashTag** [comment]
"infinite random group loops" - Here is a similar project: http://play.mubert.com
 My Gist:
https://gist.github.com/gHashTag/efbc812ec486efc79d1fac883764e537

**Comment by gHashTag** [comment]
@benvium help please
