### ISSUE TITLE
Is there a way to automate audio file include?

### ISSUE THREAD

**Issue by IljaDaderko** [zmxv/react-native-sound#116]
I've managed to get audio playing, but I'm striving to make includes to the project automated.

I've got this in my package.json to automate font includes from my `src/assets/fonts` folder

```
        "rnpm": {
		"assets": [
			"src/assets/fonts"
		]
	}
```

This puts files into Resources folder. Unfortunately it doesn't seem like `Sound` can play from there. Could you suggest something (if possible) to have similar flow for `src/assets/audio` folder. If not, is it possible to include audio file from src folder as opposed to native?

**Comment by benvium** [comment]
At the moment android can only play audio files from the res/raw folder. I'm planning to add android assets support at some time as it'd be useful for us, but don't have a timeline on this.

You could perhaps create a bash script to copy the files to res/raw to have some level of automation.

**Comment by IljaDaderko** [comment]
@benvium App is iOS focused at the moment, is there a way to achieve this there?

**Comment by benvium** [comment]
@IljaDaderko Ah I see. Our solution to this is to put all the fonts in a folder at the project root, and then have folder reference in XCode pointing to it (make sure you uncheck Copy files if required when adding the folder). This way, when new audios are added / removed / edited you don't need to change anything in Xcode.

**Comment by IljaDaderko** [comment]
I see, also looked at your example project, I didn't realise it is possible to play sound from `require('./advertisment.mp3')` I think this is sollution I needed, will give it a go. Thank you for your time

**Comment by benvium** [comment]
Aha - good point, I didn't think of that. We don't use that option as all our apps are cross-platform and that doesn't work on Android yet. :-)

**Comment by IljaDaderko** [comment]
Does the trick now, looking forward for Android support, I think this is really neat feature 👍

**Comment by Venryx** [comment]
Android asset support can be accomplished by adding this to the start of the `RNSoundModule.createMediaPlayer` function:
```
if (fileName.startsWith("assets/")) {
	try {
		MediaPlayer player = new MediaPlayer();
		AssetFileDescriptor assetFileInfo = context.getAssets().openFd(fileName.substring("assets/".length()));
		player.setDataSource(assetFileInfo.getFileDescriptor(), assetFileInfo.getStartOffset(), assetFileInfo.getLength());
		player.prepare();
		return player;
	} catch (IOException e) {
		e.printStackTrace();
	}
}
```

And then from JavaScript, doing:
```
var whoosh = new Sound('whoosh.mp3', 'assets', (error)=>{});
```

Of course, this isn't that much different from using the `android/app/src/main/res/raw` directory, as mentioned in the Readme. But I like this slightly better, because the assets folder preserves the original filename and folder structure. This is nice for when you want the user to be able to reference the files manually. (as is true in my app)
