### ISSUE TITLE
Optimising performance

### ISSUE THREAD

**Issue by IljaDaderko** [zmxv/react-native-sound#118]
We want to create separate component for `<Sound />` that will sit at app level, this way no matter where we are in the application we can play the sound and not worry about mounting / unmounting components etc, we can than play relevant sound in such component through redux or something similar.

I wanted to ask for advice on how to correctly include multiple sounds in such component for it to be performant + does releasing a sound somehow affect performance or can we keep it in there?
It will also be case where background music is playing and we need to play button click sound over it, shall we create each sound as separate constant  and then just play it? i.e. `const background = new Sound(...); const buttonPress = new Sound(...)`

**Comment by zmxv** [comment]
I wouldn't tie a `Sound` object to any React component or Redux. I'd manage all sound clips in a globally accessible class and never worry about the effects of mounting/unmounting.
