### ISSUE TITLE
Unable to load mp3 on iOS

### ISSUE THREAD

**Issue by jenbennings** [zmxv/react-native-sound#12]
Currently trying to load an mp3 from the root directory in my project but am being thrown this error in the react native debugger:

```javascript
Object {code: 2003334207, message: "The operation couldn’t be completed. (OSStatus error 2003334207.)", nativeStackIOS: Array[16], domain: "NSOSStatusErrorDomain"}
```
How I'm currently attempting to use react-native-sound:

```javascript
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  Image,
  TouchableHighlight,
  View,
} = React;

var Sound = require('react-native-sound');

var ding = new Sound('ding.mp3', Sound.MAIN_BUNDLE, (error) => {
  if (error) {
    console.log(error);
  }
});

var soundtest = React.createClass({
  _handleDing: function() {
    ding.play();
  },

  render: function() {
    return (
      <View style={styles.container}>
        <TouchableHighlight onPress={this._handleDing}>
          <View style={{width: 100, height: 100, padding: 20, backgroundColor: 'red', borderRadius: 50}}>
          </View>
        </TouchableHighlight>
      </View>
    );
  }
});

AppRegistry.registerComponent('soundtest', () => soundtest);
```

My guess is that this has something to do with the react native/ios file system. I've tried multiple mp3s so I'm relatively sure it's not to do with the file itself, but perhaps where I'm storing it. Right now it is in the root directory of my react native project (same as `index.ios.js`).

I'm running:

```json
    "react-native": "^0.17.0",
    "react-native-sound": "^0.7.3"
```

Any ideas?

**Comment by zmxv** [comment]
It doesn't matter where you store the file as long as it's bundled with the app. Can you select the mp3 in XCode's project navigator and verify that the Target Membership list includes the main build target?

**Comment by jenbennings** [comment]
Doesn't appear to be in there anywhere. Not terribly familiar with Xcode so apologies if this is a newbie error :pray:. I've got it in the root of the _react_ folder as I'd like it to be available for both iOS + Android.

<img width="286" alt="screen shot 2016-01-16 at 5 18 40 pm" src="https://cloud.githubusercontent.com/assets/3468612/12375395/5bb89d4e-bc75-11e5-9993-19a9c5fe6c63.png">

<img width="237" alt="screen shot 2016-01-16 at 5 23 07 pm" src="https://cloud.githubusercontent.com/assets/3468612/12375413/1ca3eb76-bc76-11e5-86f1-68f8b0162dbe.png">

**Comment by jenbennings** [comment]
Managed to get this working once I added the file manually to the Xcode project. Unless this should have been done automatically, it might be a good idea to update the readme with specific info for iOS (you've got some for android already).

Thanks for your help!

**Comment by zmxv** [comment]
Thanks for the suggestion. I've updated README.md with more detailed instructions.
