### ISSUE TITLE
 The operation couldn’t be completed. (OSStatus error -10875.)

### ISSUE THREAD

**Issue by zakster12** [zmxv/react-native-sound#120]
Hello, guys. I have the following error when trying to play a sound. I will attach an image of the error below. Here is my code:

```
import Sounddd from 'react-native-sound';
const sTest = new Sounddd('test.mp3', Sounddd.MAIN_BUNDLE, (error) => {
			if (error) {
				console.log('failed to load the sound', error);
				return;
			}
			// loaded successfully
			console.log('duration in seconds: ' + sTest.getDuration() + 'number of channels: ' + sTest.getNumberOfChannels());
		});

		sTest.play((success) => {
			if (success) {
				console.log('successfully finished playing');
			} else {
				console.log('playback failed due to audio decoding errors');
			}
		});
```

![screen shot 2017-02-27 at 1 11 36 pm](https://cloud.githubusercontent.com/assets/25477229/23359366/975d04c4-fcee-11e6-8161-956117fdb061.png)
![screen shot 2017-02-27 at 1 11 07 pm](https://cloud.githubusercontent.com/assets/25477229/23359365/975c4674-fcee-11e6-82ea-a7264e5c6bf4.png)

**Comment by benvium** [comment]
Perhaps it's the typo in your code `Sounddd.MAIN_BUNDLE` => `Sound.MAIN_BUNDLE`?

**Comment by zakster12** [comment]
I think it's not a typo because I imported it as Sounddd. But to be sure I tested like this:
`import Sound from 'react-native-sound';

export default class iChat extends Component {

	onPressPlay() {
		console.log('Play');

		const whoosh = new Sound('test.mp3', Sound.MAIN_BUNDLE, (error) => {
			if (error) {
				console.log('failed to load the sound', error);
				return;
			}
		});

		whoosh.play((success) => {
			if (success) {
				console.log('successfully finished playing');
			} else {
				console.log('playback failed due to audio decoding errors');
			}
		});
	}`

And I have the same error

**Comment by benvium** [comment]
@zakster12 Ah you are right about the import, apologies.

Can you check the mp3 is included in the app bundle (build phases, copy bundle resources)?

**Comment by zakster12** [comment]
@benvium thanks for trying to help me. Yes, the mp3 is listed there.

![screen shot 2017-02-27 at 4 47 55 pm](https://cloud.githubusercontent.com/assets/25477229/23365683/939d40e2-fd0c-11e6-876e-2a8f2436cc8f.png)

**Comment by Ali-Ayyad** [comment]
same problem as well @zakster12

**Comment by Ali-Ayyad** [comment]
@zakster12  had the same problem related to the audio path , made it work by using 
`const requireAudio = require('./test.mp3');
`
```
const s = new Sound(requireAudio, (e) => {
      if (e) {
        console.log('error', e);
        return;
      }
      s.play(() => s.release());
      });
```

**Comment by freiserg** [comment]
@benvium I have the same problem after updating to 0.9.0. It's working in 0.8.3. I rolled back this commit https://github.com/zmxv/react-native-sound/commit/882c663c331f8177cc2d3d01dc8163cbd854ba70 and It works.

**Comment by zakster12** [comment]
@Ali-Ayyad with your snippet of code right now I do not have any errors but there is no sound at all. I tried with .mp3 and with .wav and there is no sound.

**Comment by benvium** [comment]
@freiserg Thanks for that - sounds like there's been a regression due to that commit. I'll investigate

**Comment by benvium** [comment]
@freiserg @zakster12 So react-native-sound-demo works fine with RNSound 0.9.0.

Checking into it the difference is that I wait for the constructor callback before calling .play()

e.g:

```js
const s = new Sound('advertising.mp3', Sound.MAIN_BUNDLE, (e) => {
        if (e) {
          console.log('error', e);
        } else {
          s.setSpeed(1);
          console.log('duration', s.getDuration());
          s.play(() => s.release()); // Release when it's done so we're not using up resources
        }
      });
```

If I move the `s.play()` line to where you have it (i.e. immediately after the new Sound command) then the audio fails to play.

**Comment by Ali-Ayyad** [comment]
@zakster12 try `Sound.setCategory('Playback', true)`

**Comment by benvium** [comment]
There was a bug preventing setCategory from working if the mixWithOthers param wasn't set see #124. I made a PR to fix that - not released to npm yet

**Comment by lagofvc** [comment]
Thanx for the suggestions here: @Ali-Ayyad @benvium ,  I got rid of this errors, but I am also experiencing the exact set of descriptions that @zakster12 gave.  Currently no sound.  0.9.1

**Comment by Darthmaul** [comment]
Hello

I'm having a similar issue as @lagofvc . No errors in my code besides failing to play the sound. Getting "The operation couldn't be completed", even though I have included my sound on Xcode and have basically just copy and pasted from the demo code.

Any troubleshooting that should be done to go about fixing this?

**Comment by benvium** [comment]
@lagofvc @Darthmaul I presume you've tried `Sound.setCategory('Playback', true)` before playing any audio?

**Comment by Darthmaul** [comment]
`class Home extends Component {
  
  constructor(props) {
    super(props);

    Sound.setCategory('Playback', true); // true = mixWithOthers

    this.playSoundBundle = () => {
      const s = new Sound('advertising.mp3', Sound.MAIN_BUNDLE, (e) => {
        if (e) {
          console.log('error', e);
        } else {
          s.setSpeed(1);
          console.log('duration', s.getDuration());
          s.play(() => s.release()); // Release when it's done so we're not using up resources
        }
      });
    };
}   
  render () {
    return (
      <ScrollView style={{backgroundColor: 'white'}}>
        <Text h3 style={styles.albums}>Albums</Text>
        <Avatar
          large
          icon={{type: 'rocket', color: 'orange'}}
          overlayContainerStyle={{backgroundColor: 'white'}}
          onPress={() => console.log("Works!")}
          activeOpacity={0.7}
          containerStyle={{flex: 4}}
        />
        <Text h3 style={styles.singles}>Singles</Text>
      {/*Dynamically load our list based on the list constant above*/}
        <List containerStyle={{marginBottom: 20}}>
          {
            list.map((item, i) => (
              <ListItem
                key={i}
                title={item.title}
                leftIcon={{name: item.icon}}
              />
            ))
          }
        </List>
      {/*Let's play that audio! Need to somehow render this inside the list :)*/}
        <Button title="Main bundle audio" onPress={this.playSoundBundle}/>
      </ScrollView>
    )
  }
}`

This is my current code that is not playing any audio and throwing this error

**Comment by lagofvc** [comment]
@benvium , Thanx!  Yes, I did try with the `.setCategory('Playback', true);`.
As a side note I have the exact same mp3 file in the same code already playing but using a different library.  So at least I know my mp3 is available for sound and properly setup.   But I am wanting to use some of the capabilities of this library to see if it serve my purposes better.  Thank you again.

**Comment by Darthmaul** [comment]
Hey thanks for the response @benvium ! I just did a clean xcode install on my brand new mac and the sound works fine. Not sure what was wrong, I guess switching to a new system worked.
Andrew

**Comment by cuong1104** [comment]
did you try replace Sounddd.MAIN_BUNDLE with ''?

**Comment by paulmelnikow** [comment]
Hi! If you are still experiencing this issue in the latest version, could you please open an issue with more details following the issue template? Thanks!

**Comment by adancarrasco** [comment]
For iOS what worked for me is the following:
1. Checked that my resource file was being played in xCode
  - Open xCode
  - Select the file
  - Click play in the xCode player
2. Once it was playing sound (had issues with some files, possibly encoding), 
  - Add the file as resource (Make sure is in Build Phases)
3. Compile the project in xCode and run it from there
  - Note: Every time you change the resources or expect new resources you need to compile your Native application either by doing it from xCode or `npm run ios`

This is my code:
```JS
const sound = new Sound(
    "myFile.mp3",
    Sound.MAIN_BUNDLE,
    error => {
      if (error) {
        console.log("failed to load the sound", error);
        return;
      }
      sound.play(() => sound.release());
    }
  );
// The play dispatcher
sound.play();
```

**Comment by shindigital** [comment]
Hi for what it's worth, I've been getting this error and after rolling my project back to earlier commits I discovered that sound stopped working after I changed the project's "Display Name" to something with a space in it. Going back to a name without spaces made it work again.

**Comment by danghung24031992** [comment]
> Hi for what it's worth, I've been getting this error and after rolling my project back to earlier commits I discovered that sound stopped working after I changed the project's "Display Name" to something with a space in it. Going back to a name without spaces made it work again.
I fixed it
https://github.com/danghung24031992/react-native-sound
