### ISSUE TITLE
Strange: Local files fail to load, but only for previously downloaded file

### ISSUE THREAD

**Issue by natashache** [zmxv/react-native-sound#122]
Hi all,

I'm using react-native-sound to play files downloaded with react-native-fetch-blob and stored in local storage. But strangely, while I'm able to immediately play the file right after it's downloaded and stored, the file fails to load after I close the app and restart again. Here's a screenshot of the console:
![screenshot 2017-02-28 19 39 10](https://cloud.githubusercontent.com/assets/19754530/23440994/9fe845ae-fded-11e6-9df1-e33875c20645.png)
Section 4 is freshly downloaded and I'm able to play it, while Section 5 was a file downloaded in the previous run of the app. As you can see, the file path structure is exactly the same. So I'm rather baffled by why this is happening!

Here's the part of my code that handles file loading and playing:
```
let Playing

function setCurrentPlaySession(section) {
  console.log('set play session to: ', section.section_id)
return {
  type: types.PLAYING,
  payload: section
}
}

export function playFile(sectionInfo) {
  return (dispatch) => {
    Playing = new Sound(sectionInfo.filePath,'', error => {
      if(error) {
        console.log(`Is section ${sectionInfo.section.section_id} loaded? ${Playing.isLoaded()}`)
        console.log(`failed to load section: ${sectionInfo.section.section_id}`, sectionInfo.filePath, error)
        return
      }
      dispatch(getPlayDuration(Playing.getDuration()))
      console.log(`section ${sectionInfo.section.section_id} is playing from ${sectionInfo.filePath}`)
      dispatch(setCurrentPlaySession(sectionInfo.section))
      if(sectionInfo.currentProgress) {
        Playing.setCurrentTime(sectionInfo.currentProgress)
      }
      Playing.play((success) => {
        console.log('finished playing ')
      })
    })

  }
}
```
Any insights on this would be much appreciated. Thanks!

This is only on IOS simulator. I'm using react-native 0.41 and react-native-sound 0.9.

Oh, and I also tried rolling back to v 0.8 of the library, as suggested by one response in a similar open issue before this one. It didn't help. Playing audio is the most key functionality of my app. So I'm rather frustrated right now. Looking into other libraries. But I really like this one, when it works.

**Comment by Pedneri1** [comment]
+1

**Comment by natashache** [comment]
BTW, I also tried rolling back to v 0.8 of the library, as suggested by one response in a similar open issue before this one. It didn't help :(

**Comment by natashache** [comment]
@benvium Any suggestions?

**Comment by benvium** [comment]
I've noticed that you're not releasing the sound when it's done. This may cause issues  - though perhaps not the exact issue you're seeing.

try seeing if this helps:

```
Playing.play((success) => {
        console.log('finished playing ')
        Playing.release();
      })
```

**Comment by Pedneri1** [comment]
@benvium Thanks for the advice. I am facing the exactly the same problem. 

Releasing the player may cause issues but not this one I've just tested and the error still persists.

**Comment by natashache** [comment]
@benvium Just tried it. I released the session whenever playing stopped and also when paused. Doesn't help. What I'm trying to think is if there's any differences between a file downloaded in the current run of the app, v.s. a file downloaded in the previous run. I can think of any difference right now, as `RNSound` is retrieving these from the same folder. It seems to be a simple action.

It looks like I'm not the only person experiencing this issue. Have you yourself tried downloading a file, storing it locally, and playing it with react native sound after closing and reopening the app? Does it not cause any problem for you?

**Comment by zmxv** [comment]
Why did the application UUID change between sessions? Have you verified that the mp3 file actually exists on that path?

**Comment by natashache** [comment]
@zmxv Not sure what you were referring to by UUID change. The files do exist. I've opened the folder and checked. The two files I was trying to play in the screenshot are in the same folder. The only difference btw them is one is downloaded in the current run of the app, the other one (failed to play) is downloaded in the previous run.

**Comment by zmxv** [comment]
@natashache Does this happen when the app runs on a device?

**Comment by benvium** [comment]
@natashache I'm wondering if it's due to react-native-fetch-blob storing the file in the temporary directory (I can see RNFetchBlob_tmp in the path to the file).  
If you download to a non-temp directory does it then work?

e.g. (from their docs)

```js
let dirs = RNFetchBlob.fs.dirs
RNFetchBlob
.config({
  // response data will be saved to this path if it has access right.
  path : dirs.DocumentDir + '/path-to-file.anything'
})
.fetch('GET', 'http://www.example.com/file/example.zip', {
  //some headers ..
})
.then((res) => {
  // the path should be dirs.DocumentDir + 'path-to-file.anything'
  console.log('The file saved to ', res.path())
})
```

**Comment by natashache** [comment]
@benvium @zmxv I realized the problem is related to what Ben mentioned above-- the file system of fetch-blob "moved" the files to a different sub-folder when restarting the app. I don't know how to fix it yet. [I Posted a question](https://github.com/wkh237/react-native-fetch-blob/issues/275) to react-native-fetch-blob. Hopefully get a response soon. @Pedneri1, maybe this is your problem as well?

**Comment by Pedneri1** [comment]
Unfortunately this is not my problem.

This is how i fetch the data using RNFetchBlob
```
RNFetchBlob
    .config({fileCache : true,appendExt : 'mp3'})
    .fetch('GET', this.props.audioSource)
    .progress((received, total) => {this.setState({downloadProgress: received/total})})
    .then((res) => {
        AsyncStorage.setItem(this.props.audioId+'', res.path());
        console.log('The file saved to ', res.path());
    });
```

The result from my console.log is: (I shortened the full address to ...)
'The file saved to ', '/Users/.../Documents/RNFetchBlob_tmp/RNFetchBlobTmp_babe4c81-1b8c-4fdb-a63d-8bde327f5908.mp3'.

No matter how many times I open and close the app, the files are still on this folder and I get the error: (the same as shown on @natashache print).

```
'Error while trying to load the file', { code: 'ENSOSSTATUSERRORDOMAIN-10875',
	  message: 'A operação não pôde ser concluída. (OSStatus erro -10875.)',
```

The code to play the downloaded file is this:

```
                let player = new Sound(this.props.audioSource ,Sound.MAIN_BUNDLE, (error) => {
                    console.log(this.props.audioSource);
                    if(error){
                        console.log("Error while trying to load the file", error);
                        return;
                    }
                });

                player.play((success)=>{
                    if(success){
                        console.log("Playing successfully");
                        player.release();
                    } else {
                        console.log("Playing not so successfully");
                    }
                });
```

where this.props.audioSource is the path to the file saved.

**Comment by natashache** [comment]
@Pedneri1 On my side, the change in file path btw app runs only happens for the folder between `Application` and `Documents`, i.e. it's a child of `Application` and the parent of `Documents` (highlighted below in red). The other parts are identical. Are you sure your _entire_ path is the same? Cuz that would be even stranger.
![untitled design 2](https://cloud.githubusercontent.com/assets/19754530/23565433/9132905c-001b-11e7-8386-bb514460efd8.png)

**Comment by Pedneri1** [comment]
@natashache I just re-checked and the file doesn't change its path.

With the terminal, I opened:

`/Users/pedroneri1/Library/Developer/CoreSimulator/Devices/E1286B0B-995C-443F-AC38-16751FDF960B/data/Containers/Data/Application/1F241259-8E5A-4A83-86C7-636D56B30FFB `
folder and  `/Users/pedroneri1/Library/Developer/CoreSimulator/Devices/E1286B0B-995C-443F-AC38-16751FDF960B/data/Containers/Data/Application/1F241259-8E5A-4A83-86C7-636D56B30FFB/Documents/RNFetchBlob_tmp` folder.

Opened and closed the app many times, and for each time I listed the contents and nothing changed.

**Comment by benvium** [comment]
Try replacing Sound.MAIN_BUNDLE with ''.  Otherwise it'll prepend your path with path to the bundle itself which you probably don't want

**Comment by Pedneri1** [comment]
I replaced, and now it looks like this:
```
let player = new Sound(this.props.audioSource, '', (error) => {
                    if(error){
                        console.log("Error while trying to load the file", error);
                        return;
                    }
                });
```
But i still get the error.

**Comment by natashache** [comment]
I made the following change to make it work, at least on simulator for now. Not sure what'd happen on an actual phone.

When retrieving the file, instead of using the file path as returned by res.path() as in the code above, I now directly use filePath = RNFetchBlob.fs.dirs.DocumentDir + '/courseSections/' + sectionInfo.section.section_id + '.mp3' when retrieving the file.

But at the end of the day, this is not a react-native-sound issue. So I'm closing this thread for now. Thanks everyone for the inputs!
