### ISSUE TITLE
setCategory no longer working

### ISSUE THREAD

**Issue by a-koka** [zmxv/react-native-sound#124]
Both the static and non-static `Sound.setCategory` methods are no longer working after upgrading RN from `0.39.2` to `0.42.0` and RNS from `github:zmxv/react-native-sound` to `0.9.0`.

I've resolved to fixing this by adding the following snippet to the end of `didFinishLaunchingWithOptions` method under `AppDelegate.m`.

```
  AVAudioSession *audioSession = [AVAudioSession sharedInstance];
  NSError *setCategoryError = nil;
  BOOL success = [audioSession setCategory:AVAudioSessionCategoryPlayback error:&setCategoryError];
  if (!success) { /* handle the error condition */ }
  NSError *activationError = nil;
  success = [audioSession setActive:YES error:&activationError];
  if (!success) { /* handle the error condition */ }
```

**Comment by ronangaillard** [comment]
I have the same issue. Without using `Sound.setCategory` it works perfectly, but if I use it I get this : 
![simulator screen shot 2 mar 2017 23 39 49](https://cloud.githubusercontent.com/assets/5607736/23530345/90643b8c-ffa1-11e6-9a72-3bffc5334f18.png)

(On iOS simulator, and using `react-native-sound` version `0.9.0` )

**Comment by benvium** [comment]
@a-koka Thanks, I'll take a look at this one now.

**Comment by benvium** [comment]
I can reproduce this one - seems that the native side isn't dealing with leaving off a value for mixWithOthers. I can fix this.

**Comment by benvium** [comment]
@a-koka @ronangaillard Fixed. Until the PR is merged and the new npm release is out you can use

```
"react-native-sound": "git+ssh://git@github.com:zmxv/react-native-sound.git#92d8fde086ecb12f7e69a4ea3bc81f0e5c16d3ba"
```

.. in your package.json file.  Alternatively, always provide the mixWithOthers parameter (e.g. Sound.setCategory('Ambient', false) )

Thanks for the bug report!
