### ISSUE TITLE
Audio does not play on device

### ISSUE THREAD

**Issue by rcchen** [zmxv/react-native-sound#127]
OS: iOS 10.2.1
Library version: 0.9.1

Seems to have been a regression from 0.9.0 to 0.9.1, as downgrading resolved the issue.

I'm downloading a file via react-native-fs, saving to the Documents folder, then playing it with react-native-sound. It worked the first time with 0.9.1, then refused to work after that. Volume rocker also no longer worked in app (pressed and did not get any on-screen feedback). No messages out of the ordinary shown when trying to debug with the callback functions.

Looking at the [sole commit][sole-commit] between 0.9.0 and 0.9.1, I can't imagine why it would cause this issue.

Let me know if there is any way I can help out here.

  [sole-commit]: https://github.com/zmxv/react-native-sound/commit/3fc0a3a510c41f268aafdfd2ca3bbca9cd5e7d0e

**Comment by benvium** [comment]
Are you using setCategory? If so what are you using? Also are you using any other audio-playing libraries? A few folks here have had trouble with other libraries setting the iOS audio session.

I see no reason why 0.9.0 should work and 0.9.1 shouldn't so I suspect something else is amiss here.

**Comment by benvium** [comment]
Another thought - are you storing the absolute path to the downloaded audio on disk?
On iOS, the path contains a GUID that iOS regularly changes (on upgrade etc), so this'll cause files to suddenly stop playing. It's best to avoid doing this and to always construct the path in code using your file manager's built-in dir methods (e.g. RNFetchBlob.fs.dirs.DocumentDir or the RNFS equivalent).

**Comment by rcchen** [comment]
> Are you using setCategory?

No.

> Also are you using any other audio-playing libraries? A few folks here have had trouble with other libraries setting the iOS audio session.

I use react-native-audio for sound recording, nothing else though.

> Another thought - are you storing the absolute path to the downloaded audio on disk?

Yep, I think that I should be covering the GUID case correctly though (snippet below)

```js
    const { message } = this.props;
    const path = `${RNFS.DocumentDirectoryPath}/audio/${message.id}.aac`;
    RNFS.mkdir(`${RNFS.DocumentDirectoryPath}/audio`)
      .then(() => {
        return RNFS.downloadFile({
          fromUrl: message.url,
          toFile: path,
        }).promise;
      })
      .then((result) => {
        if (result.statusCode === 200) {
          this.sound = new Sound(path, "", (error, props) => {
            if (error) {
              console.log(error);
            } else {
              console.log("loaded ", message);
              this.setState({ path });
            }
          });
        }
      });
```

I can close for now, as you pointed out there's probably something else going on. Thanks for the pointers on what to check!

**Comment by benvium** [comment]
@rcchen [This thread ](https://github.com/zmxv/react-native-sound/issues/42) may help - react-native-audio was setting the category during recording.

**Comment by rcchen** [comment]
That was exactly what I was looking for, thanks @benvium for pointing me that way!
