### ISSUE TITLE
Loading network files

### ISSUE THREAD

**Issue by DavoCg** [zmxv/react-native-sound#129]
Hi,

I have an issue loading mp3 files from network.

```js
 return async.map(tracks, (track, cb) => {
    const whoosh = new Sound({uri: track.soundUrl}, '', (err) => {
        if(err) return cb(err);
        return cb(null, {...track, sound: whoosh, duration: whoosh.getDuration()})
    });
}, (err, tracks) => {
    console.log('tracks :', tracks);
})
```

where ```track.soundUrl``` is for example ``` https://media.hardwax.com/audio/53830_B2.mp3 ```

but the constructor's callback is never called without any error.
Does anybody encountered the same issue ?

Thanks

I'm using : 
react-native ```0.41.2```
react-native-sound: ```0.9.1```

**Comment by zmxv** [comment]
Are you trying it on iOS or Android? This feature isn't supported on Android yet.

**Comment by DavoCg** [comment]
I was trying on iOS but i used it wrong ! Instead of passing {uri: URI} i just pass URI as first parameter and it works !

Any progression on the Android version ?

Thanks for really good work
