### ISSUE TITLE
When does Android support the network？

### ISSUE THREAD

**Issue by MingYe-dz** [zmxv/react-native-sound#134]

**Comment by TheGhoul21** [comment]
it might actually be easy enough to implement this feature. I'll try to give it a look in the next few days

**Comment by MingYe-dz** [comment]
That`s great! Another, You can implement the feature that playing with options of the follows:
 Receiver;Loud Speaker;Bluetooth;Headphones.
The most import options are Receiver and Loud Speaker.

**Comment by lamjack** [comment]
follow.

**Comment by jhilden** [comment]
@TheGhoul21 are you still planing to work on this?  Do you already have some sort of "plan of attack"?

We definitely also need this feature and would be very open to supporting this. Unfortunately, I hardly have any native Android / Java experience. But maybe there are other things that we could do (e.g. testing).

**Comment by TheGhoul21** [comment]
yeah! I haven't had much time lately, I'm really sorry. I might be work it out during this weekend. It shouldn't actually take too long to implement.

**Comment by TheGhoul21** [comment]
guys, just to let you know. This morning I implemented the feature and
looks like it was working fine. Need to do more testing with invalid URLs
(might need to change callbacks and stuff). This weekend I'll be quite
busy, but I'll find an hour to run tests and make a PR.

2017-03-30 13:56 GMT+02:00 Jakob Hilden <notifications@github.com>:

**Comment by Smileo** [comment]
@TheGhoul21 awesome, I'm waiting your PR )

**Comment by TheGhoul21** [comment]
pull request made ;) works like a charm guys

**Comment by benvium** [comment]
@TheGhoul21 Great! Thank you

**Comment by jose920405** [comment]
Can you update the `readme` please.

Almost desist to use this library ... Luckily achieved to get here

**Comment by TheGhoul21** [comment]
I'll do it later this evening as soon as I am back to work ;) I always
forget to update the Readme

2017-04-06 14:30 GMT+02:00 jose920405 <notifications@github.com>:

**Comment by GShotwell** [comment]
Thank you!

**Comment by dengunya** [comment]
Does it already work ?
Passing absolute url to constructor, second parameter - empty string, always get error on android:
`{ message: 'resource not found', code: -1 }`

**Comment by ndbroadbent** [comment]
Hi @dengunya, the pull request has not been merged yet: https://github.com/zmxv/react-native-sound/pull/141

You can try that branch by adding this to your `package.json`:

```
"react-native-sound": "TheGhoul21/react-native-sound",
```

**Comment by ohtangza** [comment]
Is it released now?
