### ISSUE TITLE
prepareToPlay()

### ISSUE THREAD

**Issue by gHashTag** [zmxv/react-native-sound#144]
The AVFoundation (AVAudioPlayer) `prepareToPlay() `method does not support the library?

**Comment by blaues0cke** [comment]
Seems this is already called: https://github.com/zmxv/react-native-sound/blob/master/RNSound/RNSound.m#L134

**Comment by trepidity** [comment]
is there an issue here still or can this be closed?

**Comment by gHashTag** [comment]
thanks @blaues0cke
