### ISSUE TITLE
delayed playback

### ISSUE THREAD

**Issue by varunrau** [zmxv/react-native-sound#150]
When I was testing, I noticed a significant (user-visible) delay between the time that `Sound.play()` is called and when the sound is heard. What's the best way to mitigate this?

In my case, I instantiate all the sounds at app initialization and use the same `Sound`s multiple times.

**Comment by lamjack** [comment]
same problem.

**Comment by snawbel** [comment]
what devices are you testing on?

**Comment by varunrau** [comment]
I'm seeing this on device (iPhone 7) and on the simulator.

**Comment by HolaMan** [comment]
I got the same issue.

But on ios simulator, it's much faster than real device. (iPhone 7 plus, RN 0.44, "react-native-audio": "^3.2.2")

**Comment by paulmelnikow** [comment]
Hi! If you are still experiencing this issue in the latest version, could you please open an issue with more details following the issue template? Thanks!

**Comment by ARKEOLOGIST** [comment]
Why is this closed? The issue still exists.

**Comment by davidg327** [comment]
Same problem, has anyone been able to fix it?

**Comment by valentinev-celadon** [comment]
Why this ticked was closed? 
Actual.
