### ISSUE TITLE
Solved - Short repeated sounds cause crashes

### ISSUE THREAD

**Issue by GShotwell** [zmxv/react-native-sound#151]
I had an issue which I think I've solved related to looping short audio files. My app has the ability to play periods of sound of indeterminate length, and how I was handling this was to use a one second long sound slip and then loop it until the application stoped the sound. This meant that you sometimes have a looping sound playing for 10 minutes, or up to an hour. 

Using this configuration the app seemed to crash frequently, and looking into it I think the issue was with looping the short sound. What I think is happening is that whenever a sound plays, the javascript layer sends a new sound down to the native layer where the sound plays. When a looping sound finishes it goes back up to the Javascript layer which sends a new sound back down to the native layer. What this means is that the shorter the sound which you are looping the more often this javascript - native communication needs to happen. This can create memory leaks and crashes. 

When I switched from a 1 second loop to a 16 minute loop the crashes (fingers crossed) disappear. I just wanted to raise an issue to see if all of this makes sense for package maintainers, and to hopefully help out future people dealing with mystery crashes.

**Comment by ndbroadbent** [comment]
@GShotwell - I think I might have fixed this in #153. (It was a race condition with a callback.)

If you would like to test the fix, then you could add my branch to your `package.json`:

```
    "react-native-sound": "ndbroadbent/react-native-sound#fix-ios-callback-crash",
```
