### ISSUE TITLE
A question: In Readme haven't seen any reference how I play sound from network

### ISSUE THREAD

**Issue by vnovick** [zmxv/react-native-sound#157]
I've been trying to play sound from network, but it seams not working. I
pass 

`const sound = new Sound('url', '', (e) => {});`

then do `sound.play();`

Doesn't seems to work.

**Comment by benvium** [comment]
Can you check the URL in your browser links directly to an mp3 (or other supported file type).

Then try:
```const sound = new Sound('url', '', (e) => {
   sound.play();
});
```

**Comment by ofirgeller** [comment]
Note that the url you pass in is going to get transformed

```
/// this should be named 'has Schema' IMHO
function isRelativePath(path) {
  return !/^(\/|http(s?))/.test(path);
}


    this._filename = basePath ? basePath + '/' + filename : filename;

    if (IsAndroid && !basePath && isRelativePath(filename)) {
      this._filename = filename.toLowerCase().replace(/\.[^.]+$/, '');
    }
```
This is a bit of a trap.

If you pass in the url as one parameter (no separate base path) and you are on android and you did include the schema, the library is going to lower case the file name, that not a good thing as file name unlike other parts of urls can be case sensitive.

On the other hand if you separate the url into two params you must make sure you don't have a '/' at the end of the basePath as one more will be added and you will also get an error.

Not meaning to disparage the person who wrote this code. I'm very thankful for the work you did.

**Comment by codesinghanoop** [comment]
I just logged the url in the third party and you are right the file name is getting lower cased.... so can you please give me one example on the same...

**Comment by ofirgeller** [comment]
break the url up into a file name (1st param) and a base path (2nd param) , make sure the base path does not end with a '/' 
then it should work.

**Comment by codesinghanoop** [comment]
Can you please provide me one example..

**Comment by codesinghanoop** [comment]
Still not working..Now my URL going into the third party is the exact what i need but still not playing any sound...

**Comment by lauriegriffiths** [comment]
`new Sound('sound.mp3', 'https://example.com/assets', (error) => { }
`

That should would for you.  I got a bit confused too!

**Comment by ofirgeller** [comment]
@codesinghanoop  If you know that the url is correct the next thing to do is to look at the log for an error message.

enter into your terminal/console
`react-native log-android`

 actually that's the first thing to do :) 

For example if it says something about encoding maybe you are trying to play an ogg file but android can only play mp3.

**Comment by codesinghanoop** [comment]
Does it supports .wav file ???

**Comment by codesinghanoop** [comment]
The error is : { message: 'resource not found', code: -1 }

**Comment by SoorajChandran** [comment]
I'm facing the same issue. Any solutions ?

**Comment by trepidity** [comment]
closing, please open a new issue if this is still an issue.
