### ISSUE TITLE
Play sound in background 

### ISSUE THREAD

**Issue by jakubzloczewski** [zmxv/react-native-sound#16]
Hey, thanks for great plugin - it's awesome!

Do you know if there is possibility to play sound when app is in background using this package?

**Comment by zmxv** [comment]
Not at the moment. PRs are always welcome.

**Comment by DVassilev** [comment]
@zmxv Any pointers on how this would be implemented, interested at seeing if I can add it in.

**Comment by Reptilijonas** [comment]
Hi, maybe https://github.com/zmxv/react-native-sound/pull/25 could help (iOS only)? To play sound when app is in background, you could simply call mySound.setCategory("Playback");

**Comment by bringking** [comment]
@zmxv Any status on merging #25? We need it and I would like to avoid running off a fork. Anything we can do to help move it along?

**Comment by zmxv** [comment]
Sorry for the slow response. I'll verify the PR in a day.

**Comment by glamp** [comment]
I'm running the following and when I leave the app, the sound fades and then stops.

```
var filepath = '/path/to/audio/../sound.mp3';
var currentAudio = new Sound(filepath);
currentAudio.setCategory('Playback');
```

Am I doing something wrong? I've installed from:

```
npm install git+ssh://git@github.com/zmxv/react-native-sound.git
```

**Comment by glamp** [comment]
Ok got it working. Added this to my *Info.plist* file. 👍 
```
    <key>UIBackgroundModes</key>
    <array>
        <string>audio</string>
    </array>
```
Thanks for a great library!

**Comment by zmxv** [comment]
@glamp I've updated README with your tip. Thanks!

**Comment by tmaly1980** [comment]
What about Android?

**Comment by yelnar** [comment]
I cannot play audio in the background on Andorid. Any idea on what I could do wrong?

**Comment by Marinaarimany** [comment]
@yelnar Did you find a solution ? Thank you

**Comment by yelnar** [comment]
@Marinaarimany I ended up using [react-native-background-timer](https://github.com/ocetnik/react-native-background-timer).

**Comment by Marinaarimany** [comment]
@yelnar Thank you ;)
