### ISSUE TITLE
How can i play sound file using android absolute path? [react-native-get-music-files] npm module

### ISSUE THREAD

**Issue by themakerman** [zmxv/react-native-sound#163]
I am using react-native-get-music-files npm module to get all the music files stored on my local disk. The npm module i mentioned returns me a JSON file containing paths to .mp3 files as below format -:
/storage/emulated/0/Music/EDM/10 second Optimus prime countdown.mp3

Now the problem is whenever i initialize the constructor with this path and call isLoaded() it always returns false and so i cannot play any sound.

var whoosh = new Sound(this.state.musicFiles[0].path,'', (error) => console.log('executed'));
 console.log(whoosh.isLoaded());

Am i doing something wrong while initializing the constructor with the path?

**Comment by benvium** [comment]
try:

```js
var whoosh = new Sound(this.state.musicFiles[0].path,'', (error) => console.log(whoosh.isLoaded()));
```

**Comment by themakerman** [comment]
@benvium isLoaded() returns me true. But whoosh.play() does nothing.

`var whoosh = new Sound(this.state.musicFiles[0].path,'', (error) => console.log(whoosh.isLoaded()));
    if (whoosh.isLoaded()) {
        whoosh.setVolume(1);
        whoosh.play((success) => {
          if (success) {
            console.log('successfully finished playing');
          } else {
            console.log('playback failed due to audio decoding errors');
          }
        });
      }`

**Comment by themakerman** [comment]
Got it working. Used States to track the changes and then played the file :).

**Comment by wezzy-web** [comment]
can you solve my problem plz
