### ISSUE TITLE
0.10.0 broken

### ISSUE THREAD

**Issue by otmichael** [zmxv/react-native-sound#164]
Correct me if I'm wrong, but v0.10.0 might be broken. When running code with v0.10.0, Sound.MAIN_BUNDLE logged as undefined and loading sound didn't work.

Switching back to ~0.9.0 fixed the issue. Same code, now Sound.MAIN_BUNDLE is defined, and loading audio works.

**Comment by JasonStu** [comment]
My project in android the same as! but in ios can be work ,and other question  how to play remote  sound ?

**Comment by otmichael** [comment]
https://github.com/zmxv/react-native-sound/pull/141
我认为现在只使用于iOS
尝试：
var whoosh = new Sound(remoteURL, Sound.MAIN_BUNDLE, (error) => {
});

**Comment by themakerman** [comment]
Can someone solve problem I am facing #163

**Comment by Kerumen** [comment]
Same issue here. Sound broken since 0.10.0 on Android.

**Comment by njwest** [comment]
Same issue, couldn't get local /raw .mp3's to play on Android with 0.10.0. Reverted to 0.9.0 and now they play...
