### ISSUE TITLE
[iOS]Sound is broken

### ISSUE THREAD

**Issue by razor1895** [zmxv/react-native-sound#166]
The sound is broken no matter the mp3 file is retrieved from network or local directory.
I use 0.10.0 version and i wonder if any meet the same issue?

**Comment by razor1895** [comment]
Ah.... I found it was the react-navigation issue

**Comment by razor1895** [comment]
I have to admit that I am stupid..... I played a song in listview row components and that canse the song was played multiple times at the second

**Comment by cfournel** [comment]
@razor1895 could you tell me more about the react-natigation issue ? playing sound on ios is not working on my project while it perfectly works on android
