### ISSUE TITLE
Enable play in silent mode

### ISSUE THREAD

**Issue by alizbazar** [zmxv/react-native-sound#17]
Hi!

Could you enable a switch for playing the audio in silent mode?

http://stackoverflow.com/a/12868879/528675

Great job with the library so far!

-Albert

**Comment by nnmer** [comment]
try this #21 , worked for me

**Comment by zmxv** [comment]
@nnmer 's patch has been merged. Thank you!

**Comment by feyzilim** [comment]
You can use         
`SoundPlayer.setMixAudio(false);`
this is set category Playback
