### ISSUE TITLE
The operation couldn’t be completed. (OSStatus error -10875.)

### ISSUE THREAD

**Issue by x4922** [zmxv/react-native-sound#171]
Use the react-native-audio recording to give the following error in the address given in react-native-sound:
![0acfe5ec-7a0b-40c9-81c5-ae3a68a14b45](https://cloud.githubusercontent.com/assets/17464781/25801228/258d8e5a-341f-11e7-8184-b2a4276618fd.png)
Here's my code:

var sound = new Sound(this.state.audioPath, Sound.MAIN_BUNDLE, (error) => {
          if (error) {
            console.log('failed to load the sound', error);
            return
          }else{
            console.log('duration in seconds: ' + sound.getDuration() + 'number of channels: ' + sound.getNumberOfChannels());
            sound.play((success) => {
              if (success) {
                console.log('successfully finished playing');
              } else {
                console.log('playback failed due to audio decoding errors');
              }
            });
          }
          
        });
this.state.audioPath : /var/mobile/Containers/Data/Application/C5A0D128-16CF-4713-AC8C-056C37F4DD26/Documents/audio1494239940000.aac

**Comment by escobar5** [comment]
It would be really helpful if you post a comment on how did you solve the problem, so others can find it

**Comment by vacoo** [comment]
Just wrap `basePath` in `encodeURIComponent` and everything will work
```
var SOUND_PRESS = new Sound(getSoundName('sound_press'), encodeURIComponent(Sound.MAIN_BUNDLE));
```
