### ISSUE TITLE
Silent button does not mute sounds from react-native-sound

### ISSUE THREAD

**Issue by blaues0cke** [zmxv/react-native-sound#173]
I cannot find any solution to mute the sounds when the iPhone silent switch is on "silent". The iPhone just plays the Sounds at maximum volume. Is there a way to support that switch?

(I am trying to implement [react-native-silent-switch](https://github.com/gnestor/react-native-silent-switch) but it looks like a bad practice to me to play a unhearable sound in the background just to detect the switch state)

**Comment by blaues0cke** [comment]
Ok, got it. Its a feature. I changed the category from `Playback` to `Ambient` to make it work.

```
Sound.setCategory('Playback');
```

```
Sound.setCategory('Ambient');
```

**Comment by sthompsond** [comment]
I've pushed code to the st-sound-fix branch. It just needs to be tested on a physical ios device.

**Comment by Linoa65** [comment]
Hello,

Problem is that Playback allow sounds to get played in background, but in my case, I want to play a sound in background, but managed by the "Ring" channel volume. Ambient cannot resolve my case, because of, the volume is cut when app goes background, and get back when app goes foreground.

**Comment by Pingou** [comment]
If I put the category to Ambient, no sound is played at all, mute or not, on iOS 14.

**Comment by Ehtesham25** [comment]
@blaues0cke It doesn't work when launch the app. it gives audio sound however when remove silent mode to normal and then normal to silent it works. any Solution.
