### ISSUE TITLE
It looks like it does not work on Android

### ISSUE THREAD

**Issue by yellow066** [zmxv/react-native-sound#18]
Hello.

I tried to play call .play() but it does not work and did not give me any error. I tried wav and mp3 files. Also .duration and .numberOfChannels give undefined value, when I changed to ._duration and ._numberOfChannels it gave me duration and -1 in numberOfChannels.

**Comment by zmxv** [comment]
What version of RN are you using? Did you follow all the steps to set up the native module on Android?

**Comment by yellow066** [comment]
react-native-cli: 0.1.10
react-native: 0.19.0
I did all steps. It gives me only correct duration if I use audio._duration.

**Comment by zmxv** [comment]
Can't reproduce.

**Comment by rohitgoyal** [comment]
No working for me on Android
