### ISSUE TITLE
Play callbacks not firing

### ISSUE THREAD

**Issue by mujtaba-ahmad** [zmxv/react-native-sound#187]
I am creating an android app, sound plays but i want to trigger an event when it ends, but pay callbacks not firing.

`const Sound = require('react-native-sound');`
`Sound.setCategory('Playback', true);`
`const s = new Sound(NARRATION_RULES[narrationNumber].sound, Sound.MAIN_BUNDLE, (e) => {`
               ` if (e) {`
                    `console.log('error', e);`
                `} else {`
                    `s.setSpeed(1);`
                    `console.log('duration', s.getDuration());`
                   ` s.play(() => {`
                        `console.log('Not Printing');`
                     `});` 
                 `}`
`});`

My console statement isn't printing anything.
Help Needed!!

**Comment by mujtaba-ahmad** [comment]
Also i am unable to release resource.

**Comment by mujtaba-ahmad** [comment]
Another thing i have noticed, this only happens when i try to play sound in my async actions.

**Comment by gvenk** [comment]
The `s.setSpeed()` causes the player to start playing, according to the [MediaPlayer documentation](https://developer.android.com/reference/android/media/MediaPlayer.html#setPlaybackParams(android.media.PlaybackParams)): 

> After the object is prepared, calling it with zero speed is equivalent to calling pause(). After the object is prepared, calling it with non-zero speed is equivalent to calling start()

By the time `play()`-method is called, the player is already playing, so the console.log message is never reached.
