### ISSUE TITLE
Can't loop

### ISSUE THREAD

**Issue by irrigator** [zmxv/react-native-sound#19]
I'm using react-native 0.20.0 and react-native-sound 0.7.3. The audio only plays once no matter which number of loops was given.

**Comment by KevinHu2014** [comment]
@irrigator 
I am using Android 5.01 React-native 0.24
I am able to do the indefinite loop the by giving a negative number 
ex: `setNumberOfLoops(-1);`

**Comment by zmxv** [comment]
@irrigator The limitation is mentioned in the API documentation: infinite loop (-1) works on both platforms, but finite loops (>0) are iOS-only.

**Comment by roysG** [comment]
the value "-1" not working.
The sound is play just once in ios.
Any update?

**Comment by bakystefan** [comment]
> the value "-1" not working.
> The sound is play just once in ios.
> Any update?

Yea, you are right, any update?! @zmxv

**Comment by Akash-T2S** [comment]
sound = new Sound('order_beep.mp3', Sound.MAIN_BUNDLE, (error) => {
                if (error) {
                    console.log('error', error);
                    return;
                }
                // Play the sound with an onEnd callback
                sound.setNumberOfLoops(-1);
                sound.play();
            });

loop working fine in android, iOS not able to loop
Any Update on this?
