### ISSUE TITLE
Can't play remote .aac files on iOS

### ISSUE THREAD

**Issue by mikeknapp** [zmxv/react-native-sound#199]
Hi there - thanks for a great library!

Thanks to the new 10.0.2 update, audio was loading fine on Android, however I kept getting the `OSStatus error 2003334207` errors on iOS.

Looking into it, it seems that AVAudioPlayer doesn't like remote .aac/m4a files when initialized with the contents of a URL. 

The fix is to use `AVPlayer` instead, or do something like this:

```objectivec
NSData* data = [NSData dataWithContentsOfURL:url] ;
AVAudioPlayer* audioPlayer = [[AVAudioPlayer alloc] initWithData:data error:outError];
```

I'm going to temporarily solve this in my own project by using mp4 files, however it would be great if RNS could handle .aac/m4a files out of the box - as they are becoming more popular. Thanks! :) 

[Source](https://stackoverflow.com/questions/20104398/avaudioplayer-initwithcontentsofurl-returns-nil-for-aac-m4a-files).

**Comment by mikeknapp** [comment]
Actually, you can't play .mp3 files either. I've created a pull request that gets this working.

**Comment by benvium** [comment]
Can you try out 0.10.2 from npm? This should be fixed now. https://github.com/zmxv/react-native-sound-demo has a test for remote aac files

**Comment by mikeknapp** [comment]
Looks good to me! Thanks!
