### ISSUE TITLE
Cannot read property 'IsAndroid' of undefined

### ISSUE THREAD

**Issue by findzen** [zmxv/react-native-sound#215]
On iOS, in fresh project generated by latest version of `create-react-native-app`: RNSound is not defined in `NativeModules` of `react-native`.

```
"dependencies": {
    "expo": "^18.0.3",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-sound": "^0.10.3"
  }
```

**Comment by benvium** [comment]
Did you run react-native link react-native-sound?

**Comment by findzen** [comment]
Yep

**Comment by gasparteixeira** [comment]
Same here. Running through Expo a got this error. Also, I tried another way and got the application broken.

**Comment by gasparteixeira** [comment]
FYI ... https://docs.expo.io/versions/v17.0.0/sdk/audio.html great stuff for expo users!

**Comment by jpapillon** [comment]
You need to delete your derived data in XCode: `/Users/{yourUserName}/Library/Developer/Xcode/DerivedData`

**Comment by JimSchofield** [comment]
Restarting Android Studio, my emulator, and terminal seemed to work for me.

**Comment by MPieter** [comment]
I had the issue as well, I deleted `/Users/{yourUserName}/Library/Developer/Xcode/DerivedData` and rebuilded everything, solved it.

**Comment by divyam3897** [comment]
I am having the similar error in android too, How can I fix it?

**Comment by jpapillon** [comment]
@divyam3897 https://github.com/zmxv/react-native-sound/issues/215#issuecomment-311783335

**Comment by baldurpan** [comment]
I'm only getting this error when I try to build for production. I tried removing DerivedData and rm -rf ios/build/* but so far I'm out of luck.

`2017-07-19 23:40:08.572 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 's.IsAndroid')
2017-07-19 23:40:08.577 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 's.IsAndroid')
2017-07-19 23:40:08.577 [error][tid:com.facebook.react.JavaScript] this._lazyCallableModules[e] is not a function. (In 'this._lazyCallableModules[e]()', 'this._lazyCallableModules[e]' is undefined)`

**Comment by LeeZC** [comment]
you need run react-native link react-native-sound

**Comment by dominictracey** [comment]
I have this problem running test cases from Jest. Works fine in emulators and hardware for both Android and iOS.

**Comment by gvenk** [comment]
create-react-native-app only works with pure JavaScript compontents. So it won't work with react-native-sound, because it requires native code.

> What are the limitations of Create React Native App?

> The main limitation of a Create React Native App project is that it must be written in pure JavaScript and not have any dependencies which rely on custom native code (i.e. ones which require running react-native link to work). This allows the projects to load directly on a phone without native compilation, and also means that it's not necessary to install or use Android Studio or Xcode.

https://github.com/react-community/create-react-native-app#what-are-the-limitations-of-create-react-native-app

**Comment by justinTime225** [comment]
I am running into the same issue, where it builds for IOS but not for Android.  It errors out at the import statement with undefined is not an object (evaluating 'RNSound.IsAndroid').  
Android studio had an error about not being able to have non-gradle java modules and android-gradle modules in one project.  I think it was resolved once I updated react-native-sound in from 23.0.1 to 25.0.0 in studio.  I've reinstalled react-native-sound, relinked, and rebuilt everything but to no avail.  Any help would be appreciated.

i have "react-native": "0.46.4 and "react-native-sound": "^0.10.4"

**Comment by trepidity** [comment]
@justinTime225 it sounds like you are using a native java project and not react project, is that not the case?

**Comment by justinTime225** [comment]
@trepidity I am using react-native.  I am trying to launch it on the android emulator using android studio.  The app launches perfectly when I do react-native run-ios but not for android studio.

**Comment by JperF** [comment]
I am running into the same issue as @justinTime225 was running into.

Compiles fine in `react-native run-ios` but not for `react-native run-android`

**Comment by tirrorex** [comment]
iOS app crashing, built for release on device.
Framework linked properly, derived data deleted.
Same error on app launch than everyone.

**Comment by jchirik** [comment]
^ seconded

**Comment by devagul93** [comment]
Getting this issue in iOS simulator, Framework linked, derived data deleted.
Working fine on Android Device

**Comment by mikeknapp** [comment]
Have a look at https://github.com/zmxv/react-native-sound/issues/36#issuecomment-284443489 -- this works for me

**Comment by RassaLibre** [comment]
Had exactly the same problem. Cleaning the project (Product->Clean) in Xcode surprisingly helped :-)

**Comment by mr4227** [comment]
I am getting a similar error:
"Uncaught Error: undefined is not an object (evaluating 'r.IsAndroid')"
The project works fine on my android emulator when I run 'react-native run-android', but when I loaded it onto google play and ran it in test mode I get this error on my phone.

**Comment by SamiChab** [comment]
Restarting the `React Packager` did it for me

**Comment by marcelobbfonseca** [comment]
> FYI ... https://docs.expo.io/versions/v17.0.0/sdk/audio.html great stuff for expo users!

for newcomers using expo try https://docs.expo.io/versions/latest/sdk/audio

**Comment by abhi-nahi** [comment]
You can use manual linking in order to solve this problem.

**Comment by vladbars** [comment]
Make sure that you run `pod install` after `react-native link react-native-sound` in case you are use pods. In other case link it manually [https://github.com/zmxv/react-native-sound/issues/36#issuecomment-284443489](https://github.com/zmxv/react-native-sound/issues/36#issuecomment-284443489)

**Comment by paulmelnikow** [comment]
See also #128 which is the same issue.

Running `pod install`, deleting `ios/build`, and running `react-native run-ios` solved this for me.

If you're still experiencing this issue, please open a new issue with steps to reproduce. If you have a universal solution, please open a pull request with a documentation update.

**Comment by tirrorex** [comment]
So basically you're closing an issue because "it works for me".
That's not how things works you know?

**Comment by paulmelnikow** [comment]
To elaborate, this isn't something that will be fixed by a code change in the library. Rather it's a tooling issue that manifests in a lot of different ways depending on people's setup. If you search the issues for IsAndroid and read the threads you'll see there isn't a single fix that works for everyone.

Apart from collecting all the workarounds in one place, the only other thing that can be done is to troubleshoot someone's specific situation, which is better done at the time they're experiencing the problem.

I'll open a new issue for the doc update.

**Comment by Cat107** [comment]
> See also #128 which is the same issue.
> 
> Running `pod install`, deleting `ios/build`, and running `react-native run-ios` solved this for me.
> 
> If you're still experiencing this issue, please open a new issue with steps to reproduce. If you have a universal solution, please open a pull request with a documentation update.

I don't understand what does it mean "running pod install"?

**Comment by ezratechdev** [comment]
For anyone developing for Android using React Native CLI in the Linux environment and facing this issue, by following these steps I was able to fix the issue on my end:

1. cd android
2. ./gradlew clean
3. cd ..
4. yarn start --reset-cache
5. yarn android (on another terminal: CTRL + SHIFT + T)

**Comment by simranenvsoft** [comment]
i am getting this error when i try to run the react-native sound library on my android
![Screenshot_20241105_172417_AudioBook](https://github.com/user-attachments/assets/41bd69f8-165a-475c-8a2c-858e95ef8bfc)
