### ISSUE TITLE
How i can pause sound on incoming call in Android OS?

### ISSUE THREAD

**Issue by kot-ezhva** [zmxv/react-native-sound#217]
Now if the sound plays and I get an incoming call, then in the speaker I hear both the caller and the sound being played.

**Comment by hssrrw** [comment]
@kot-ezhva from what I can see in the sources,  changing audio focus isn't supported.

**Comment by northern-fox** [comment]
@kot-ezhva Did you solve this issue?

**Comment by kot-ezhva** [comment]
@northern-fox No.

**Comment by northern-fox** [comment]
@kot-ezhva you can use [https://github.com/priteshrnandgaonkar/react-native-call-detection](https://github.com/priteshrnandgaonkar/react-native-call-detection) this lib for  detection
