### ISSUE TITLE
Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by saeedhei** [zmxv/react-native-sound#220]
Why after using `react-native run-android` I Get this?:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> java.io.IOException: Could not delete path 'D:\Projects 2016\Web\Android\2 Defullt Project\Mohajerkade\android\app\build\generated\source\r\debug\android\support\v7'.

**Comment by saeedhei** [comment]
Solved By making my folders permission Full Control

**Comment by alanyong91** [comment]
How you set folders permission to full control ?

**Comment by muganwas** [comment]
Could someone please help out here, how do you grant permission to the folders??

**Comment by trepidity** [comment]
On the properties of the Folder in Windows Explorer.
https://msdn.microsoft.com/en-us/library/bb727008.aspx

**Comment by muganwas** [comment]
I sorted it out, didn't have to mess around with any permissions. just had to open a terminal in my application root folder and ran this:
cd android && gradlew clean
