### ISSUE TITLE
The operation couldn’t be completed. (OSStatus error 2003334207.)

### ISSUE THREAD

**Issue by oliviachang29** [zmxv/react-native-sound#221]
I occasionally encounter this error and I don't know what causes it. Below is what is printed to the console:

```
* Object {code: "ENSOSSTATUSERRORDOMAIN2003334207", message: "The operation couldn’t be completed. (OSStatus error 2003334207.)", nativeStackIOS: Array(18), domain: "NSOSStatusErrorDomain", userInfo: Object}
    * code:"ENSOSSTATUSERRORDOMAIN2003334207" domain:"NSOSStatusErrorDomain" message:"The operation couldn’t be completed. (OSStatus error 2003334207.)" nativeStackIOS:Array(18) userInfo:Object __proto__:Object 
```

**Comment by mgcmgc110** [comment]
So do I

**Comment by lukecwilliams** [comment]
Duplicate of https://github.com/zmxv/react-native-sound/issues/64#issuecomment-312381532 - check out answers in that thread.

**Comment by jackple** [comment]
I use the network file and I have the same error

**Comment by FRodrigues21** [comment]
Had this problem.
Solved it by adding Sound.MAIN_BUNDLE to the Sound constructor and moving the .mp3 files to the resources folder of the project in XCode.

_(Note: Keeps working on Android without problems)_

**Constructor**
`var Beep = new Sound('beep_high.mp3', Sound.MAIN_BUNDLE);`

**Folder structure**
<img src="https://i.gyazo.com/c11849f401e4a1e85f18742f63554bf5.png" width="200" />

**Comment by trepidity** [comment]
#334

**Comment by Nitingadhiya** [comment]
I use network file and same error
