### ISSUE TITLE
.AAC format can not be played in Android

### ISSUE THREAD

**Issue by Amissioz** [zmxv/react-native-sound#222]
I want to play a AAC network audio, but I can't play it on Android. but IOS work.
here is my code ：

 setTestState(testInfo, component, status) {
    if(status=='win'){
      this.setState({sounding: false})
    }
    component.setState({tests: {...component.state.tests, [testInfo.title]: status}});
  }
  playSound(testInfo, component) {
    this.setState({sounding: true})
    this.setTestState(testInfo, component, 'pending');

    const callback = (error, sound) => {
      if (error) {
        this.setState({sounding: false})
        Alert.alert('error', error.message);
        this.setTestState(testInfo, component, 'fail');
        return;
      }
      this.setTestState(testInfo, component, 'playing');
      // Run optional pre-play callback
      sound.play(() => {
        // Success counts as getting to the end
        this.setTestState(testInfo, component, 'win');
        // Release when it's done so we're not using up resources
        sound.release();
      });
    };

    // If the audio is a 'require' then the second parameter must be the callback.

      const sound = new Sound(testInfo.url, Sound.MAIN_BUNDLE, error => callback(error, sound));
  }

please help me when you look

**Comment by zmGitHub** [comment]
me to  and react-native-video cant play aac file

**Comment by zmGitHub** [comment]
i have test react-native-sound-demo  and  remote aac file cant play please  help us

**Comment by arrygoo** [comment]
@Amissioz did you find a solution?

**Comment by sejas** [comment]
same error

**Comment by cokealmonacid** [comment]
Same error here, did you find the solution? got the "playback failed due to audio decoding errors" log after recording

**Comment by sejas** [comment]
@cokealmonacid 
Finally I discovered that it was my error.
I don't know why, I was using `encodeURI` function, then I passed the url to `new Sound(`.
I guess I copied the code from some example. And it was working ok in iOS, but not in Android.

When I removed the call to `encodeURI `, then it worked perfectly in both platforms.
