### ISSUE TITLE
Sound is not played if URL contains special characters (ä,ö,ü etc.)

### ISSUE THREAD

**Issue by ahaus** [zmxv/react-native-sound#223]
If we want to play a sound with a remote url containing special characters (ä,ü, ..., e.g. https://test.xxx.com/user1/töllergebäude-123.aac) the library throws the following error:
```
{code: "ENSOSSTATUSERRORDOMAIN-10875", message: "The operation couldn’t be completed. (OSStatus error -10875.)", nativeStackIOS: Array(17), domain: "NSOSStatusErrorDomain", userInfo: Object}

code:"ENSOSSTATUSERRORDOMAIN-10875"

domain:"NSOSStatusErrorDomain"

message:"The operation couldn’t be completed. (OSStatus error -10875.)"
```

**Comment by ahaus** [comment]
Error was reproduced on ios 8.4 and ios 10.2

**Comment by ahaus** [comment]
Using
`uri = encode(uri)`
in the Javascript code did not work either.

**Comment by ahaus** [comment]
We fixed the problem on replacing the line 124 in RNsound.m from 
`fileNameUrl = [NSURL URLWithString:[fileName stringByRemovingPercentEncoding]];`
to
`fileNameUrl  = [NSURL URLWithString:[fileName stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];`

We hope this helps others as well who encounter this problem.

**Comment by alfonsodev** [comment]
related issue 
https://github.com/zmxv/react-native-sound/issues/229
