### ISSUE TITLE
Problem twice Play

### ISSUE THREAD

**Issue by saeedhei** [zmxv/react-native-sound#224]
I'm Using Your Demo Project and I want to read from url, But When I Click in Play Button twice, It play 2 times, I want to have 1 Time for play and 1 time for Stop, What Should I Do? 
Thanks

**Comment by lossen** [comment]
Same error

**Comment by abdulKarim002** [comment]
Assign a props isRunning and configure the play button something like this
`{this.state.isRunning? 'Pause': 'Play'}`

**Comment by trepidity** [comment]
@saeedhei @lossen you two good with the answer?

**Comment by saeedhei** [comment]
Please add a simple example for us.
Thank you.
