### ISSUE TITLE
[Request] Support for STREAM_ALARM on Android

### ISSUE THREAD

**Issue by juanamd** [zmxv/react-native-sound#227]
Hello,

I would like to request the addition of having the option to change the STREAM_MUSIC type to STREAM_ALARM, for uses related to alarms with sound.

For reference: https://stackoverflow.com/questions/7057115/android-mediaplayer-how-to-play-in-the-stream-alarm

Thanks

**Comment by franck-nadeau** [comment]
I added the required change for this in this PR:

https://github.com/zmxv/react-native-sound/pull/570
