### ISSUE TITLE
undefined is not an object (evaluating 'RNSound.setLooping')

### ISSUE THREAD

**Issue by Shakarang** [zmxv/react-native-sound#23]
Hello, I have the same problem as another had before but on Android platform. 

I use React 0.21 and Android Api 22.

**Comment by jenbennings** [comment]
I'm also experiencing this issue on 0.21.

**Comment by jenbennings** [comment]
@Shakarang Did you upgrade react-native recently? I just tried running through the installation steps (linking it in Xcode etc.) and this seems to have fixed it.

**Comment by Shakarang** [comment]
Hello,
I juste upgraded one hour ago. On iOS it works fine, but on android now I've got "undefined is not a function (evaluating 'RNSound.enable(enabled)')

I'm new to React and I don't know, maybe I've done something wrong. I've correctly followed your explanations for settings.gradle and build.gradle but in my MainActivity I don't have the OnCreate method preset but I've getPackages() method. Si here is my main : 
`public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "ReactTest";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.asList(
                new MainReactPackage(),
                new RNSoundPackage()
        );
    }
}
`
I'm also testing on GenyMotion device. Can this be the source of my problems?

**Comment by peternann** [comment]
It appears you have followed the README accurately, and you have added the getPackages method into MainActivity.java

The README seems wrong (at the time of typing).
Doco here indicates the correct class to add to is MainApplication.java:
http://facebook.github.io/react-native/docs/native-modules-android.html

I moved it, and things finally started to work.

**_Please correct the README ASAP. Shitty trap for new users..._**
