### ISSUE TITLE
isReleased function?

### ISSUE THREAD

**Issue by wayne1203** [zmxv/react-native-sound#231]
May I know is it have a function to get is it released of the audio?
isLoaded seems like  always return true when first loaded.

**Comment by gvenk** [comment]
This may be a bug. I can see the loaded flag is not reset after releasing the audio.

**Comment by trepidity** [comment]
I don't see a `isReleased` method. Am I missing it?

**Comment by gvenk** [comment]
There is an [`isLoaded`](https://github.com/zmxv/react-native-sound/blob/master/sound.js#L50) method, but this always returns true after the Player has been initialized. Even when the `release` method is called, the isLoaded is still returning true, I think it must return false after the `release' has been called.

**Comment by gvenk** [comment]
I'll submit a PR, because I think this is a bug.
