### ISSUE TITLE
Get current time while playing

### ISSUE THREAD

**Issue by cheesest3ak** [zmxv/react-native-sound#235]
How can I get the current time while playing

**Comment by riosimatupang** [comment]
Hi @cheesest3ak, same here, I am wondering how to get the current time while playing.

But it should be as simple as this:

whoosh.play(() => {
      // Get the current time
      sound.getCurrentTime((seconds) => {
          this.setState(currentTime: seconds)
      });
});

constructor(props) {
    super(props);

    this.state = {
      currentTime: 0
    };
}

But when every time I get the current time, it always returns -1

<Text>{this.state.currentTime}</Text>

**Comment by gvenk** [comment]
The callback in the `play`-method, is an `onEnd`-callback, so this only gets called after the file has finished playing or an error occurred. 

I'm using a timer to get the currenttime, something like this:

```
play() {
  this.tickInterval = setInterval(() => { this.tick(); }, 250);
  this.s.play((success) => {
  if (success) {
    if (this.tickInterval) {
     clearInterval(this.tickInterval);
     this.tickInterval = null;
    }
  } else {
    if (this.tickInterval) {
      clearInterval(this.tickInterval);
      this.tickInterval = null;
    }
    console.log('error');
  }
}

tick() {
  this.s.getCurrentTime((seconds) => {
    if (this.tickInterval) {
      this.setState({
        currentTime: seconds,
      });
    }
  });
}
```

**Comment by gustavoInventdigital** [comment]
> Como posso obter a hora atual enquanto jogo

`import React, {useCallback, useEffect, useState} from 'react';
import {View, Text, StyleSheet} from 'react-native';
import Slider from '@react-native-community/slider';
import Sound from 'react-native-sound';
import {TouchableRipple} from 'react-native-paper';
import IconFeather from 'react-native-vector-icons/Feather';

const PlaySound: React.FC = () => {
  const [durationSlider, seDurationSlider] = useState(0);
  const [timeSlider, setTimeSlider] = useState(1);
  const [urlAudio, setUrlAudio] = useState('http://192.168.100.9/musica.mp3');
  const [isPlayer, setIsPlayer] = useState(false);
  const [player, setPlayer] = useState(new Sound('', ''));

  useEffect(() => {
    Sound.setCategory('Playback');
    const whoosh = new Sound(urlAudio, '', error => {
      if (error) {
        console.log('error: ', error);
      }
    });

    setPlayer(whoosh);
  }, [urlAudio]);

  useEffect(() => {
    var timerID = setInterval(() => loadCurrentTime(), 1000);

    return function cleanup() {
      clearInterval(timerID);
    };
  });

  const loadCurrentTime = useCallback(() => {
    if (isPlayer) {
      player.getCurrentTime((seconds: number, isPlaying: boolean) => {
        console.log('loadCurrentTime: ', seconds);
        setTimeSlider(seconds);
      });
    }
  }, [player, isPlayer]);

  return (
    <View style={styles.main}>
      <Text>Current Time: {timeSlider}</Text>
      <View style={styles.mainSound}>
        {!isPlayer ? (
          <>
            <TouchableRipple
              onPress={() => {
                seDurationSlider(player.getDuration());
                setIsPlayer(!isPlayer);
                player.play();
              }}>
              <IconFeather name="play" size={25} />
            </TouchableRipple>
          </>
        ) : (
          <>
            <TouchableRipple
              onPress={() => {
                player.pause();
                setIsPlayer(!isPlayer);
              }}>
              <IconFeather name="pause" size={25} />
            </TouchableRipple>
          </>
        )}

        <Slider
          style={styles.slider}
          minimumValue={0}
          maximumValue={durationSlider}
          minimumTrackTintColor="#f6e3b0"
          maximumTrackTintColor="#f6e3b0"
          thumbTintColor="#f6e3b0"
          value={timeSlider}
          step={1}
          onValueChange={values => {
            player.setCurrentTime(values);
            setTimeSlider(values);
          }}
        />
      </View>
    </View>
  );
};

export default PlaySound;

const styles = StyleSheet.create({
  main: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingTop: 20,
  },
  slider: {
    width: '80%',
  },
  mainSound: {
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
  },
});
`

**Comment by muhammaddawood129** [comment]
@gustavoInventdigital  Argument 1 (RCTResponseSenderBlock) of RNSound.play must not be null

RCTLogArgumentError(RCTModuleMethod*, unsigned long, objc_object*, char const*)
    RCTModuleMethod.mm:67
__41-[RCTModuleMethod processMethodSignature]_block_invoke.164
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread



getting this error since i'm new in react so i'm unable to figure out why the sound is null?
