### ISSUE TITLE
Build failure on RN0.47.0 on Android

### ISSUE THREAD

**Issue by ohtangza** [zmxv/react-native-sound#238]
<img width="629" alt="screen shot 2017-08-09 at 5 04 21 am" src="https://user-images.githubusercontent.com/1323963/29092179-63be8a32-7cc0-11e7-907c-d5ea05582160.png">

Due to breaking change of RN0.47.0, the build on Android fails.

**Comment by ohtangza** [comment]
The best solution is to be this one: https://github.com/facebook/react-native-fbsdk/commit/f0523e7f62ad82b8c1d83275c51d70a93aa594cd

**Comment by ohtangza** [comment]
I just submitted a pull request. This issue will be resolved shortly.

**Comment by hellogerard** [comment]
@zmxv @benvium You have your choice of PRs, ha!

**Comment by ohtangza** [comment]
@hellogerard I just closed pull request because your submission is a precedent to mine. Thanks for your effort! I'm very happy that this repo is well-managed because we are using it on production :)

**Comment by trepidity** [comment]
@hellogerard you are referring to #239?

**Comment by hellogerard** [comment]
@trepidity Yessir!

**Comment by ohtangza** [comment]
I am not upgrading RN because of this issue!

**Comment by ohtangza** [comment]
@trepidity The pull request #239 definitely resolves this issue. Lots of 3rd party libraries have already done the same patch all around.

**Comment by mo-solnet** [comment]
As of version `0.10.3`, this is still an issue (code is fixed but not released on npm!)
Can you please do a release of the new version which has the fix?

**Comment by trepidity** [comment]
@mo-solnet `0.10.4` released :)

**Comment by mo-solnet** [comment]
Thank you @trepidity 🥂
