### ISSUE TITLE
Sound not playing - `success` false

### ISSUE THREAD

**Issue by pudility** [zmxv/react-native-sound#242]
### Installation
I installed `react-native-sound` with:
1) `npm install react-native-sound --save`
2) `react-native link`

### Code
I have imported the module here:
```
import Sound from 'react-native-sound';
Sound.setCategory('Playback');
```
And then I call it on the press of a button:
```
                var whoosh = new Sound('https://raw.githubusercontent.com/zmxv/react-native-sound-demo/master/frog.wav', (error) => {
                  if (error) {
                    console.log('failed to load the sound', error);
                    return;
                  }
                  // loaded successfully
                  console.log('duration in seconds: ' + whoosh.getDuration() + 'number of channels: ' + whoosh.getNumberOfChannels());
                });

                // Play the sound with an onEnd callback
                whoosh.play((success) => {
                  if (success) {
                    console.log('successfully finished playing');
                  } else {
                    console.log('playback failed due to audio decoding errors');
                  }
                });
```

### Error

However when I run it I get this error:
`playback failed due to audio decoding errors`

### Versions:
`react-native-sound` - 0.10.3
`react-native` - 0.47.1

### Expected behavior
It plays the audio clip.

### Actual behavior
`success` is false therefore it gives an error.

**Comment by denisftw** [comment]
Hi @pudility !

Did you manage to find the solution?  

I have the same setup (`react-native-sound` 0.10.3 and `react-native` 0.47.1) and see the same error when trying to play an MP3 from URL. Tried it on the Android emulator and the actual device - same thing.

**Comment by denisftw** [comment]
Apparently, this is the same bug as #203 . It also says 

> numberOfChannels: -1

**Comment by DavitVosk** [comment]
the same problem here

**Comment by trepidity** [comment]
Does the fix, that was provided in #203 help any?

**Comment by DavitVosk** [comment]
yes it helped me, see my comment there..

**Comment by trepidity** [comment]
LOL, awesome. I guess I should pay better attention.
