### ISSUE TITLE
Can't run unit tests with Jest

### ISSUE THREAD

**Issue by Andruschenko** [zmxv/react-native-sound#244]
While running a most simple unit test I get `TypeError: Cannot read property 'IsAndroid' of undefined` as in issue #36 . However, building and running the app works perfectly fine.

Mocking `react-native-sound` via `jest.mock('react-native-sound');` doesn't help.

Here's my unit test code:

```
import 'react-native';
import React from 'react';
import renderer from 'react-test-renderer';

jest.mock('react-native-sound');

import myComponentWithANestedSubComponentWhichUsesRNSound from './';

describe('<ListItemVideo />', () => {

  it('renders correctly', () => {
    const tree = renderer.create(<myComponentWithANestedSubComponentWhichUsesRNSound />);
  });
});

```

**Comment by trepidity** [comment]
duplicate of #245
