### ISSUE TITLE
How do I use the react - native sound to implement a pause playback function

### ISSUE THREAD

**Issue by iOSQiao** [zmxv/react-native-sound#246]
When I quickly click on the pause play, the playback progress is reset to 0.

'use strict';
import React, { Component } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Modal, Image } from 'react-native';

import Sound from 'react-native-sound';
import RNFS from 'react-native-fs';

import * as theme from '../theme';
import Progress from '../components/Progress';

const AudioPlayIcon = require('../resource/img/file_audio_paly.png');
const AudioStopIcon = require('../resource/img/file_audio_stop.png');

const AudioStatePlay = "play";
const AudioStatePause = "pause";
const AudioStateStop = "stop";

class SoundPlayer extends Component {
    
    constructor (props) {
        super(props)
        
        this.state = {
            visible: this.props.visible,
            isPlaying: false,
            progress: 0,
        };
        this.duration = 1;
        this.audioState = "";
        this.enable = true;
    }

    componentWillUnmount() {
        this.clearTimer();
    }

    componentWillReceiveProps(nextProps) {
        if (nextProps.visible) {
            this.setState({ isPlaying: true, ...nextProps });
            this.play();
        } else {
            this.setState(nextProps);
        }
    }

    showModal(visible) {
        if (!visible) {
            this.stop();
        }
		this.setState({ visible: visible });
    }

    changePlayState() {
        if (!this.enable) return;
        if (this.state.isPlaying) {
            this.setState({ isPlaying: false });
            this.pause();
        } else {
            this.setState({ isPlaying: true });
            this.play();
        }
        this.enable = false;
        setTimeout(() => {
            this.enable = true;
        }, 500);
    }

    play() {
        if (this.whoosh && !this.state.isPlaying) {
            this.whoosh.getCurrentTime((seconds) => { 
                this.whoosh.setCurrentTime(seconds);
                this.whoosh.play((success) => {
                    if (success) {
                        this.stop();
                    }
                });
                this.audioState = AudioStatePlay;
                this.playProgress();
            });
            return;
        }
        this.whoosh = new Sound(this.props.source, null, (error) => {
            if (!error) {
                this.duration = this.whoosh.getDuration();
                this.whoosh.play((success) => {
                    if (success) {
                        this.stop();
                    }
                });
                this.audioState = AudioStatePlay;
                this.playProgress();
            }
        });
    }

    pause() {
        this.audioState = AudioStatePause;
        if (!this.whoosh) return;
        this.whoosh.pause();
        this.clearTimer();
    }

    stop() {
        this.audioState = AudioStateStop;
        if (!this.whoosh) return;
        this.whoosh.stop();
        this.whoosh.release();
        this.whoosh = null;
        this.clearTimer();
        this.setState({ isPlaying: false });
    }

    playProgress() {
        this.timer = setInterval(() => {
            this.whoosh.getCurrentTime((seconds) => {
                if (this.duration >= seconds && this.audioState === AudioStatePlay) {
                    this.setState({ progress: seconds }); 
                } else if (this.audioState === AudioStateStop) {
                    this.setState({ progress: 0 }); 
                }
            });
        }, 0);
    }

    clearTimer() {
        if (this.timer) {
            clearInterval(this.timer);
            this.timer = null;
        }
    }

    render() {
        return (
            <Modal
		        animationType={"none"}
		        transparent={true}
		        visible={this.state.visible}
		        onRequestClose={() => this.showModal(false)} >
                <View style={styles.modal}>
                    <TouchableOpacity style={{flex: 1}} onPress={() => null} />
                    <View style={styles.modalSubContainer}>
                        <Text>{this.state.progress+"/"+this.duration}</Text>
                        <View style={styles.progressContainer}>
                            <Progress style={styles.progress} value={this.state.progress / this.duration} color={theme.colors.primary} />
                        </View>
                        <TouchableOpacity style={[styles.iconContainer, styles.icon]} onPress={() => this.changePlayState()}>
                            <Image style={styles.icon} source={this.state.isPlaying?AudioStopIcon:AudioPlayIcon}/>
                        </TouchableOpacity>
                    </View>
                    <TouchableOpacity style={{flex: 1}} onPress={() => null} />
                </View>
		    </Modal>
        );
    }
    
}

class MyClass extends Component {

    constructor(props) {
	    super(props);
	
	    this.state = {
            play: false,
        };
        this.filePath = "/var/mobile/Containers/Data/Application/D7592EFB-660A-468F-B6F9-68B1F653C722/Library/Caches/recorder/316186435.mp3"
    }

    componentDidMount() {
        this.setState({ play: true });
    }

    render() {
        return (
            <View style={styles.container}>
                <TouchableOpacity onPress={() => this.setState({ play: true })}>
                <View style={styles.button}>
                    <Text>Play</Text>
                </View>
                </TouchableOpacity>
                <SoundPlayer visible={this.state.play} source={this.filePath} />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#ccffcc',
    },
    button: {
        padding: 10,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#2c3e50',
    },
    modal: {
        flex: 1,
        backgroundColor: 'transparent',
    },
    modalSubContainer: {
        marginLeft: 60,
        marginRight: 60,
        paddingTop: 10,
        paddingBottom: 10,
        backgroundColor: 'white',
        flexDirection: 'column',
        justifyContent: 'flex-end',
    },
    iconContainer: {
        alignSelf: 'center',
    },
    icon: {
        width: 45,
        height: 45,
    },
    progressContainer: {
        flex: 1,
        justifyContent: 'flex-end',
        paddingBottom: 10,
    },
    progress: {
        height:3,
        backgroundColor:'#ccc',
        borderRadius:2,
        marginLeft: 10,
        marginRight: 10,
    },
});

export default MyClass;

**Comment by gvenk** [comment]
This only happens when you 'quickly click on the pause play'? What do you mean by quickly? Quickly after start playing?

**Comment by iOSQiao** [comment]
I solved the scheduling problem, use to react-native-video.
