### ISSUE TITLE
Why set onError to basePath?

### ISSUE THREAD

**Issue by gvenk** [zmxv/react-native-sound#249]
In sound.js on line 17 the onError callback is set to basePath? What's the purpose of this? 

https://github.com/zmxv/react-native-sound/blob/cc72835a8a1e3150379a643bc9aea60b8f6fbc27/sound.js#L17

**Comment by trepidity** [comment]
@zmxv can you answer this?

**Comment by gvenk** [comment]
It was a commit made by @lostintangent 
https://github.com/zmxv/react-native-sound/commit/231a3b6270ef9bafebbe0417ef57552f45259a66#diff-efdec638a15cc8a34818959e66e01127R16

**Comment by gvenk** [comment]
I just looked at the code for the demo app and [found something interesting](https://github.com/zmxv/react-native-sound-demo/blob/master/main.js#L142): 

`// If the audio is a 'require' then the second parameter must be the callback.`

That's probably the reason why onError = basePath. Wouldn't it be better to set basePath to something like null if you would like to use require? But if we change it now, it breaks the API, so that's probably not a good idea. 

It would be a good idea to add some info in a comment above this line.

**Comment by trepidity** [comment]
You mean in the documentation?
Would this maybe be a 2.0 thing

**Comment by gvenk** [comment]
No, in de source code. Above line 17 (sound.js) add some clarification about why the onError gets set to the basePath. I'll create a PR somewhere this week. 

Changing the API would be a 2.0 thing indeed.

**Comment by gvenk** [comment]
After going through the list of issues, it looks like not everybody knows in some cases the callback must be the second parameter instead of the third. A lot of people ran into this and a lot will probably run into this in the future.

What would be best? Add a note about this in the documentation or change the constructor, so the callback will always be the third parameter? 
The latter will be the most developer friendly I think, but could be breaking existing implementations. So maybe add a note about this in the documentation and do things different in a future 2.0 version?
