### ISSUE TITLE
Development branch

### ISSUE THREAD

**Issue by trepidity** [zmxv/react-native-sound#251]
Does anyone oppose me making a development branch to merge PR's into before merging into master "stable"?

@benvium @zmxv

**Comment by gvenk** [comment]
Sounds like a good idea to me 👍

**Comment by trepidity** [comment]
I'm on the fence on this. Having a development branch is more work to maintain, but I feel better about it until 1. there are tests 2. I get to know the project better.

For now, I created `unstable`. If it doesn't work or we need something better, we can adjust and move forward :)

**Comment by trepidity** [comment]
And that didn't work. Waiting on Zhen to make some changes.
