### ISSUE TITLE
Crash on iOS  on load "dyld: Symbol not found: ___NSArray0__"

### ISSUE THREAD

**Issue by yaronlevi** [zmxv/react-native-sound#259]
When creating a clean project (react-native init):

run NPM install react-native-sound
run react-native link react-native-sound
then run the Xcode project on an iPhone device, 
the app crash the moment is loads with:

**"dyld: Symbol not found: ___NSArray0__"**

While investigating I found that in Xcode's Link Binary With Libraries, if I remove the line of "libRNSound.a" then the crash disappears.

This happens with RN@0.45 up to the latest RN@0.47.2
The version of react-native-sound is 0.10.4

(On Android everything runs fine)

**Comment by gvenk** [comment]
Which version of XCode do you have and which version of iOS on your device?

**Comment by yaronlevi** [comment]
xcode version: Version 8.3.3 (8E3004b)

iphone4 4s: 8.1.3(12B466)

**Comment by gvenk** [comment]
Is this the only error message you get? Could you paste the complete error message?

**Comment by agumack** [comment]
Hi, I also same problem.

> dyld: Symbol not found: ___NSArray0__
  Referenced from: /private/var/mobile/Containers/Bundle/Application/8B40C8BE-5816-495B-98BF-2E43A2B4009B/soundATM.app/soundATM
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /private/var/mobile/Containers/Bundle/Application/8B40C8BE-5816-495B-98BF-2E43A2B4009B/soundATM.app/soundATM
(lldb)

**Comment by gvenk** [comment]
Could you try to add CoreFoundation.framework with the 'optional' flag to the Linked Frameworks and libraries?

**Comment by gvenk** [comment]
@agumack You're also on iOS 8.x?

**Comment by yaronlevi** [comment]
@gvenk getting the same error as @agumack

**Comment by gvenk** [comment]
@yaronlevi Did you try it with adding the CoreFoundation.framework to the Linked Frameworks in XCode? (with flag optional)

**Comment by yaronlevi** [comment]
Will try later and come back with results

**Comment by junjunconan** [comment]
@gvenk @yaronlevi Getting the same error on iOS 8. After tried adding the ```CoreFoundation.framework``` in XCode, it seems to work fine. Many thanks!

**Comment by gvenk** [comment]
@junjunconan that's good to hear! 
If @yaronlevi can confirm this also, this issue can be closed.

**Comment by yaronlevi** [comment]
![screen shot 2017-09-04 at 22 10 26](https://user-images.githubusercontent.com/5398977/30244522-faf6dac4-95c7-11e7-935a-381f97cbd9f9.png)

Yes! adding the lib as in the above image solves the issue. (Mind the optional flag).

**Comment by gvenk** [comment]
That's good to hear, thanks. 

Maybe we have to add this to the documentation: iOS8 needs the CoreFoundation.framework (optional flag enabled).

**Comment by trepidity** [comment]
Documented at https://github.com/zmxv/react-native-sound/wiki/Known-Issues-and-Problems

**Comment by eladnava** [comment]
Seems that iOS 8 requires the `UIKit.framework` to be linked in addition to `CoreFoundation.framework`. 👍
