### ISSUE TITLE
Not loading and no error on Android

### ISSUE THREAD

**Issue by RailtonMatthew** [zmxv/react-native-sound#260]
Hi, I have installed react-native-sound, placed an mp3 into the specified folder but the initialisation does not complete.  Code snippet below, "Did mount" shows in the console but nothing else:

```
var Sound = require('react-native-sound');

componentDidMount() {
  console.log("Did mount");
  var whoosh = new Sound('sound1.mp3', Sound.MAIN_BUNDLE, (error) => {
  if (error) {
    console.log('failed to load the sound', error);
    return;
  }
  console.log('success ');
});
```

Version info below:
react-native-cli: 1.0.0
react-native: 0.43.3

Thanks for any pointers.

**Comment by gvenk** [comment]
Where did you put the mp3 file? In the same directory as the code above?

**Comment by RailtonMatthew** [comment]
Thanks for the reply.  The mp3 is in  android/app/src/main/res/raw.

My version of RN was a bit out of date so decided to update it.  After the update and creating a test app it worked without issue.  

Now to rebuild my app and see if it still works! :)

**Comment by gvenk** [comment]
Ok, let us know if there are any problems you run into. For now this can be closed I think?

**Comment by RailtonMatthew** [comment]
App rebuild, and re-coded due to deprecated and changed modules!!

Sounds are playing fine so please close the ticket.

Thanks for your help. :)
