### ISSUE TITLE
How to disable Sound Overlapping?

### ISSUE THREAD

**Issue by themakerman** [zmxv/react-native-sound#262]
Hi guys, 
I am working on a music player and struggling with the problem of overlapping sound. The thing is when user is listening to song and wants to change to other song ---> presses back ----> selects new song from listView ----> new Sound is played (but is overlapped with older one).

I am unable to find correct way to release previous sound resource. Would be grateful if someone can help me out.

**Comment by trepidity** [comment]
@themakerman can you provide a snip of the code that you are using to start and stop the track?
 You should be able to call `pause()` or `stop()`, if you need, you can finally call `release()`

Could the issue be that you are not making the call in a callback?

```
// Stop the sound and rewind to the beginning
whoosh.stop(() => {
  // Note: If you want to play a sound after stopping and rewinding it,
  // it is important to call play() in a callback.
  whoosh.play();
});
```

**Comment by VanessaChu** [comment]
Sorry, same issue. Did you ever figure this out?
