### ISSUE TITLE
'<React/RCTDefines.h> file not found' error

### ISSUE THREAD

**Issue by leenasn** [zmxv/react-native-sound#264]
I saw the [PR](https://github.com/zmxv/react-native-sound/pull/135#issuecomment-327407842) related to this, but am still getting this error.

My app is a [detached expo app](https://docs.expo.io/versions/latest/guides/detach.html)

I've setup a sample app to reproduce the same issue:

[https://github.com/leenasn/react-native-sound-demo-app](https://github.com/leenasn/react-native-sound-demo-app)

The above app works with Android, but doesn't compile in iOS with the above-mentioned error '<React/RCTDefines.h> file not found'.

Any help is appreciated.

Thanks,
Leena

**Comment by stefvw93** [comment]
I have the same issue, also with a detached expo app.

**Comment by leenasn** [comment]
@stefvw93 I was able to resolve it by removing the library dependency from the project. This is what I did:

- Removed RNSound.xcodeproj from the libraries
- Add the below line to the Podfile

```
pod 'RNSound',
    :path => "../node_modules/react-native-sound"
```
- Run `pod install`

I've updated the sample project too with the above.

https://github.com/leenasn/react-native-sound-demo-app

I am not sure why is this the case. I assume the linking is done for non-CocoaPods apps as react-native normally is not built using CocoaPods.

**Comment by gvenk** [comment]
So the problem has been solved? 

I'm not a CocoaPod user, you have to use one of the methods to install a native library, so use `react-native link` or use the CocoaPods-way. And with CocoaPod, I think you need to include it in the project's pod file.

**Comment by gvenk** [comment]
Any news about this isssue?

**Comment by leenasn** [comment]
It works fine for me
