### ISSUE TITLE
iOS 8: stop sound crashes app with EXC_BAD_ACCESS (code=1)

### ISSUE THREAD

**Issue by RalfNieuwenhuizen** [zmxv/react-native-sound#266]
Upon calling `Sound.stop` on iOS 8, the app crashes on the callback line.
```
RCT_EXPORT_METHOD(stop:(nonnull NSNumber*)key withCallback:(RCTResponseSenderBlock)callback) {
  AVAudioPlayer* player = [self playerForKey:key];
  if (player) {
    [player stop];
    player.currentTime = 0;
    callback(@[]);                               <- EXC_BAD_ACCESS (code=1)
  }
}
```

Any ideas why?

**Comment by gvenk** [comment]
Hmm...that's a difficult one to debug. Can we see a bit more of your code?

**Comment by agumack** [comment]
Hey, I have same problem 
Xcode crash when run app. 

<img width="999" alt="screen shot 2017-09-13 at 10 44 55 pm" src="https://user-images.githubusercontent.com/19372005/30386971-60a811b6-98d5-11e7-9dac-4c8868b2ecda.png">

**Comment by gvenk** [comment]
@agumack does `react-native log-ios` give any more information?

**Comment by newbdez33** [comment]
<img width="1213" alt="rnsound_m" src="https://user-images.githubusercontent.com/114880/30408790-06866f54-993c-11e7-8f72-58554fca297c.png">

This is what i got

**Comment by RalfNieuwenhuizen** [comment]
@newbdez33 that's exactly what I got!
Could it be that the callback is handled differently/not propagated at all on iOS 8? This  happens every time you simply call `stop()`

**Comment by gvenk** [comment]
Sounds different than #259, but did you try to include the corefoundation framework?
 https://github.com/zmxv/react-native-sound/wiki/Known-Issues-and-Problems#ios8-needs-the-corefoundationframework

**Comment by RalfNieuwenhuizen** [comment]
Unfortunately this is not the fix. Already had this included as optional framework. (Probably to fix the same problem as #259)
Thanks for the suggestion though!

**Comment by yibyli** [comment]
hey guys,I found it that edit the deployment version of the RNSound.xcodeproj to iOS 8 can resolve this problem,[remove objective c literals ](https://github.com/zmxv/react-native-sound/pull/416)works too.

**Comment by mklb** [comment]
@yibyli what exactly do you mean? 

I have the same error for a while now (half a year) in my production app running on various iOS versions.. This error comes sometimes up if the app plays multiple sounds (at the same time or right after another)..
I updated the react-native-sound package to the newest version (..again..) but it still persists. I have no idea what to do actually 🤷‍♂

**Comment by paulmelnikow** [comment]
@mklb That sounds like a different occurrence of EXC_BAD_ACCESS than the one being described here. Could you open a new issue with a stack trace?

**Comment by paulmelnikow** [comment]
Hi!

Going forward I'm not sure how far back in iOS versions we should support, and for how long. It could create a lot of extra maintenance work. Are there a lot of users using this library still targeting iOS 8?

Also, it would be helpful to have a way to test that none of these literals are in the code in CI, to prevent this from regressing.
