### ISSUE TITLE
Sound.MAIN_BUNDLE: undefined - can't find file

### ISSUE THREAD

**Issue by PeterKow** [zmxv/react-native-sound#27]
I am using Android 5.01 React-native 0.19

after creating object to access my file 
```javascript
const notifySound = new Sound('notify.aac', Sound.MAIN_BUNDLE, (error) => {
```

I got error `{ message: 'resource not found', code: -1 }` I followed all steps in the documentation, but then console.log - `Sound.MAIN_BUNDLE` and it's `undefined`

```javascript 
{ [Function: Sound]
I/ReactNativeJS( 9413):   enable: [Function],
I/ReactNativeJS( 9413):   MAIN_BUNDLE: undefined,
I/ReactNativeJS( 9413):   DOCUMENT: undefined,
I/ReactNativeJS( 9413):   LIBRARY: undefined,
I/ReactNativeJS( 9413):   CACHES: undefined }
```

which comes from `sound.js` file and this code

```javascript
Sound.MAIN_BUNDLE = RNSound.MainBundlePath;
Sound.DOCUMENT = RNSound.NSDocumentDirectory;
Sound.LIBRARY = RNSound.NSLibraryDirectory;
Sound.CACHES = RNSound.NSCachesDirectory;
```

**Solution** 
In the end, I put my files into `android/app/src/main/res/raw`, but it would be nice to put this file directly in my service folder

Thanks!

**Comment by zmxv** [comment]
What folder did you previously put notify.aac into?

**Comment by PeterKow** [comment]
On the root as in example
https://github.com/zmxv/react-native-sound-demo/blob/master/advertising.mp3

and I also tried next to .js file

**Comment by zmxv** [comment]
The file under the base directory is for the iOS demo app; there's a copy under android/app/src/main/res/raw for the Android counterpart. This is working as intended.

**Comment by KevinHu2014** [comment]
I am using Android 5.01 React-native 0.24
I have follow the steps in the documentation and I also put my files into `android/app/src/main/res/raw`, 
but still got  ` {message: "resource not found", code: -1}`

**Comment by zmxv** [comment]
@KevinHu2014 Did you try out the sample project at https://github.com/zmxv/react-native-sound-demo ?

**Comment by KevinHu2014** [comment]
@zmxv Thanks , after restarting the React Packager It woks.

**Comment by fritx** [comment]
```js
// sound.js
function Sound(filename, basePath, onError) {
  // ...
  if (IsAndroid && !basePath) {
    this._filename = filename.toLowerCase().replace(/\.[^.]+$/, '');  // why removing trailing `.xx`?
  }
```

```js
new Sound('/data/xxx/xx.mp3', ...)  // does not work
new Sound('/data/xxx/xx.mp3' + '.aaaaa', ...)  // works
```

**Comment by zmxv** [comment]
@fritx As documented in README.md, the basePath parameter (`Sound.MAIN_BUNDLE`) should be omitted when you're passing in an absolute path.

**Comment by fritx** [comment]
@zmxv hey, but as

```js
// sound.js
if (IsAndroid && !basePath) {
    this._filename = filename.toLowerCase().replace(/\.[^.]+$/, '');
}
```

I guess, even I pass `''` or any other falsy value, the `.mp3` ext would be removed, right?

**Comment by zmxv** [comment]
@fritx You're right. I should probably check if `filename` is an absolute path in the `if` condition.

**Comment by kenchengch** [comment]
I've same problem. How to fix it? I got error even i put the mp3 into android/app/src/main/res/raw.
code like this.
var s = new Sound('advertising.mp3', 'Sound.MAIN_BUNDLE', (e) => {

**Comment by fritx** [comment]
@kenchengch 

```js
// wrong
var s = new Sound('advertising.mp3', 'Sound.MAIN_BUNDLE', (e) => {
// maybe this?
var s = new Sound('advertising.mp3', Sound.MAIN_BUNDLE, (e) => {
```

**Comment by challenger532** [comment]
How did you solve this issue ? I'm having the same problem, I tried everything  Sound('track.mp3', '/', (error)

**Comment by sexykodo** [comment]
For Android I got the same error if I try to reproduce a downloaded file.
I got the example working ( putting the audio in /res/raw -> relative path)
Everything works fine on IOS (simulator and physical device) if i put reproduce files from Sound.DOCUMENT

For Android i tried DocumentDir/MainBundleDir/DownloadDir but none of these seem to work. 
Library can't seem to load the file from these sources.
Any idea?

**Comment by bobbyrinaldy** [comment]
> For Android I got the same error if I try to reproduce a downloaded file.
> I got the example working ( putting the audio in /res/raw -> relative path)
> Everything works fine on IOS (simulator and physical device) if i put reproduce files from Sound.DOCUMENT
> 
> For Android i tried DocumentDir/MainBundleDir/DownloadDir but none of these seem to work.
> Library can't seem to load the file from these sources.
> Any idea?

any update ?

**Comment by aliraza96** [comment]
Any Update ?

**Comment by devartwa** [comment]
hi guys, any update?

**Comment by ShahnawazHussain28** [comment]
Any update?
