### ISSUE TITLE
 how to get the time update event while play a mp3

### ISSUE THREAD

**Issue by sxwailyc** [zmxv/react-native-sound#277]
hi,  i want to use react-native-sound for my project ,  and i want to do something while the time update, can you help me, tks

**Comment by trepidity** [comment]
Can you look at this past thread?
https://github.com/zmxv/react-native-sound/issues/235

I think it has the answer you want.

**Comment by sxwailyc** [comment]
> Can you look at this past thread?
> #235
> 
> I think it has the answer you want.

yes, tks
