### ISSUE TITLE
playback failed due to audio decoding errors

### ISSUE THREAD

**Issue by jYh1014** [zmxv/react-native-sound#285]
Every time  playing audio ，
![image](https://user-images.githubusercontent.com/26647220/31381730-01b2350a-ad7b-11e7-876b-efa7e1c62b80.png)
success is always false

**Comment by jYh1014** [comment]
have already been solved

**Comment by wordyallen** [comment]
@jYh1014  how?

**Comment by quangduz** [comment]
move it to inside "new Sound"

**Comment by RameshSain** [comment]
playback failed due to audio decoding errors

**Comment by manoj2166** [comment]
I am having issue

**Comment by canaan5** [comment]
Move the pay action into the success part of loading the sound file like so

var sound = new Sound(require('./sound.mp3'), (error) => {
            if (error) {
                console.log('failed to load the sound', error);
                return;
            }
            // loaded successfully
            sound.play((success) => {
                if (success) {
                    console.log('successfully finished playing');
                } else {
                    console.log('playback failed due to audio decoding errors');
                    sound.release();
                }
            });
        });

**Comment by jinglongbu** [comment]
@jYh1014 how?
