### ISSUE TITLE
Android: How to set system's Media volume?

### ISSUE THREAD

**Issue by enzeberg** [zmxv/react-native-sound#288]
I'm writing an alarm app, so In fact I want to use the Alarm volume(Xiaomi Phone). But I don't know how to use Alarm volume. It seems that `react-native-sound` does not provide the API(https://github.com/zmxv/react-native-sound/issues/287).
And I noticed that it supports setting volume on iOS, Android and Windows and setting system volume on Android.
I tried `setVolume`, but it seems like it can only reduce the volume. So I tried `setSystemVolume`, the "API" I guessed, but it would cause errors.

**Comment by afilp** [comment]
@enzeberg I have an Android phone and 'setVolume' does nothing. I am using the 'npm' version ``0.10.4.`` (not master).

See my issue here: https://github.com/zmxv/react-native-sound/issues/333

How does this work for you? (I mean lowering the volume)

**Comment by enzeberg** [comment]
@afilp I've seen your issue and found your code is almost the same as mine. But my code does work. Which version of `react-native-sound` are you using? I'm using `^0.10.2`.

**Comment by afilp** [comment]
@enzeberg 

Using the latest one:
``"react-native-sound": "^0.10.4",``

Did you try upgrading and see if you have problems with this? Thanks.

**Comment by enzeberg** [comment]
@afilp 
I used the latest version `^0.10.4` at the beginning, but it couldn't even play sound (I don't know why). Maybe I saw some examples (e.g. https://github.com/zmxv/react-native-sound-demo), so I downgraded it. Then it worked well.

**Comment by afilp** [comment]
@enzeberg It had no difference between 0.10.2 and 0.10.4.

After lots of testing, I realized this:

It works only if the range is between 0 and 0.1! The volume is at maximum level on `0.1`, not on `1`.  So, `half volume` now means `0.05`. Whatever value we put above `0.1` is at maximum level.

Can you also do the same experiment? Is this normal?! (very strange)

**Comment by enzeberg** [comment]
@afilp 
I did the experiment, but got the different results. When I write `sound.setVolume(0.2)`, the sound really gets smaller (I'm sure it is smaller). When the code is `sound.setVolume(0.02)`, the sound gets much smaller (it is so small that I can hardly hear it).
The sound is from a `.mp3` file.
