### ISSUE TITLE
method isPlaying() ?

### ISSUE THREAD

**Issue by joeylu** [zmxv/react-native-sound#291]
can we have a function to check whether or not the current player is playing (return with the song info or just a boolean)? or is there an alternative way? tks

**Comment by lodev09** [comment]
I believe you need to use `Promise` together with `getCurrentTime`. [docs here](https://github.com/zmxv/react-native-sound/wiki/API#getcurrenttimecallback)

Something like:
```javascript
isPlaying() {
	return new Promise((resolve, reject) => {
		whoosh.getCurrentTime((seconds, isPlaying) => {
			resolve(isPlaying);
		});
	})
}
```
then you call it like so:
```javascript
var isPlaying = await this.isPlaying();
```

If you don't want to use promises, you can directly pass your logic to `getCurrentTime`'s `callback`

** code is not tested but you should get the idea :)

**Comment by ohtangza** [comment]
This is implemented: https://github.com/zmxv/react-native-sound/pull/366

@zmxw I think this issue can be closed.
