### ISSUE TITLE
Sound not working on real ios 11

### ISSUE THREAD

**Issue by GH974** [zmxv/react-native-sound#297]
-------- INFO ------ 
- React-native 0.49.3
- Xcode 9
- ios 11
-react-native-sound 0.10.4
--------------

Hi, I tested the sound in Android and the ios simulator is ok. and try on the real ios 11 device, the sound doesn't work and does not return an error

**Comment by Winglonelion** [comment]
@GH974 Version 0.10.3 of it still working on My Iphone 6Plus Ios 11.0.3. I think your issue start from another side.

**Comment by GH974** [comment]
On IOS 11 simulator sound is ok and on my real device ios 11 this sound not worked and not error returned

**Comment by Winglonelion** [comment]
@GH974 I test on real device

**Comment by GH974** [comment]
Can you send 1 short exemple ?

**Comment by GH974** [comment]
`
import React, { Component } from 'react';
import { AsyncStorage } from "react-native";
import ReactNativeSound from 'react-native-sound';
import Storage from 'react-native-storage';

export default class Sound extends Component{
    constructor(props){
		super(props);
		var self                = this;
        this.successSound       = null;
        this.buttonSound        = null;
        this.failureSound       = null;
        this.returnButton       = null;
        this.returnGrid         = null;
        this.isSound            = true;

        var storage = new Storage({
        	size: 1000,
        	storageBackend: AsyncStorage,
        	defaultExpires: null,
        	enableCache: true,
        	sync : {
        		// we'll talk about the details later.
        	}
        });

        storage.load({
            key: "config"
        }).then(ret =>{
            self.isSound = ret.sound;
            self.config();
        }).catch(() => {
            self.config();
        });
    }

    config(){
        this.successSound  = this.initializeSound('success.wav');
        this.buttonSound   = this.initializeSound('button_tap.wav');
        this.failureSound  = this.initializeSound('failure.wav');
        this.returnButton  = this.initializeSound('button_return.wav');
        this.returnGrid    = this.initializeSound('button_return_grid.wav');
    }

    play(sound){
        switch (sound) {
            case 'successSound':    this.playSound(this.successSound);
                break;
            case 'buttonSound':     this.playSound(this.buttonSound);
                break;
            case 'failureSound':    this.playSound(this.failureSound);
                break;
            case 'returnButton':    this.playSound(this.returnButton);
                break;
            case 'returnGrid':      this.playSound(this.returnGrid);
                break;
        }
    }

    playSound(sound){
        //if(this.isSound==true){
            sound.getCurrentTime(currentTime => {
                if (currentTime === 0) {
                    sound.play( (err) => {
                        console.log(err);
                    } );
                } else {
                    sound.stop(() => {
                        sound.play();
                    });
                }
            });
        //}
    };

    initializeSound(name) {
        return new ReactNativeSound(name, ReactNativeSound.MAIN_BUNDLE, err => {
            if (err) {
                console.warn('failed to load the sound', err);
            }
        });
    };

}
`


and call this 

`
constructor()
{
 this.soundClass = new Sound();
}

play(){
   this.soundClass.play("returnButton");

}`

**Comment by Winglonelion** [comment]
@GH974 Oh, i see. I implement ```react-native-sound``` just simple as a set of function. 

```
import Sound from 'react-native-sound';

const flipCard = 'sound/slide_click.caf';


const playSoundFromRequire = (src) => {
  const s = new Sound(src, Sound.MAIN_BUNDLE, async (e) => {
    if (e) {
      return;
    }
    s.play();
  });
};

const playFlipCard = () => {
  playSoundFromRequire(flipCard);
};

```
I think your problem is: you implement RNS by the way of a React Native component. And then, it can be update or reload whenever the parent components update.  It can make some resource conflict when you call a not-yet-release Sound Instant many times. 

You should separate logic from View. RN is just a view library.

**Comment by GH974** [comment]
Ok thanks, this code is copied in the exemple found on another gist.
I try this and back later

**Comment by poorvasingh04** [comment]
I recently faced this issue and none of the responses available online worked for me. At the end, I found mp3 sounds that I used were not being detected by mac/Xcode. So, when you see file details in Xcode or Finder, it was not able to identify enough information like duration. After spending hours looking for the solution. I found this issue.

What I did wrong - Renamed *.wav or *.avi files to .mp3 manually

Solution - 
1. Use iTunes to convert files to specific format. Manually converting file formats corrupts the file and though they work on android, iOS fails to detect them after archiving the build.
2. For iOS, Add your sounds to Resources in Xcode project

**Comment by HarshaKoshila** [comment]
const notificationSound = new Sound('ring_tone.wav', Sound.MAIN_BUNDLE, (error) => {
        if (error) {
            console.log('failed to load the sound', error);
            return;
        }
    });
    
    Please use following way in ios
    **notificationSound.play(() => {});**.
