### ISSUE TITLE
Sound stops when application in background mode (IOS 11)

### ISSUE THREAD

**Issue by ACOSW** [zmxv/react-native-sound#299]
**Info:** 
react-native 0.49.3
react-native-sound 0.10.4
xcode 9.0.1
Added capabilities to info.plist
`
<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
`

**Affected platforms**
Appears only on IOS 11 (IOS 10 and below works as expected)

**Code example**
`
Sound.setCategory('Playback', true);
sound = new Sound(url, undefined, error => {
    if (error) {
      console.log('error loading sound', error);
      return;
    }
    sound.play(() => {
    });
  });
`
**Steps to reproduce**
Play sound and press home button

**Result**
Sound stops until application is not active

**Expected result**
Sound plays until end of the track even if app is not active or screen is locked

**Comment by ACOSW** [comment]
Sorry, issue has gone after full reinstall of node_modules and application.

**Comment by aditya-sodhani** [comment]
So you just updated the info.plist and it started working?

**Comment by Koxx3** [comment]
I had the same issue (no sound in background).
I added the audio background permission... and it was not working.
I had to remove and reinstall the app.
Just to help people having such issue too :)
