### ISSUE TITLE
Loop not working for the first play

### ISSUE THREAD

**Issue by Kerumen** [zmxv/react-native-sound#31]
I have a weird issue, the same as described [here](http://stackoverflow.com/questions/20208355/avaudioplayer-number-of-loops-only-taking-effect-after-being-played-through-once).

The loop parameter is not taken in consideration until the first play, even though the `numberOfLoops` property is correct (I logged it just before the play).

The temporary workaround I found JS side (without touching the library) is:

``` javascript
const sound = new Sound('alert.m4a', Sound.MAIN_BUNDLE, () => {
  sound.setNumberOfLoops(-1);
  sound.play(() => {
    sound.play();
  });
});
```

The second play take into account the `numberOfLoops` property. On the SO post, the OP found a native workaround by replacing the player. Maybe it's worth looking into this.

**Comment by zmxv** [comment]
Replacing the player sounds more hacky than your JS workaround.

**Comment by tuxtux00** [comment]
Hi there,

I have got the same issue.

Did you find a way to fix this issue ? 

Cheers

**Comment by benvium** [comment]
I added a test to react-native-sound demo, and it worked as intended on iOS and Android https://github.com/zmxv/react-native-sound-demo/pull/5.
