### ISSUE TITLE
Why iOS can not play url start with Http, but start with Https can

### ISSUE THREAD

**Issue by ipulian** [zmxv/react-native-sound#315]

**Comment by RickDT** [comment]
Do you have App Transport Security setup correctly for the URL in question?
https://developer.apple.com/news/?id=12212016b

**Comment by ipulian** [comment]
@RickDT yes,I have already setup , I can request api of http ,but I still can't play sound of http.
<img width="559" alt="qq 20171123161551" src="https://user-images.githubusercontent.com/26737939/33163555-09a89bca-d06a-11e7-976a-aee7db0160d8.png">

When I do that , It prompt error ,like this
<img width="182" alt="122a2e84-fb22-3fc9-3366-84896210c923" src="https://user-images.githubusercontent.com/26737939/33163898-81e4600a-d06b-11e7-9c6f-a6bd50d97d17.png">

**Comment by RickDT** [comment]
Does the HTTPS version play in Safari if you just paste the URL?

According to this, the file is not valid, so I’m wondering if your web server is not serving HTTPS properly:

https://www.osstatus.com/search/results?platform=all&framework=all&search=1954115647

**Comment by ipulian** [comment]
@RickDT  Rick, Sorry for the late response. Let me clarify, I want to use this to play mp3 files with http address (not https), i won't work even i set App Transport Security (see above), i can play those files with same address in Safari BTW.  I tried to download those files first and play those mp3 locally, it can play. I tried another mp3 file with https url, and it can play.
So, is there any other possible issue to stop streaming mp3 file with http address with this module?

**Comment by RickDT** [comment]
My best guess is that the web server isn't fully compliant with whatever iOS needs. Things like Range headers come to mind. If you're serving this from your own custom server, that's probably the culprit. 

To narrow that down, you could try hosting it on something like S3 and see if that works (it does for us).
