### ISSUE TITLE
Failed to play file on Android

### ISSUE THREAD

**Issue by devbriguy** [zmxv/react-native-sound#32]
I'm using react-native-networking module to download a file from a server which saves it to contents://downloads/my_downloads/{id} but sound fails to load the file given the path and file name (id). I am not too familiar with the file system on Android, could there be a permissions issue?

**Comment by zmxv** [comment]
Are you able to read the file using the react-native-fs module?

**Comment by devbriguy** [comment]
@zmxv I just tried to and it says File does not exist. I'm going to try and use the react-native-fs module to download the file instead of react-native-networking module.

**Comment by devbriguy** [comment]
Update: I went ahead and modified react-native-networking android implementation and was able to get an absolute path and send that back in a callback which then fixed the playback.
