### ISSUE TITLE
Can not play sound normally

### ISSUE THREAD

**Issue by poc7667** [zmxv/react-native-sound#324]
# Exception message

code: "ENSOSSTATUSERRORDOMAIN2003334207", message: "The operation couldn’t be completed. (OSStatus error 2003334207.)"

#PLIST 

	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>

# Code

        sound = new Sound('http://www.noiseaddicts.com/samples_1w72b820/4923.mp3', Sound.MAIN_BUNDLE, (error) => {
            if (error) {
                console.warn('failed to load sound, ', error);
            } else {
                // sound.play();
                this.setState({
                    isPlaying: true,
                });
            }
        });

**Comment by Andrfas** [comment]
I think you should replace `Sound.MAIN_BUNDLE` with `''`

**Comment by trepidity** [comment]
#334

**Comment by krunalp1993** [comment]
@Andrfas Solution worked fine, Thanks!

**Comment by adancarrasco** [comment]
For iOS what worked for me is the following:
1. Checked that my resource file was being played in xCode
  - Open xCode
  - Select the file
  - Click play in the xCode player
2. Once it was playing sound (had issues with some files, possibly encoding), 
  - Add the file as resource (Make sure is in Build Phases)
3. Compile the project in xCode and run it from there
  - Note: Every time you change the resources or expect new resources you need to compile your Native application either by doing it from xCode or `npm run ios`

This is my code:
```JS
const sound = new Sound(
    "myFile.mp3",
    Sound.MAIN_BUNDLE,
    error => {
      if (error) {
        console.log("failed to load the sound", error);
        return;
      }
      sound.play(() => sound.release());
    }
  );
// The play dispatcher
sound.play();
```
