### ISSUE TITLE
Are there any plans to implement playing audio from a url?

### ISSUE THREAD

**Issue by Leekao** [zmxv/react-native-sound#33]

**Comment by zmxv** [comment]
Streaming? No plans yet, but PRs are welcome.

**Comment by Leekao** [comment]
I actually meant just playing mp3  files that aren't bundled with the apk. urls.

**Comment by zmxv** [comment]
It's already supported. See https://github.com/zmxv/react-native-sound/pull/24
On iOS, you can download mp3 files using react-native-fs before playing them.

**Comment by Leekao** [comment]
wow great! 
@zmxv maybe it would be a good idea to update the readme because it's really not clear that option exists, should I just do  `new Sound(url,"",onErrorHandler) `?

**Comment by smithaitufe** [comment]
Please I am currently struggling with this. 

It is not working for me

I have this situtation. The user will click a button and then I use react-native-document-picker to allow them select the mp3 file. When I try playing it, it does not work for me.

I have created an issue in the demo [here](https://github.com/zmxv/react-native-sound-demo/issues/16#issue-324619559)

How did you manage to resolve this?

Thanks for your anticipated feedback

**Comment by harshakollipara** [comment]
> Please I am currently struggling with this.
> 
> It is not working for me
> 
> I have this situtation. The user will click a button and then I use react-native-document-picker to allow them select the mp3 file. When I try playing it, it does not work for me.
> 
> I have created an issue in the demo [here](https://github.com/zmxv/react-native-sound-demo/issues/16#issue-324619559)
> 
> How did you manage to resolve this?
> 
> Thanks for your anticipated feedback

Hi,
By any chance have you got any solution for your issue ? Actually I was trying the same uploading audio from my phone and select , but not able to play the audio file.I am using react-native-sound-player.
thanks in advance.
