### ISSUE TITLE
IOS can not paly audio!!!

### ISSUE THREAD

**Issue by nfq6612** [zmxv/react-native-sound#331]
IOS can not paly audio!  see picturn
![qq 20171218160711](https://user-images.githubusercontent.com/21963633/34095740-8ea49d86-e40d-11e7-9aae-d173b4bcaf8c.jpg)

**Comment by schumannd** [comment]
can you provide more info? What kind of file are you trying to play?

**Comment by paulmelnikow** [comment]
Ref #482

**Comment by afilp** [comment]
I have the same problem in iOS, any solution to this please?
