### ISSUE TITLE
'setVolume' has no effect - Android

### ISSUE THREAD

**Issue by afilp** [zmxv/react-native-sound#333]
We are using the following code to load the sound (successfully). Then we set the volume to a lower level (0.4 or even 0.1). But this has absolutely no effect. The sound is still the one provided by the phone, which is too loud by default.

Is this a bug of the library?

````
     const sound_correct = new Sound('sound_correct.mp3', Sound.MAIN_BUNDLE, (error) => {
        if (error) {
            console.log('failed to load the sound', error);
            return;
        }
        // loaded successfully
        sound_correct.setVolume(0.4);
        console.log('duration in seconds: ' + sound_correct.getDuration() + 'number of channels: ' + sound_correct.getNumberOfChannels());
    });
````

**Comment by afilp** [comment]
Now I see that it works only if the range is between 0 and 0.1. The volume is at maximum level on `0.1`, not on `1`.  So, steps I needed like `0.01`.

**Comment by ma-pe** [comment]
I am not experiencing your issue on AVD Emulator. I can set the volume to 1 which is the maximum. Will try this on a real device now.

**Comment by ma-pe** [comment]
Also my device (One Plus One) works just fine when setting volume to 1. 

On which device / emulator are you experiencing this?

**Comment by afilp** [comment]
Xiaomi Redmi Note 4

**Comment by roysG** [comment]
not working also for me, any update?

**Comment by Ilario17** [comment]
in my tests, it doesn't work with 1 or 0.1

version 0.11.0
tested on iPhone XR iOS 12.2

**Comment by paulmelnikow** [comment]
@Ilario17 Could you open a new issue, please, and post your code?

**Comment by paulmelnikow** [comment]
Anyone else still experiencing this issue, could you please open a new issue, post your code, and say which version of the library you are using?

**Comment by rahulmishra1991** [comment]
Play not working for redmi devices if anyone have solution then please help me out.
