### ISSUE TITLE
E/FFmpegExtractor( 1971): android-source:0x410646e0: avformat_open_input failed, err:Invalid data found when processing input

### ISSUE THREAD

**Issue by kenchengch** [zmxv/react-native-sound#34]
I think this caused by my old device while playing mp3. Finally it is work with wav file. My device is N7100 CyanogenMod 12.1 ...

Below is error Log.
E/ExtMediaPlayer-JNI(28234): QCMediaPlayer could not be located....
E/MediaPlayer-JNI(28234): QCMediaPlayer mediaplayer NOT present
E/FFmpegExtractor( 1971): android-source:0x410646e0: avformat_open_input failed, err:Invalid data found when processing input
E/FFmpegExtractor( 1971): android-source:0x410646e0|file:/data/app/com.nwrnlayout-1/base.apk: avformat_open_input failed, err:Invalid data found when processing input

**Comment by benvium** [comment]
Thanks for the report. This sounds like a device-specific issue not related to the library, so I'm closing it.
