### ISSUE TITLE
Class undefined.

### ISSUE THREAD

**Issue by changx03** [zmxv/react-native-sound#344]
Followed Installation.  The sound class is undefined in react-native 0.52.0

`
import Sound from 'react-native-sound';
`
`
console.log('Sound:', Sound);
`

Tried download package from 
`
"react-native-sound": "git+ssh://git@github.com:zmxv/react-native-sound.git",
`
Still don't have any luck.
Any clue?

**Comment by paulmelnikow** [comment]
Hi! If you're still having this problem can you try upgrading? And if that doesn't work, to post a link to your project?
