### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Acenth** [zmxv/react-native-sound#346]
Can we get a new release of this project? There have been a lot of commits since August. Not everyone will know to add this project via git url to get the latest fixes.

**Comment by maxkomarychev** [comment]
I would love to get this one published https://github.com/zmxv/react-native-sound/commit/51864a88f46620036b0db04fc37e416873ab6825

**Comment by Acenth** [comment]
@trepidity Not sure who can trigger a new release, but it sure would help new folks to the project.

**Comment by maxkomarychev** [comment]
I guess only @zmxv has permissions..

**Comment by trepidity** [comment]
I have published `0.10.5`
