### ISSUE TITLE
Do we have seekTo(time) API?

### ISSUE THREAD

**Issue by thphuc** [zmxv/react-native-sound#347]
As the title, I would want to know if we have seekTo method. Thanks.

**Comment by jcodlingcc** [comment]
[.setCurrentTime() ?](https://github.com/zmxv/react-native-sound/wiki/API#setcurrenttimevalue)

**Comment by thphuc** [comment]
@jcodlingcc It's too late to reply. 
.setCurrentTime() seems working. Thanks!
