### ISSUE TITLE
ld: library not found for -lRNSound-tvOS clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by ZackTRobertson** [zmxv/react-native-sound#356]
React-Native: v0.52.2 and v0.51.0
React-Native-Sound: v0.10.5
Target- IOS 11.2 (iphone 6 Simulator)
OSX xcode 9.2 (9C40b)

Attempted to start new react-native project using npm versions of react-native and react-native-sound (0.10.5). Linked depencies using react-native link react-native-sound and get the following error when I try to execute react native run-ios:

`ld: library not found for -lRNSound-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/AudioTest.app/AudioTest normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/AudioTest.app
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):`

This error does not occur when using react-native-sound 0.10.4. After inspecting the .xcodeproj in xcode there appears to be an issue with the libRNSound-tvOS.a library not supporting the iosimulator.

After removing the entry "libRNSound-tvOS.a" from the Link Binary With Items list in the xcode project settings the build succeeded and I could install/run the app from both xcode and from react native cli with no issues. I imagine this is an issue using Link to install the dependencies. If others face this issue try the above method. I am still trying to work out if there are any other effects from removing the library in question.

**Comment by ZackTRobertson** [comment]
Just to follow up the error likely occurred from a recent problem in npm ([17379](https://github.com/npm/npm/issues/17379)) where the install --save command was deleting other node packages that did not have a lock file in them. Because react native defaults to yarn I made the error of not using yarn to add the react-native-sound to the project.

So now I can verify that 0.10.5 is working on my current configuration with React native 0.51.

**Comment by trepidity** [comment]
Thanks for the feedback @ZackTRobertson . You OK if this thread is closed then?

**Comment by ZackTRobertson** [comment]
Yeah, the problems were mainly with node and oversights on my part.

**Comment by octopicorn** [comment]
Hi @trepidity 

It looks like what happened here was that, despite this issue being local user error related to npm, @dotkebi 's PR was merged, thereby entirely removing tvOS support for this library which was added by @dlowder-salesforce .

This means that react-native-sound cannot work on tvOS at all unless you rely on @dlowder-salesforce 's fork from 2 years ago.

Would it be ok to restore the tvOS target so that users of this library can use it with tvOS apps? I"m happy to submit a PR, or perhaps @dlowder-salesforce might be willing?

**Comment by bobby-hewitt** [comment]
has there been any progress on implementing the tvOS target?

**Comment by dlowder-salesforce** [comment]
For recent React Native since 0.60, react-native-sound should be integrated using Cocoapods.  Doing it this way, the only change needed is to just add the tvos platform to s.platforms in the podspec.

**Comment by bobby-hewitt** [comment]
Boom! all working. There seemed to be a bit of code in there relating to the silence switch which stopped it building but just deleted it and all good.  Thanks :)

**Comment by mattallard123** [comment]
@douglowder made that change to podspec and getting a AVAudioSessionPortOverrideSpeaker is unavailable: not available on tvOS build erro on iOS. On latest version of tvOS. Any suggestions? Thank you!

**Comment by douglowder** [comment]
@mattallard123 thanks for the report -- I'll have a look

**Comment by mehthabux** [comment]
@douglowder , the above link give me 404, can you please share the patch here

**Comment by douglowder** [comment]
@mehthabux https://github.com/douglowder/RNAppleTVTalk/blob/9d99037f7cba28a246fed255f7f19a9f8da2cb25/patches/react-native-sound%2B0.11.0.patch

**Comment by mehthabux** [comment]
@douglowder . thank you 👍
