### ISSUE TITLE
ios compilation issue

### ISSUE THREAD

**Issue by prashantham** [zmxv/react-native-sound#365]
Hi, I get this error on running run-ios command

ld: library not found for -lRNSound-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
** BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/prashanth/SoundDemo/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp
	Analyze Base/RCTModuleMethod.mm
(2 commands with analyzer issues)

The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/SoundDemo.app/SoundDemo normal x86_64
(1 failure)
```

**Comment by vadermemo** [comment]
same here, I am using:
  "react": "16.2.0",
   "react-native": "0.52.2",
Xcode Version 9.2 (9C40b)

ld: library not found for -lRNSound-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)


@prashantham Workaround: You can manually delete libRNDeviceInfo-tvOS.a in Xcode -> [Your iOS build target] -> Build Phrases -> Link Binary with Libraries.

**Comment by trepidity** [comment]
I believe this issue was fixed in https://github.com/zmxv/react-native-sound/pull/357
I haven't made a new release yet.
