### ISSUE TITLE
Can not play a file  on Android

### ISSUE THREAD

**Issue by tasiyo7333** [zmxv/react-native-sound#37]
I would like to play downloaded mp3 file , but I can't.

The downloaded directory is under the path which is got from "react-native-fs" 's ExternalDirectoryPath().
I checked if the file exists or not . I used exists() of "react-native-fs" and it returned true. 

onError's argument ```error``` is below.  
{“message”:”resource not found”,”code”:”-1”}

I found that this problem occurs by trimmed file extension on Android.
External file path requires file extension except bunbled file on Android.
https://github.com/zmxv/react-native-sound/blob/master/sound.js#L12

### Environment
* Android Physical Device 
* Android version 4.4.4
* React Native v0.25.1
* react-native-sound : v0.8.1
* react-native-fs : v1.4.0

**Comment by zmxv** [comment]
See https://github.com/zmxv/react-native-sound/issues/27
