### ISSUE TITLE
Duplicate RNSound @interface

### ISSUE THREAD

**Issue by alexey-pelykh** [zmxv/react-native-sound#377]
```
react-native-sound/RNSound/RNSound.h:11:1: missing '@end'
@interface RNSound : NSObject <RCTBridgeModule, AVAudioPlayerDelegate>
```

**Comment by alexey-pelykh** [comment]
#378

**Comment by trepidity** [comment]
@sunjae1294 In fa95e59, you added the second Interface. Can you explain the reason behind that?

**Comment by alexey-pelykh** [comment]
And NativeEventEmitter import/reference is missing as well

**Comment by trepidity** [comment]
@alexey-pelykh did you test a build once you removed the second import?

**Comment by alexey-pelykh** [comment]
@trepidity yes, it failed on NativeEventEmitter being undefined, so added an extra change to PR. Yet as far as I can see, behaviour of the library changed in comparison to .5 version, I'll make extra tests to check if that's on our side on inside the library and will get back asap.

**Comment by trepidity** [comment]
OK thanks.

**Comment by alexey-pelykh** [comment]
@trepidity false alarm regarding different behaviour, with #378 changes it actually works normally.

**Comment by trepidity** [comment]
Master and unstable have been updated. version 0.10.7 has been published. This should no longer be an issue.
