### ISSUE TITLE
Playing sound on device

### ISSUE THREAD

**Issue by boblad** [zmxv/react-native-sound#38]
I can get my sounds and the demo app sounds to work on the ios simulator but when I build to my phone on both apps I get no sound. No errors, the app recognizes the mp3 file because I get the length of the mp3 just fine with `getDuration()`, here is some of the code, what am I missing? 

```
class MusicPlayer extends Component {
  constructor() {
    super();
    this.playSong = this.playSong.bind(this);
    this.pauseSong = this.pauseSong.bind(this);
    this.changeVolume = this.changeVolume.bind(this);
    this.backPress = this.backPress.bind(this);
    this.tick = this.tick.bind(this);
    this.state = {
      volume: .5,
      isPlaying: false,
      songLength: 0,
      currentTime: 0,
      interval: null,
      error: null
    }
  }

  componentWillMount() {
    var song = new Sound('collide.mp3', Sound.MAIN_BUNDLE, (error) => {
      if (error) {
        console.log('failed to load the sound', error);
        this.setState({
          error:error.message
        })
      } else { // loaded successfully
        console.log('duration in seconds: ' + song.getDuration() +
            'number of channels: ' + song.getNumberOfChannels());
        this.setState({
          volume: .5,
          song: song,
          isPlaying: false,
          songLength: song.getDuration(),
          currentTime: 0,
          interval: null,
          error: null
        })
      }
    });
  }

  playSong() {
    this.state.song.play();
    this.setState({
      isPlaying: true,
      interval: setInterval(this.tick, 1000)
    })
  }

  pauseSong() {
    this.state.song.pause();
    this.setState({
      isPlaying: false,
      interval: clearInterval(this.state.interval)
    })
  }

  tick() {
    this.state.song.getCurrentTime((seconds) => {
      this.setState({
        currentTime: seconds
      })
    })
  }
```

**Comment by zmxv** [comment]
Where did you call the playSong() method?

**Comment by Frosty92** [comment]
I am having the same problem, any updates @boblad ?

**Comment by boblad** [comment]
I felt really stupid when I figured out my issue, Even if your sound is all
up on Ios but your sound switch on the side or your phone is off it wont
play. I think there is a method in the docs that overrides this though.

**Comment by Frosty92** [comment]
@boblad, take solace in knowing that you aren't the only one feeling stupid. Thanks for your prompt reply, it fixed my issue!

**Comment by 7kfpun** [comment]
I have another issue about the sound.
Works both on simulator and devices, but when I upload to testflight or publish to itunes, sound doesn't work.

**Comment by gloomcheng** [comment]
I have the same issue about sound, works on simulator but does not works on testflight, any suggestion?

**Comment by henninghall** [comment]
I had a similar issue and solved it by replacing "AVAudioSessionCategoryAmbient" with "AVAudioSessionCategoryPlayback" in the enable method in RNSound.m.

**Comment by franzejr** [comment]
there are some update on this issue ?

**Comment by juliangorge** [comment]
any update?
