### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by trepidity** [zmxv/react-native-sound#385]
The original author of this library is no longer active on this project. I am picking up just high-level activities of this project, communication, and coordination. With all that said, there are a couple of things with this project that needs help.

1.  Android
2. Testing

It would be great if someone could pick-up testing PR's that are submitted on Android platforms.

For testing, this project has had no tests. I'm trying to change that and there is an open PR for this. It's going to take a lot of work and it's open to anyone helping on this.

I know there are several open issues right now and they are related, isAndroid and the Integer and Double issue. Both of these need someone to dig in deep and submit a PR that addresses the issue. Remember, complaining doesn't help, feel free to submit a PR with a proposed fix.

**Comment by afilp** [comment]
Hello, 

the Android app does not play sounds anymore, same code, new packages (other, gradle, etc.).

Note sure what causes the problem. The sound does not just play, without errors.

Do you have any progress in trying to organize the continuation of the support? Thanks!
