### ISSUE TITLE
react-native unlink react-native-sound not working properly

### ISSUE THREAD

**Issue by webraptor** [zmxv/react-native-sound#390]
**Steps to reproduce:**
1. Open project root
2. run command: `react-native unlink react-native-sound`

**Expected results:**
React native sound properly removed from project resource, on Android and iOS

**Actual result:**
1. Android: no changes within project
2. iOS: the library is partially **linked** again (**not unlinked**), with libraries and paths being added in the ios _.pbxproj_ file

RN sound version: 0.10.5
RN version: 0.53.3

**Comment by derN3rd** [comment]
Same for `link`

Looks like the "android" folder is missing in `node_modules/react-native-sound`.

**Comment by talha-ahmed** [comment]
android folder mistakenly was added to .gitignore. Its been reverted but I think the changes have not been published yet. In the meanwhile you can just download the folder and copy it inside of node_modules as workaround.

**Comment by PauloLuan** [comment]
as @talha-ahmed mentioned only the github repository has the android folder, temporarily you can fix it by pointing your `package.json` to this repository as I mentioned on #392

**Comment by trepidity** [comment]
Closing this thread so that we can track in #392
