### ISSUE TITLE
No android folder

### ISSUE THREAD

**Issue by aybb** [zmxv/react-native-sound#392]
After installing 0.10.5 i have found that there is no android folder that caused crash while building app. So i downgraded to 0.10.4 and it worked, have no idea how this happenned

**Comment by PauloLuan** [comment]
@aybb   I had the same problem, for some reason the NPM module doesn't have the `android` folder, in which raises this error when the gradlew compilation tries to find the linked module folder (in which not exists).

You can fix it by changing your `package.json` pointing directly to this commit (temporarily whilst they fix it on NPM).

Something like: 

```json
"dependencies": {
    "react-native-sound": "https://github.com/zmxv/react-native-sound#fd89265133963b6914d292bdc9c7f8478440f9ba",
}
```

**Comment by windydang26** [comment]
same me

**Comment by anton6** [comment]
is this going to be fixed anytime soon? I have same problem with 0.10.8

**Comment by dotansimha** [comment]
same here

**Comment by LMestre14** [comment]
Had the same problem, I did "react-native link" and thought that it was weird that it didn't link to Android.
@PauloLuan 's temporary fix did it

**Comment by trepidity** [comment]
`0.10.9` should address this issue, which I just released.

**Comment by LMestre14** [comment]
React-Native link this time worked, except it didn't put the link on build.gradle ( compile project("react-native-sound") );
Besides that, settings.gradle and MainApplication.java did it right.
This in version 0.10.9
