### ISSUE TITLE
android folder missing when installed with yarn

### ISSUE THREAD

**Issue by dinukasal** [zmxv/react-native-sound#393]
there is no android folder inside node_modules when I added the library with yarn add

**Comment by PauloLuan** [comment]
@dinukasal  I had the same problem, for some reason the NPM module doesn't have the `android` folder, in which raises this error when the gradlew compilation tries to find the linked module folder (in which not exists).

You can fix it by changing your `package.json` pointing directly to this commit (temporarily whilst they fix it on NPM).

Something like: 

```json
"dependencies": {
    "react-native-sound": "https://github.com/zmxv/react-native-sound#fd89265133963b6914d292bdc9c7f8478440f9ba",
}
```

**Comment by PauloLuan** [comment]
Duplicated #392

**Comment by dinukasal** [comment]
Thank you @PauloLuan
