### ISSUE TITLE
It is a  buggy module

### ISSUE THREAD

**Issue by esmatptr** [zmxv/react-native-sound#395]
I'm so sorry, but it is a buggy module, all the time the build is failing because of your module and your changes on production.
It is the 2nd time that this happen.
I will try to find another library for sound with react native.
now, I have the following issue:
and no android folder for it.
Error:Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-sound.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-sound: None of the consumable configurations have attributes.

**Comment by trepidity** [comment]
I've published `0.10.9` do you mind testing with that version?
