### ISSUE TITLE
I'm having errors in running Android

### ISSUE THREAD

**Issue by paapii3d** [zmxv/react-native-sound#397]
React-native link react-native-sound only links my IOS, it doesn't link my android

```
/projects/hcdd$:react-native link react-native-sound 
Scanning folders for symlinks in /projects/hcdd/node_modules (11ms) 
rnpm-install info iOS module react-native-sound is already linked 

```
so wen i run `react-native run-android` i get an error. How can i fix this? But IOS works fine.

**Comment by trepidity** [comment]
What version of RNS?

**Comment by paapii3d** [comment]
I already used the update u made, it has been fixed. thanks alot...
I would be grate if i can get a code on hw to make loop, play and pause using same button
