### ISSUE TITLE
Able to play sound only if filename has no extension

### ISSUE THREAD

**Issue by Frosty92** [zmxv/react-native-sound#40]
If my filename is something like this: 

`audioFileName += "/" + timeStamp;`  I have no problem with playing/pausing/etc. However, if my filename has an extension, like so: `audioFileName += "/" + timeStamp + ".wav"`; I get the following error: 
`failed to load the sound Object {message: "resource not found", code: -1}`. 

This error is on Android. My device is running Marshmallow.

**Comment by zmxv** [comment]
Please upgrade to v0.8.3 and give it another try.

**Comment by Frosty92** [comment]
I will give that a try first chance I get and report back!

**Comment by Frosty92** [comment]
Ok, this works fine now, you can close the issue.
