### ISSUE TITLE
Need sound-player example

### ISSUE THREAD

**Issue by benevbright** [zmxv/react-native-sound#412]
Hi, thanks for this great library.

I coded some to demonstrate 'sound-player' with using this module.
I hope my example would help someone to use `react-native-sound` well.
https://www.npmjs.com/package/react-native-sound-playerview

![demo](https://user-images.githubusercontent.com/916690/38447395-008b8d4e-3a38-11e8-9fbe-490301da3e51.gif)

I'll request a pull request.

**Comment by dammy95** [comment]
Great job! I think this should be included in the `README.md` file as well 👍

**Comment by paulmelnikow** [comment]
Done in #413. Thanks!
