### ISSUE TITLE
Sound playing via Receiver instead of phone speaker in IOS

### ISSUE THREAD

**Issue by Frosty92** [zmxv/react-native-sound#42]
I have no problems with playing/manipulating the sound file in IOS, but the sound is coming from the receiver so it's not practical. I am using the latest version of this module, testing on Iphone 5s.

**Comment by nclaveeoh** [comment]
I'm experiencing the same thing, the sound does not play from the speaker. Also have 5s.

**Comment by wootwoot1234** [comment]
I'm having the same issue.  I'm using [react-native-audio](https://github.com/jsierles/react-native-audio) and it only happens after I've recorded audio.

**Comment by wootwoot1234** [comment]
@zmxv any idea why this is happening?

**Comment by wootwoot1234** [comment]
For other people having this issue.  Calling `.setCategory("Playback");` right before `.play();` fixed my issue.

**Comment by vaibhawc** [comment]
No, this doesn't work in my case.

**Comment by pottercomuneo** [comment]
I'm having the same problem, even in the example, any solution?

**Comment by dennislaupman** [comment]
> No, this doesn't work in my case.
+1

**Comment by benvium** [comment]
This sounds like a conflict between react-native-audio and this library. 

EDIT: Yeah, it's setting the category to AVAudioSessionCategoryMultiRoute. 
See https://github.com/jsierles/react-native-audio/blob/master/ios/AudioRecorderManager.m

Should be fixable by calling .setCategory('Playback') *after* react-native-audio has finished recording.

**Comment by benvium** [comment]
I'm closing this issue for now. If this comes up again, let me know and I'll reopen.

**Comment by hemaliVadher** [comment]
It didn't work after setting up setCategory('Playback'). Because I want to record audio and play that audio at the same time, not after react-native-audio has finished recording.

**Comment by hemaliVadher** [comment]
Please give me suggestions if you have any. I have facing issues with iOS 16 particularly. So, it would be great if you share any suggestions asap @benvium .
