### ISSUE TITLE
Problem with unicode and space and special characters

### ISSUE THREAD

**Issue by mehdihz** [zmxv/react-native-sound#420]
I was using absolute path and facing problem of unicode and special chars and space character.
The code was like this:

```
Sound.setCategory("Playback");
const dir = RNFetchBlob.fs.dirs.DocumentDir;
let file = new Sound(
  dir + playing.filePath,
  null,
  error => {
    if (error) {
      console.log("failed to load the sound", error);
      return;
    }

    file.play();
  }
);

```
But it was not working for special and unicode included paths. 

# **Solution:**
I've found I should use encoding of url. Just use `encodeURI(path)` before passing it to sound constructor.

Fixed code:

```
let file = new Sound(
  encodeURI(dir + playing.filePath),
  null,
  error => {
    if (error) {
      console.log("failed to load the sound", error);
      return;
    }

    file.play();
  }
);
```

**Comment by nicbarker** [comment]
Just a heads up to anyone who ends up here googling, the above solution will not work for Android out of the box. If the first part of the URI is encoded (the double slash after http, etc) the file will not load. You need to do something like this:
```
const urlParsed = url.parse(yourAudioFile)
const audio = new Sound(urlParsed.protocol + '//' + urlParsed.host + encodeURI(urlParsed.pathname), null, (error) => {
```
