### ISSUE TITLE
How to deal with base64 encoded files that was downloaded remotely?

### ISSUE THREAD

**Issue by itinance** [zmxv/react-native-sound#44]
I download mp3 files from a remote source with [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) and store them in local filesystem with [react-native-fs](https://github.com/johanneslumpe/react-native-fs).
However, the data is stored in base64 encoded then.

Is it possible to play these files with this react-native-sound? Or how can i decode the base64 to native binary data?

**Comment by zmxv** [comment]
Please base64-decode the files first.
