### ISSUE TITLE
when vibrate mode on android device

### ISSUE THREAD

**Issue by njustice4all** [zmxv/react-native-sound#441]
it sounds

How can I not hear the sound?

setCategory is not working

device - android SM-A530N - 7.1.1
os - mac 10.13.4
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-sound": "^0.10.9"

```
componentDidMount() {
  this.alarm = new Sound('alarm.mp3', Sound.MAIN_BUNDLE, error => {
    if (error) {
      console.log('failed to load the sound', error);
      return;
    }

    this.alarm.setVolume(1);
    this.alarm.setNumberOfLoops(-1);
  });
}

playAlarm = () => {
  this.alarm.play(success => {
    console.log(success);
  });
};

stopAlarm = () => {
  this.alarm.stop();
};
```

**Comment by njustice4all** [comment]
setCategory is not working

**Comment by tkiefhaber** [comment]
@njustice4all have you seen this: https://github.com/zmxv/react-native-sound/issues/173#issuecomment-299839186

This worked for me.
