### ISSUE TITLE
Android Build Error:  com.zmxv.RNSound not exists And can not found Symbol: new RNSoundPackage()

### ISSUE THREAD

**Issue by zhenizhui** [zmxv/react-native-sound#442]
### Versions && Environment I use
+ react: 16.2.0
+ react-native:  0.53.3
+ react-native-sound: 0.10.9
+ Win 10
+ node 8.9.1
+ npm 5.7.1

### Reproduce step 

+ npm install react-native-sound --save

+ react-native link react-native-sound

+ react-native run-android

### Problem

![react-native-sound-error](https://user-images.githubusercontent.com/13503884/40712459-605c0d58-6430-11e8-82fe-7d67e947fcd4.png)

Help, please 😢

**Comment by zhenizhui** [comment]
I found a relate issue https://github.com/zmxv/react-native-sound/issues/379 while it is not the same error

**Comment by SNVID** [comment]
I got the same issue. I managed to get passed it by manually linking it by following the instructions in https://github.com/zmxv/react-native-sound/wiki/Installation

For me, the android/app/build.gradle didn't have the compile dependency. 

i.e. this step:
Edit android/app/build.gradle to declare the project dependency:

```
dependencies {
  ...
  compile project(':react-native-sound')
}
```

**Comment by zhenizhui** [comment]
@SNVID  thanks you! it works!
