### ISSUE TITLE
in RN 0.52.0  iOS  undefined is not an object (evaluating  'RNSound.IsAndroid' )

### ISSUE THREAD

**Issue by shijinwu** [zmxv/react-native-sound#446]
undefined is not an object (evaluating  'RNSound.IsAndroid' )

**Comment by dskoneczny** [comment]
@shijinwu 
https://github.com/zmxv/react-native-sound/issues/352#issuecomment-360475664

**Comment by tetreault** [comment]
no functional verified solution in that thread @dskoneczny and this shouldn't happen on iOS out-the-box after the linker runs successfully. Currently this error occurs even from merely importing `react-native-sound`

**Comment by isaaclem** [comment]
Just clean the cache and restart your app will do.

**Comment by hellohaidev** [comment]
same problem

**Comment by isaaclem** [comment]
@tetreault : Have you actually tried and my suggestion failed? Because I was facing the same issue and I could fix it by running the below command. 

```
watchman watch-del-all && rm -rf node_modules/ && yarn cache clean && yarn install && yarn start -- --reset-cache
```

**Comment by tetreault** [comment]
I have indeed and it didn't work on my end. Same error thrown just by merely importing it. also tried random other things like cleaning the xcode project etc with no luck.

**Comment by nabehide** [comment]
This works for me.
```Console
rm -rf ios && react-native eject
react-native link
react-native run-ios
```

**Comment by paulmelnikow** [comment]
Hi! If you're still having this problem, could you please post a link to a project that reproduces the problem, give information about your environment, and say what steps you have already tried?

This is the most common issue faced by react-native-sound users and it would be good to add documentation listing the possible resolutions. A pull request would be welcome; I've opened #592 to track that.
