### ISSUE TITLE
ios：cant play

### ISSUE THREAD

**Issue by HouLinguo** [zmxv/react-native-sound#457]
`react-native :0.42.3`
`"react-native-sound": "^0.10.5",`

![a581152fbc174ebdfe837a372756459a](https://user-images.githubusercontent.com/22906873/42499350-5eca0fbc-83e3-11e8-9451-a5d46ade641b.jpg)

**Comment by HouLinguo** [comment]
ios cant support amr?

**Comment by paulmelnikow** [comment]
Hi! If you're still having this problem, could you post the code and the file that's causing the problem?
