### ISSUE TITLE
BuildToolsVersion compatibility with RN 0.56

### ISSUE THREAD

**Issue by xaviraol** [zmxv/react-native-sound#458]
The error:

```
 Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-sound'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-sound'. Minimum required is 25.0.0

```

Would it be possible to update them following [this](https://github.com/react-community/react-native-maps/pull/2047) approach?

**Comment by solaomosola** [comment]
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-sound'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-sound'. Minimum required is 25.0.0

**Comment by Gatreek92** [comment]
I'am having the same issue after updating to react native 0.56.0 anyone knows what to do ?

**Comment by Jaewoook** [comment]
same issue in react native 0.56.+. are you have update plan yet?

currently I manually change the `react-native-sound/android/build.gradle` file's sdk version.

**Comment by skb1129** [comment]
`react-native-sound` package needs to be updated to use with RN 0.56

**Comment by paulmelnikow** [comment]
Looks like this has been resolved. The project now supports RN 0.60.
