### ISSUE TITLE
getCurrentTime without callback

### ISSUE THREAD

**Issue by tomasite** [zmxv/react-native-sound#46]
I would like to retrieve the current time directly, without passing a callback or at least synchronously. Do you think it could be conceivable?

Thanks in advance,

**Comment by zmxv** [comment]
Sorry, synchronous getCurrentTime isn't possible.

**Comment by tomasite** [comment]
Ok thanks anyway.
Just to be sure to understand why is it mandatory to access the current player time through a callback?
(I don't see any callback in the core implementation neither on android nor on ios but maybe I miss something)

**Comment by zmxv** [comment]
This is a limitation of React Native's native module library.
