### ISSUE TITLE
Error on IOS. What is this?

### ISSUE THREAD

**Issue by ramos-lucas** [zmxv/react-native-sound#461]
![simulator screen shot - iphone x - 2018-07-12 at 22 11 08](https://user-images.githubusercontent.com/18932708/42667681-4e557f1c-8623-11e8-8a01-88e7aea83416.png)

**Comment by paulmelnikow** [comment]
Hi! If you're still experiencing this could you post your code?

**Comment by paulmelnikow** [comment]
Related to #468?

**Comment by zabojad** [comment]
@ramos-lucas did you find a solution?

**Comment by afilp** [comment]
I also have the same problem, did anyone find a solution please? Thanks!
