### ISSUE TITLE
playing audio from url containing Polish ąęóńśćźż characters does not work

### ISSUE THREAD

**Issue by GA1** [zmxv/react-native-sound#470]
this code

`     
 const sound = new Sound('www.someurlwithąężźćPolishcharacters.com/blabla, null, (e) => {
        if (e) {
          console.log('Error on playing audio', e)
        } else {
          sound.play()
        }
      })
    }
`

would print an error:

> ReactNativeJS: 'Error on playing audio', { extra: -1005, what: 1 }

Occured on devices:
Samsung Galaxy S4 mini,
The error does not occur on:
Nexus 5x, Android 8.1

**Comment by schumannd** [comment]
We are experiencing the same issue, only on samsung devices. Have you found out how to solve this?

**Comment by paulmelnikow** [comment]
Can you try URL-encoding the filename first?
