### ISSUE TITLE
undefined is not an object (evaluating 'RNSound.IsAndroid')

### ISSUE THREAD

**Issue by aspitsyn** [zmxv/react-native-sound#471]
Hi,
I run react-native expo and IPhone X emulator on MacOS  but I keep getting
"**undefined is not an object (evaluating 'RNSound.IsAndroid')**" error on emulator IPhone X.
Can anyone help please with that issue?
<img width="277" alt="screenshot 2018-07-31 08 18 40" src="https://user-images.githubusercontent.com/15245068/43439140-61d1cd18-949a-11e8-86d5-6e47493b5875.png">

react-native-cli: 2.0.1
react-native: 0.55.4
react-native-sound: 0.10.9

**Comment by tmilewski** [comment]
I'm running into this exact same issue and all I have is

`var Sound = require('react-native-sound')`

**Comment by AilsonFreire** [comment]
You need to link your library. Use "react-native link react-native-sound"

**Comment by aspitsyn** [comment]
[AilsonFreire](https://github.com/AilsonFreire), I have checked that option, no effect.

**Comment by Udbhav12** [comment]
I too faced this problem. 'react-native link react-native-sound' didn't work for me

I managed to resolved this error by following the manual linking steps

**Comment by jean-noelp** [comment]
A solution which worked for me :
- check the manual installation
- remove node_modules
- yarn install
- rebuild & install android package

**Comment by ArtemKosiakevych** [comment]
Have you tried to install Pods after linking?

**Comment by tetreault** [comment]
This is happening for me, and my project is iOS only. Running on my iPhone X.

**Comment by jnosornov** [comment]
It might be something related to permissions, I managed to solved by adding permissions to Manifest in android folder, using the next line of code.

`<uses-permission android:name="android.permission.RECORD_AUDIO" />`

But I am not sure about Expo implementation, do not know if it comes configured out the box. Go check [react-native-sound](https://www.npmjs.com/package/react-native-audi
o) npm package **read me** description.

**Comment by internetegir** [comment]
> [Udbhav12](https://github.com/Udbhav12), how you managed to resolve that issue, could you please describe the manual linking steps?

have you find any solution & resolve the issue ?

**Comment by rahamin1** [comment]
I have the same problem on android.
I did a manual installation of the package.

**Comment by manishsxnaa** [comment]
I am resolved this issue by manually link library in X code, actually i did react-native link that is not giving any error so assume it's linked but when i have checked xcode then see this library is not linked so when i have linked manually and create new build then it's working perfectly.

**Comment by paulmelnikow** [comment]
If you're still having this problem, could you please post a link to a project that reproduces the problem, give information about your environment, and say what steps you have already tried?

This is the most common issue faced by react-native-sound users and it would be good to add documentation listing the possible resolutions. A pull request would be welcome; I've opened #592 to track that.
