### ISSUE TITLE
Pause, stop, and resume not working react-native android 

### ISSUE THREAD

**Issue by shaheem-khanzada** [zmxv/react-native-sound#473]
hey i need help 
```
pauseSound(){
  const sound = new Sound(this.props.url);
  sound.pause()
}

stopSound(){
  const sound = new Sound(this.props.url);
  sound.stop()
}
resumeSound(){
  const sound = new Sound(this.props.url);
  sound.resume()
}
```

**Comment by Matzielab** [comment]
You're creating a new Sound instance in every function. So you're trying to pause, stop and resume something that is not playing. You need to call those funcs on the same instance as the play is played on to control the playing sound.
