### ISSUE TITLE
New require() feature doesn't work

### ISSUE THREAD

**Issue by chetstone** [zmxv/react-native-sound#48]
@lostintangent did you see my comment on your [PR](https://github.com/zmxv/react-native-sound/pull/47)? I wonder if you could please take a look?

thanks

**Comment by aahz** [comment]
Added pull-request https://github.com/zmxv/react-native-sound/pull/68, should be working after merging with it.

**Comment by benvium** [comment]
This works in 0.9.0 (iOS)
