### ISSUE TITLE
IOS getting wrong duration time. Anybody solved this?

### ISSUE THREAD

**Issue by appaaaa** [zmxv/react-native-sound#488]
IOS some songs return wrong duration time.

but Android get correct duration time.

Anybody solve this?

**Comment by appaaaa** [comment]
I found that 
in mp3 incoded tag : id3v2.3
 - IOS : wrong duration time
 - Android: working well

if not attach id3v2.3
 - IOS : working well
 - Android: some device has a problem(galaxy s8+) - song playing delay is too long (more than 30 seconds)

**Comment by paulmelnikow** [comment]
Hi! If you're still experiencing this issue, could you post an example of a file that gets the wrong time, along with code that reproduces the problem? Thanks!
