### ISSUE TITLE
Sound stop after about 30 second

### ISSUE THREAD

**Issue by hiradary** [zmxv/react-native-sound#491]
<img width="985" alt="screen shot 2018-09-17 at 5 40 35 pm" src="https://user-images.githubusercontent.com/29271309/45635764-1cd26000-babb-11e8-8475-81f546fa7e8c.png">

I have a carousel, in which when I swipe, I want to play a sound. It was working perfectly for first 3-4 times of swiping, but after that the sound didn't play. So I tried to use setInterval, so that I play that sound many times (to see whether it's react-native-sound problem or my carousel). It works for, almsot 10-15 times, then It stopps. What I did wrong?

**Comment by naklow12** [comment]
Same problem still I have. And never solved. I have a game, after maybe 40-60 seconds I can't hear any sound.

**Comment by paulmelnikow** [comment]
Hi! If you're still experiencing this issue, could you please open an issue with more details following the issue template? Thanks!
