### ISSUE TITLE
getSystemVolume returns null

### ISSUE THREAD

**Issue by natimenashe** [zmxv/react-native-sound#496]
Hi,

I am trying to use the method getSystemVolume with passing it a callback method.

Here is my code:

callBackMethod(volume) {
		console.log('in callback');
		console.log(volume);
	}
this.soundObj.getSystemVolume(volume => this.callBackMethod(volume));	

logs printed:
in callback
null

I must say i am pretty new with react-native so maybe i am missing something.
vers:
"react-native-sound": "^0.10.9",
"react": "16.3.1",
 "react-native": "^0.55.4",

**Comment by franck-nadeau** [comment]
Pushed a fix for this issue : https://github.com/zmxv/react-native-sound/pull/569
