### ISSUE TITLE
why duration()  can't get total time in android

### ISSUE THREAD

**Issue by zhuhai123** [zmxv/react-native-sound#498]
It works fine on iOS, but on Android the call to getDuration() is returning 0 seconds. Any idea why?

**Comment by paulmelnikow** [comment]
Hi! If you're still experiencing this issue, could you please open an issue with more details following the issue template? Thanks!

**Comment by meghaptg** [comment]
@paulmelnikow, i'm facing this issue, any update on it?

**Comment by paulmelnikow** [comment]
@meghaptg Could you please open a new issue following the issue template?
