### ISSUE TITLE
has error when run on ios8 

### ISSUE THREAD

**Issue by askday** [zmxv/react-native-sound#50]
16:41:56.198 ERROR: 404: error -66680
16:41:56.198 ERROR: >aq> 1600: failed (-66680); will stop (11025/0 frames)

is it support on ios8?

**Comment by askday** [comment]
16:41:56.198 ERROR:     404: error -66680
16:41:56.198 ERROR:     >aq> 1600: failed (-66680); will stop (11025/0 frames)

is it support on ios8?

**Comment by zmxv** [comment]
I haven't tested it on iOS 8. Can you verify it with https://github.com/zmxv/react-native-sound-demo ?

**Comment by askday** [comment]
maybe not your problem,I restart simulator then run right.
thx
