### ISSUE TITLE
Volume bug since 0.7.3 

### ISSUE THREAD

**Issue by eranbes** [zmxv/react-native-sound#51]
Volume bug was introduced in 0.7.3 by checking for `isLoaded` and we had to do this to circumvent:

class FixedSound extends Sound {
    play (...args) {
        this.setVolume(this.getVolume());
        return super.play(...args);
    }
}

Any chance to fix it soon?

**Comment by zmxv** [comment]
Can you elaborate on the volume bug? And how is it related to the `isLoaded` function?

**Comment by eranbes** [comment]
We used `const actionSound = new Sound('action.mp3'); actionSound.setVolume(0.5);` to get it attenuated for later uses. It stopped to work because of the isLoaded check.
Now that we use ` actionSound = new Sound('action.mp3', null, () => actionSound.setVolume(0.5));` it works.
Nevertheless, `this._volume` is never actually used and volume is only ​_actually_​ set when sound is loaded, which ​_is_​ strange.

**Comment by benvium** [comment]
setVolume works if the sound is loaded. I agree the docs could be clearer on this point.
