### ISSUE TITLE
How to play audio from decoded base64?

### ISSUE THREAD

**Issue by DnEgorWeb** [zmxv/react-native-sound#510]
I get base64 encoded audio file from server. Now I want to play this file. I'm trying to decode base64 file and pass it to:
const sound = new Sound(decodedFile, '', error =>(...))
But callback doesn't work. What am I doing wrong and how to properly handle encoded audio files?

**Comment by Linoa65** [comment]
Hello ! 

Same issue, I use Firestore and unable to store audio, so I store it in base64 but now I need to find a solution to play audio with this base64 string I have. If you find a solution, feel free to notify how you did, thanks a lot :)

**Comment by DnEgorWeb** [comment]
@Linoa65 Hi!
Here is the way that I used to solve it:
I used react-native-fs library to create file from my base-64 string and then to create new Sound using path of created file:
`const path = '${RNFS.DocumentDirectoryPath}/${attachment}.aac';`
`RNFS.writeFile(path, yourBase64String, 'base64').then(() => playSound())`
`const playSound = () => {`
`const sound = new Sound(path, '', () => callback(sound))`
`}`
`const callback = () => sound.play(successCallback)`

**Comment by Linoa65** [comment]
Hey @DnEgorWeb !

Thanks for your answer, I will try it tomorrow, really thanks for the solution and your quick answer !

**Comment by nguyenvm** [comment]
> @Linoa65 Hi!
> Here is the way that I used to solve it:
> I used react-native-fs library to create file from my base-64 string and then to create new Sound using path of created file:
> `const path = '${RNFS.DocumentDirectoryPath}/${attachment}.aac';`
> `RNFS.writeFile(path, yourBase64String, 'base64').then(() => playSound())`
> `const playSound = () => {`
> `const sound = new Sound(path, '', () => callback(sound))`
> `}`
> `const callback = () => sound.play(successCallback)`

Thank you very much. It working.

**Comment by Sayyamabbasi786** [comment]
can someone please quote how to convert recorded audio into base64, Thanks in advance

**Comment by jusltop** [comment]
thank you! it worked!

**Comment by aligol20** [comment]
> can someone please quote how to convert recorded audio into base64, Thanks in advance

Did you find any way?

**Comment by hie6953** [comment]
https://base64.guru/converter/encode/audio

**Comment by umairkhan1997** [comment]
> can someone please quote how to convert recorded audio into base64, Thanks in advance

    RNFS.readFile(`${dirs.CacheDir}/hello.mp3`,'base64').then(o => console.log(o, 'base64 audio')).catch(e=>console.log(e,'err ==?> asdasd'))

I used RNFS and read Method to convert my audio into base64

**Comment by hadanghuy** [comment]
Hello everyone, in addition to writing data to a file like that, is there any way to directly read that data to make sound? Thank you very much.

**Comment by s4rath07** [comment]
@hadanghuy Did you find any solution?
