### ISSUE TITLE
Broken on RN 0.29 (even with updates)

### ISSUE THREAD

**Issue by peterpme** [zmxv/react-native-sound#54]
Hey,

I'm trying this out on a clean install of RN 0.29. 
- The sound loads successfully.
- The sound says it has played successfully.

But unfortunately, nothing comes out of my speakers. I tried the demo with an older version of RN and everything is working fine.

I also had this working on a previous app I've tried using 0.27

Thanks,
Peter

Great job by the way :)

**Comment by abhaytalreja** [comment]
@peterpme is this Android or iOS. May be try to do `rnpm link` again.

**Comment by peterpme** [comment]
Hey @abhaytalreja thanks for the quick response! Android. Did this package work for you in 0.29?

**Comment by abhaytalreja** [comment]
Yes @peterpme , it does sometimes but it doesn't work other times... I have this weird problem, some sounds work always and some don't. However, everything works on IOS. 

Not sure what's happening there. I thought it might be the emulator and it may work on device. But unfortunately, don't have an android device :( 

Let me know if you come across something helpful.

**Comment by benvium** [comment]
Am closing this issue due to it's age. Hopefully whatever problem it was has been solved in either newer react-native-sound or react native.
