### ISSUE TITLE
Not working on Windows: Cannot read property 'IsAndroid' of undefined

### ISSUE THREAD

**Issue by huuchi207** [zmxv/react-native-sound#541]
Like [iOS](https://github.com/zmxv/react-native-sound/issues/36), the issue appears on Windows: 
```
var RNSound = require('react-native').NativeModules.RNSound;
var IsAndroid = RNSound.IsAndroid;
```
How can I fix that? Thank you in advance!

**Comment by paulmelnikow** [comment]
Hi! If you're still having this problem, could you please post a link to a project that reproduces the problem, give information about your environment, and say what steps you have already tried?

This is the most common issue faced by react-native-sound users and it would be good to add documentation listing the possible resolutions. A pull request would be welcome; I've opened #592 to track that.
