### ISSUE TITLE
production apk not bundling .mp3 in raw folder

### ISSUE THREAD

**Issue by sja1n** [zmxv/react-native-sound#544]
I have bundled the sounds with my apk as instructed in manual in `raw` folder, whenever but the final apk instead of complete `.mp3` file there is only probably link of the file i.e. the file size is only 2 bytes.

**Comment by RodneyOnyi** [comment]
This is probably due to setting shrinkResources true in build.gradle

**Comment by sja1n** [comment]
Hi, i tried to see if there was any such settings and there was not, surprisingly I was able to bundle .mp3 files if i pre-pend names with `notification_`
