### ISSUE TITLE
Bluetooth does not work;

### ISSUE THREAD

**Issue by cq0702** [zmxv/react-native-sound#545]
When I open Bluetooth and link the Bluetooth earphone,playing the mp4.It can't play through Bluetooth.It plays on the phone.You can try it.And is there any solution to solve it?

**Comment by cq0702** [comment]
I have resoved it and submit a PR. #548

**Comment by paulmelnikow** [comment]
Hi! From https://github.com/zmxv/react-native-sound/pull/548#pullrequestreview-223420824 it looks like `Sound.setCategory('playback')` is the solution to this issue. Feel free to reopen if not!
