### ISSUE TITLE
[Android] Uses or overrides a deprecated API

### ISSUE THREAD

**Issue by lorenc-tomasz** [zmxv/react-native-sound#555]

**Comment by lorenc-tomasz** [comment]
Error:

> node_modules/react-native-sound/android/src/main/java/com/zmxv/RNSound/RNSoundModule.java uses or overrides a deprecated API.

**Comment by djlolito** [comment]
some

**Comment by UserSty** [comment]
The same. When do you planning to fix it?

**Comment by paulmelnikow** [comment]
A pull request would be welcome!

**Comment by paulmelnikow** [comment]
Same as #550; let’s track there.
