### ISSUE TITLE
cannot read property 'IsAndroid' of undefined

### ISSUE THREAD

**Issue by xiaobei56** [zmxv/react-native-sound#567]
+-- core-js@3.0.1
+-- npm@6.9.0
+-- react@16.8.3
+-- react-devtools@3.6.1
+-- react-native@0.59.5
`-- react-native-cli@2.0.1

![000](https://user-images.githubusercontent.com/18367988/56791354-72cd6a00-6839-11e9-9f3b-264372d4e785.jpg)

i real did react-native link react-native-sound,.
but it still happen to this erro.
how shold i do. help me ,thanks.

**Comment by xiaobei56** [comment]
I had solve the problem by：
add code  at MainApplication：
` @Override
    public void onCreate() {
        super.onCreate();
       reactInstanceManager = ReactInstanceManager.builder()
      …………
      .addPackage(new RNSoundPackage());
      .build();
}
`

**Comment by james2doyle** [comment]
I had to manually add the package in `protected List<ReactPackage> getPackages() { ... }`

```diff
diff --git a/android/app/src/main/java/com/myapp/MainApplication.java b/android/app/src/main/java/com/myapp/MainApplication.java
index 8b3c131..d1d31d4 100644
--- a/android/app/src/main/java/com/myapp/MainApplication.java
+++ b/android/app/src/main/java/com/myapp/MainApplication.java
@@ -19,6 +19,7 @@ import com.facebook.react.ReactNativeHost;
 import com.facebook.react.ReactPackage;
 import com.facebook.react.shell.MainReactPackage;
 import com.facebook.soloader.SoLoader;
+import com.zmxv.RNSound.RNSoundPackage;
 
 import java.util.Arrays;
 import java.util.List;
@@ -46,6 +47,7 @@ public class MainApplication extends Application implements ReactApplication {
             new ReactVideoPackage(),
             new VectorIconsPackage(),
             new RCTPdfView(),
+            new RNSoundPackage(),
             new RNGestureHandlerPackage()
       );
     }

```
