### ISSUE TITLE
Could not find method compileOnly() for arguments [com.facebook.react:react-native:+]

### ISSUE THREAD

**Issue by Rishabh-Rathod** [zmxv/react-native-sound#568]
# Could not find method compileOnly() for arguments [com.facebook.react:react-native:+]

Hi,

I get this error when i try to run on android :
#### react-native --version
>react-native-cli: 2.0.1
>react-native: 0.56.1

**Comment by hinhinvn1111111** [comment]
change compileOnly to compile. it works for me. good luck

**Comment by Rishabh-Rathod** [comment]
Yeah, even i am doing the same to make it work for now but i couldn't understand the reason why it works.If you can help me with understanding differences between compileOnly, compile and implementation it will be great help
