### ISSUE TITLE
有关音频监听的问题

### ISSUE THREAD

**Issue by China-Robin** [zmxv/react-native-sound#572]
我的app正在播放音频，此时我的app进入后台运行，然后有电话进入，此时我的app暂停播放，当电话挂断的时候，音频继续播放，但是不会进入下一首（因为我设置了播放结束后播放下一首），我查看了源码，发现监听的地方，重新播放的时候没有把我的callback设置进去，我只能通过修改源码修复这个问题，希望可以添加一个设置监听方法的函数

**Comment by 13627491210** [comment]
> 



> 

大佬，请问一下怎么改
