### ISSUE TITLE
react-native 0.60.0, isAndroid of undefined, CocoaPods could not find compatible versions for pod "React/Core"

### ISSUE THREAD

**Issue by eyale** [zmxv/react-native-sound#584]
have:
```
    "react": "16.8.6",
    "react-native": "0.60.0",
    "react-native-sound": "0.10.12",
```

have done `npm i` then running a project but receiving the error:
`Cannot read property 'IsAndroid' of undefined`
consoling inside of file 'sound.js' of package
<img width="907" alt="Screen Shot 2019-07-05 at 4 42 52 PM" src="https://user-images.githubusercontent.com/8945716/60726504-66a20f00-9f44-11e9-84a1-72678e629b3d.png">
and this is true, there are no RNSound
![image](https://user-images.githubusercontent.com/8945716/60726580-94875380-9f44-11e9-824e-3a81cd4c9355.png)

`pod install` returns me:
```
[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    RNSound (from `/Users/antongoncharov/Development/hearingapp/node_modules/react-native-sound`) was resolved to 0.10.12, which depends on
      React/Core

None of your spec sources contains a spec satisfying the dependency: `React/Core`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by kouohhashi** [comment]
I have same error. have you find a solution?

**Comment by jdegger** [comment]
Same problem here, the RN upgrade guide specifies to inlcude 

`pod 'React-Core', :path => '../node_modules/react-native/React'`

but this doesn't work.

**Comment by jdegger** [comment]
PR #579 fixes this issue

**Comment by muzammil-triffort** [comment]
The most easiest solution is:
`react-native uninstall react-native-sound`
and then install again `npm i -save react-native-sound`
