### ISSUE TITLE
Publish version with fixed podspec for RN 0.60

### ISSUE THREAD

**Issue by jacargentina** [zmxv/react-native-sound#591]
I 've seend there is a fix for the podspec; a new release please to use that?🙏

**Comment by paulmelnikow** [comment]
I don't have access to publish, but I'd be happy to prepare a release!

**Comment by jacargentina** [comment]
@paulmelnikow  who can publish then...

**Comment by paulmelnikow** [comment]
I emailed @zmxv asking for access.

**Comment by paulmelnikow** [comment]
It's shipped! 🚀 

https://www.npmjs.com/package/react-native-sound

This software is alpha quality and may have bugs. I urge you to do your own testing!
