### ISSUE TITLE
Not playing aac

### ISSUE THREAD

**Issue by hasen6** [zmxv/react-native-sound#6]
I have it working just fine with mp3s but I can't see why aacs won't play since you say they would. I've tried with both .aac and .m4a with no success. The files have been added into the project, definitely should be working since everything is exactly the same.

**Comment by zmxv** [comment]
Would you share the .aac/.m4a file that can reproduce the bug?

**Comment by hasen6** [comment]
It doesn't work with any m4a/aac I tried whether I encoded myself or others that were already m4a. I've attached one for your testing.
[1.m4a.zip](https://github.com/zmxv/react-native-sound/files/68102/1.m4a.zip)

**Comment by zmxv** [comment]
I've created a simple app that plays your 1.m4a file without any problems. Here's the full source:

```
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} = React;
var Sound = require('react-native-sound');

var RNSoundDemo = React.createClass({
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this.play}>
        <Text style={styles.whoosh}>
          Whoosh!
        </Text>
        </TouchableOpacity>
      </View>
    );
  },

  play() {
    var s = new Sound('1.m4a', Sound.MAIN_BUNDLE, (e) => {
      if (e) {
        console.log(e);
      } else {
        s.play();
      }
    });
  },
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  whoosh: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});

AppRegistry.registerComponent('RNSoundDemo', () => RNSoundDemo);
```

**Comment by hasen6** [comment]
That does not work for me.....your code plays mp3s but does not play the
m4a. Maybe it something to do with XCode version or I don't know what? Must
be some other reason.

Regards,
Simon P Burgess
http://www.BetterCredit.co.uk <http://www.bettercredit.co.uk/>

**Comment by zmxv** [comment]
I was testing it on XCode 7.1.1 with React Native 0.17.0 and react-native-sound 0.5.1.

**Comment by hasen6** [comment]
Ok I'm using React Native 0.17, XCode 7.2. react-native-sound 0.5.1. Maybe its the different version of XCode unless you have any other ideas?

**Comment by zmxv** [comment]
Maybe this helps? http://stackoverflow.com/questions/17867213/nsbundle-finds-mp3-file-but-not-m4a-when-trying-to-instantiate-avaudioplayer

**Comment by hasen6** [comment]
Yeah that was it! That's weird that the mp3s get added automatically to Copy bundle resources. That's why they played and the m4as didn't. Thanks for your help.
