### ISSUE TITLE
Why is it asking for micro permission?

### ISSUE THREAD

**Issue by pierroo** [zmxv/react-native-sound#606]
:beetle: **Description**

I only want to use the plugin to play sound; not to record anything.
I am not doing any such call for recording, but upon launching my app when I call "new Sound(...)" it asks for micro permission right away.

Is there any way to get rid of this permission asking entirely?

**Comment by paulmelnikow** [comment]
Could you fill out the template, please?

https://github.com/zmxv/react-native-sound/issues/new?labels=question&template=1_Get_help.md
