### ISSUE TITLE
React/Core does not exist in react native 0.60

### ISSUE THREAD

**Issue by noway** [zmxv/react-native-sound#612]
:beetle: https://github.com/facebook/react-native/issues/25553

:beetle: **What is the observed behavior?** fails with `None of your spec sources contain a spec satisfying the dependency: `React/Core`.`

:beetle: **What is the expected behavior?** to succeed pod install

:bulb: **Possible solution**

Change dependency from React/Core to React-Core in podspec

:bulb: **Is there a workaround?**

```
grep -rl "s.dependency 'React/Core'" node_modules/ | xargs sed -i '' 's=React/Core=React-Core=g'

```
:bulb: **If the bug is confirmed, would you be willing to create a pull request?** sorry no capacity

**Is your issue with...**

- [x] iOS
- [ ] Android
- [ ] Windows

**Are you using...**

- [x] React Native CLI (e.g. `react-native run-android`)
- [ ] Expo
- [ ] Other: (please specify)

**Which versions are you using?**

- React Native Sound: 0.10.9
- React Native: 0.60
- iOS: iphone 7 plus with the latest updates as of 28 august 2018
- Android: not relevant
- Windows: not relevant

**Does the problem occur on...**

- [ ] Simulator
- [ ] Device
- [x] During build time

**If your problem is happening on a device, which device?**

- Device:

**Comment by noway** [comment]
I looked at https://github.com/zmxv/react-native-sound/releases, and 0.11.0 is marked pre-release, i'm on v0.10.4 which I thought was the latest version. Should the releases be updated, or 0.11.0 is still a release candidate?

**Comment by RWOverdijk** [comment]
Hey! Quick question, when will this be a "real" release?

**Comment by paulmelnikow** [comment]
In the future, please ignore the "prerelease" status in GitHub. This project is not using it to signal anything different about the releases, which are all alpha quality.
