### ISSUE TITLE
null is not an object (evaluating 'RNSound.IsAndroid')

### ISSUE THREAD

**Issue by FatemeKhodayari** [zmxv/react-native-sound#618]
:beetle: **Description**

I tried installing and using this package for playing an audio file which I fetch from an API. 

:beetle: **What have you tried?**

I followed the instructions in the wiki. I've installed the package using npm. I've also linked it using `react-native link react-native-sound`. It says that both Android and IOS modules have been linked. But then when I start the metro server and reload the app, everything crashes giving the error. I've also tried rebuilding the project but it doesn't work either.

:beetle: **Please post your code:**

```js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { View } from 'react-native';
import { Card, Image, Button } from 'react-native-elements';
import Sound from 'react-native-sound';

class Activity extends Component {

  playSound() {
    const track = new Sound(this.props.sound, null, (error) => {
      if (error)
        console.log("Can't play sound. ", e);
      else
        track.play();
    });
  }

  render(){
    return (
      <Card title={this.props.title}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', paddingTop: 20 }}>
          <Image
            source={{ uri: this.props.questions[0].options[0].value.image }}
            style={{ width: 100, height: 100 }}
          />
          <Image
            source={{ uri: this.props.questions[0].options[1].value.image }}
            style={{ width: 100, height: 100 }}
          />
          <Image
            source={{ uri: this.props.questions[0].options[2].value.image }}
            style={{ width: 100, height: 100 }}
          />
        </View>
        <View style={{ alignItems: 'center' }}>
          <Button
            titleStyle={{ fontSize: 40, fontWeight: '700', padding: 50 }} 
            title={this.props.presentation}
            onPress={this.playSound}
          />
        </View>
      </Card>
    );
  }
}

const mapStateToProps = (state) => {
  const { presentation, sound, title, questions } = state.game;
  return { presentation, sound, title, questions };
};

export default connect(mapStateToProps, {})(Activity);
```

**Is your issue with...**

- [ ] iOS
- [x] Android
- [ ] Windows

**Are you using...**

- [x] React Native CLI (e.g. `react-native run-android`)
- [ ] Expo
- [ ] Other: (please specify)

**Which versions are you using?**

- React Native Sound: 0.11.0
- React Native: 0.60.5
- Android: 9.0

**Does the problem occur on...**

- [x] Simulator
- [ ] Device

**Comment by rafaelvinicius** [comment]
Same to me. IOS only.
Android works fine.

**Comment by rafaelvinicius** [comment]
@FatemeKhodayari 
Look this: https://github.com/zmxv/react-native-sound/issues/215#issuecomment-510543679

**Comment by FatemeKhodayari** [comment]
> @FatemeKhodayari
> Look this: [#215 (comment)](https://github.com/zmxv/react-native-sound/issues/215#issuecomment-510543679)
> 
> Running `pod install`
> Deleting `ios/build`
> Running `react-native run-ios`

I think this may work for IOS. But my problem is with Android only. :)

**Comment by FatemeKhodayari** [comment]
As far as I tried, there's no need to do the `react-native link react-native-sound` step. React Native does it automatically. No need to follow the instructions to wiki. Just rebuild the app and reload it. Everything works fine.

**Comment by FatemeKhodayari** [comment]
As far as I tried, there's no need to do the `react-native link react-native-sound` step. React Native does it automatically. No need to follow the instructions to wiki. Just rebuild the app and reload it. Everything works fine.

**Comment by creditcoder** [comment]
Same to me in the Android 10.0 emulator.
react-native: 0.61.5
react-native-sound: 0.11.0
![error](https://user-images.githubusercontent.com/53688893/74525615-6fd46f00-4f5c-11ea-8bda-03e69cf0caa5.png)

**Comment by AdamGerthel** [comment]
I have the same problem. Just installed react-native-sound and I'm getting this error. I've checked the linking (compared to manual steps) and everything looks in order.

**Comment by vaidis** [comment]
same here on linux / expo. The strange is that the same problem occurs also with other libraries like react-native-track-player

**Comment by Cat107** [comment]
Same proble, not working on iOS expo app

**Comment by AdamGerthel** [comment]
@Cat107 Libraries which require linking will never work with an Expo app, unless you're using the bare workflow. See https://docs.expo.io/introduction/why-not-expo/

**Comment by beingArkReal** [comment]
I'm facing exactly the same issue on an ios device, why is this closed what should i do?

**Comment by markdashi** [comment]
> I'm facing exactly the same issue on an ios device, why is this closed what should i do?

try react-native link react-native-sound

**Comment by hewang42** [comment]
> Same problem, not working on iOS expo app
@Cat107 I tried to replace with import {Audio} from 'expo-av'
the error gone but there is no sound still

**Comment by ProPratik1405** [comment]
I am facing the same issue for both in IOS and android emulator

**Comment by faizkhan7896** [comment]
> ```js
> import Sound from 'react-native-sound';
> ```

it's Working

**Comment by markdashi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by faizkhan7896** [comment]
> 

Please write in english

**Comment by AliakseiHryhoryeu** [comment]
Audio for expo - https://docs.expo.dev/versions/latest/sdk/audio/

**Comment by markdashi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cyxstudio** [comment]
its an auto reply, saying he is on vacation and cant reply
