### ISSUE TITLE
Add callback when file has finished loading

### ISSUE THREAD

**Issue by sdeleon28** [zmxv/react-native-sound#62]
In some cases it may be necessary to load a file ad-hoc and play it as soon as it has loaded. It is impossible to do this now without some convoluted polling for the value of `isLoaded()` inside a recurring  `setTimeout` call.

This problem could be solved by providing a functional API that passes the sound instance to a callback once it's finished loaded.

So instead of doing:

```
const sound = new Sound(...);
```

You'd have something like:

```
Sound.load(filename, Sound.MAIN_BUNDLE, (sound, error) => {
  // Do whatever you want with sound and error here
});
```

**Comment by sdeleon28** [comment]
I've worked around this limitation by using an inelegant recursive call inside a `setTimeout` that checks for the value of `isLoaded()` every so often. Kinda hacky but gets the job done. Also with this strategy you can work around the Android limitation that only lets you play 6 pre-loaded files without releasing the `MediaPlayer` (see this post -> http://stackoverflow.com/questions/23665250/mediaplayer-stops-playing-the-sounds-android)

**Comment by benvium** [comment]
You can use the onError callback in the constructor of Sound for this now.

```
new Sound('foo.mp3',  Sound.MAIN_BUNDLE, (error, props) => { if (!error) { .. loaded .. } })
```

**Comment by Rafazor** [comment]
> You can use the onError callback in the constructor of Sound for this now.
> 
> ```
> new Sound('foo.mp3',  Sound.MAIN_BUNDLE, (error, props) => { if (!error) { .. loaded .. } })
> ```

Thanks, it works.
