### ISSUE TITLE
Edit MainActivity.java turned out I needed to edit MainApplication.java

### ISSUE THREAD

**Issue by cagdass** [zmxv/react-native-sound#65]
The step below from `README.md`, I received errors when went ahead and edited my MainActivity.java, the getPackages() function was not there to begin with. Instead, I had the function in MainApplication.java in the same directory: `android/app/src/main/java/.../MainApplication.java`. I thought you may want to cover that in the readme.

Here's that step:

Edit `android/app/src/main/java/.../MainActivity.java` to register the native module:

``` javascript
...
import com.zmxv.RNSound.RNSoundPackage; // <-- New
...

public class MainActivity extends ReactActivity {
  ...
  @Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new RNSoundPackage() // <-- New
    );
  }
```

**Comment by peternann** [comment]
**This is a shitty trap for new users. Wasted about a day.

_Please fix the doco ASAP!_**

**Comment by benvium** [comment]
Agreed - the docs have been updated via PR #85. Thanks for the report.
