### ISSUE TITLE
I  create a new Sound object use remote network;but two things happened；for short sound,it worked as usual,and long durations it wouldn't work; Console the sound object ,I got a duration of -1

### ISSUE THREAD

**Issue by linyangcong** [zmxv/react-native-sound#655]
:beetle: **Description**

:beetle: **What have you tried?**

:beetle: **Please post your code:**

```js
// Please post your code
```

:bulb: **Possible solution**

**Is your issue with...**

- [ ] iOS
- [x] Android
- [ ] Windows

**Are you using...**

- [x] React Native CLI (e.g. `react-native run-android`)
- [ ] Expo
- [ ] Other: (please specify)

**Which versions are you using?**

- React Native Sound:
- React Native:
- iOS:
- Android:
- Windows:

**Does the problem occur on...**

- [x] Simulator
- [x] Device

**If your problem is happening on a device, which device?**

- Device:

**Comment by linyangcong** [comment]
//Click  button will call

playmusic() {
            if (this.state.playState) {
                if (store.getState().musicAction.musicObj!=null||store.getState().musicAction.musicObj!=undefined) {
                    this.stopspin()
                    setTimeout(() => {
                        this.stopplaybar()
                    },500)
                    if(this.sound){
                        this.sound.release()
                        this.sound=null
                    }
                    store.getState().musicAction.musicObj.release();
                    store.getState().musicAction.musicObj = null;
                }

                if (this.timeout) {
                    clearInterval(this.timeout);
                }
                this.setState({
                    playState: false
                })
            }

            else if (!this.state.playState) {
                if(store.getState().musicAction.musicObj==null||store.getState().musicAction.musicObj==undefined){
                    this.setState({loading:true})
                    this.sound = new Sound(this.state.musciPath,(error) => {
                        if (error) {
                            this.setState({ playState: false });
                            return;
                        }
                        this.setState({
                            durations: this.sound.getDuration()  
                        })
                    });         this.props.setMusic({musicDetail:this.props.navigation.getParam('musicDetail'),obj:this.sound})
                        //this.sound and store's musicobject  consoles long Sound would get durations of -1 
                       //I have played the  Audio of 11s  that is ok,but 90s in trouble   
                this.playbar();
                ToastAndroid.show('Loading',2000)
                setTimeout(() => {
                    this.play();
                    this.spin();
                    this.CurrentTimer();
                }, 3000);  
                }
                else{
                    console.log('release Sound Object')
                    store.getState().musicAction.musicObj.release();
                    store.getState().musicAction.musicObj=null
                    if(this.sound){
                        this.sound.release()
                        this.sound=null
                    }
                    this.setState({playState:false},()=>{
                        this.playmusic()
                    })
                }
            }
    }

**Comment by linyangcong** [comment]
wow,Maybe the cause of this problem is too long to load resources, such as mobile network or server bandwidth；I just tried it again, the big audio needs to wait longtime;

**Comment by dingdongping** [comment]
On Android, big audio does not need to wait for a long time, while IOS needs to wait for a long time. How to repair it
