### ISSUE TITLE
Sound does not use speaker

### ISSUE THREAD

**Issue by vaibhawc** [zmxv/react-native-sound#66]
@zmxv , It is using only the ear phone meant for calls. I tried making changes suggested on various forums to make AVAudioSession default to speakers but to no result. Do you have ideas on how it could be achieved? Are there some more settings to be changed for it work?

**Comment by bourgois** [comment]
Hi @vaibhawc we use the following code to set speakers on and off on iOS:
        if (PLAYBACK) {
              this.sound.setCategory("Playback");
            } else {
              this.sound.setCategory("PlayAndRecord");
            }
Normally when the Category is Playback you use the call speaker and when it is PlayAndRecordyou use the main loudspeakers...
