### ISSUE TITLE
Android : Cannot Play Mp3 on Real Device's

### ISSUE THREAD

**Issue by bobbyrinaldy** [zmxv/react-native-sound#664]
:beetle: **Description**

Hello, im trying to play mp3 from physical device (Real Device). the code working for IOS but on ANDROID it says 'Resource not found : error code -1'

:beetle: **What have you tried?**

the file path is like this : 
`/storage/emulated/0/Download/bf7befd8a3abf8aa0bad9d359214fd22.mp3`

i have try to add file:// like this : 
`file:///storage/emulated/0/Download/bf7befd8a3abf8aa0bad9d359214fd22.mp3`
and
`file://storage/emulated/0/Download/bf7befd8a3abf8aa0bad9d359214fd22.mp3`

also, i have try to add content:// like this : 
`content:///storage/emulated/0/Download/bf7befd8a3abf8aa0bad9d359214fd22.mp3`
and
`content://storage/emulated/0/Download/bf7befd8a3abf8aa0bad9d359214fd22.mp3`

but nothing work above.

:beetle: **Please post your code:**

```js
play = async path => {
    let dirs = RNFetchBlob.fs.dirs;
    var pathFile = Platform.select({
      ios: dirs.DocumentDir,
      android: dirs.DownloadDir,
    });
    if (this.sound) {
      this.sound.play(this.playComplete);
      this.setState({playState: 'playing'});
    } else {
     //
      const filepath = pathFile + '/' + path.filename;

      this.sound = new Sound(filepath, null, error => {
        if (error) {
          console.log('failed to load the sound', error);
          Alert.alert('Notice', 'audio file error. (Error code : 1)');
          this.setState({playState: 'paused'});
        } else {
          this.setState({
            playState: 'playing',
            duration: this.sound.getDuration(),
          });
          this.sound.play(this.playComplete);
        }
      });
    }
  };
```

:bulb: **Possible solution**

**Is your issue with...**

- [ ] iOS
- [*] Android
- [ ] Windows

**Are you using...**

- [*] React Native CLI (e.g. `react-native run-android`)
- [ ] Expo
- [ ] Other: (please specify)

**Which versions are you using?**

- React Native Sound : 0.11.0
- React Native: 0.61.5
- iOS: -
- Android: 10
- Windows: -

**Does the problem occur on...**

- [ ] Simulator
- [*] Device

**If your problem is happening on a device, which device?**

- Device: Xiaomi Mi9T

**Comment by luigbren** [comment]
Hi.. Same problem in Samsung S9+ Device.. sound.mp3 cannot play

**Comment by luigbren** [comment]
my friends.. my solution was put the code into mountcomponent..
` constructor(props) {
    super(props);
    this.state = {
     };
    sound = null
  }

componentDidMount =() => {
    this.sound = new Sound('mysound.mp3', Sound.MAIN_BUNDLE, (error) => {
      if (error) {
        console.log('failed to load the sound', error);
        return;
      }
    });
}`

and then turn on when you want....
this.sound.play();

**Note: Android: Save your sound clip files under the directory _android/app/src/main/res/raw_. Note that files in this directory must be lowercase and underscored (e.g. my_file_name.mp3) and that subdirectories are not supported by Android.**

**Comment by ArunKumarVallal99** [comment]
> my friends.. my solution was put the code into mountcomponent..
> 
> ```
> constructor(props) {
>     super(props);
>     this.state = {
>      };
>     sound = null
>   }
> 
> componentDidMount =() => {
>     this.sound = new Sound('mysound.mp3', Sound.MAIN_BUNDLE, (error) => {
>       if (error) {
>         console.log('failed to load the sound', error);
>         return;
>       }
>     });
> }
> ```
> 
> and then turn on when you want.... this.sound.play();
> 
> **Note: Android: Save your sound clip files under the directory _android/app/src/main/res/raw_. Note that files in this directory must be lowercase and underscored (e.g. my_file_name.mp3) and that subdirectories are not supported by Android.**

What if We need to access the Download Directory?  Fetch from Director and play? Could please provide any solution for this scenario?
