### ISSUE TITLE
Sound file not getting played when there is space in application name. Got error - "The operation couldn’t be completed. (OSStatus error -10875.)"

### ISSUE THREAD

**Issue by Girishav** [zmxv/react-native-sound#676]
:beetle: Sound file not getting played when there is space in iOS application name.Got following error "The operation couldn’t be completed. (OSStatus error -10875.)" 

This issue  happening for only iOS. 

React native ver : 0.61.4

**Comment by HossamSamir** [comment]
same

**Comment by rezareact** [comment]
I have same problem

**Comment by Girishav** [comment]
Thank you @rezareact. your suggestion worked for me.
