### ISSUE TITLE
Please explain how make sound from ear speaker.

### ISSUE THREAD

**Issue by KZinc** [zmxv/react-native-sound#688]
:beetle: **Description**

I want sound not from main speaker, but from ear one.
:beetle: **What have you tried?**
I've tried `Sound.setCategory('Playback');` With all of the categories, Alarm makes sound twice quite but still not from speakerphone i want.

There is closed request which says I should use `Sound.setCategory('Playback');`
:beetle: **Please post your code:**
  import Sound from 'react-native-sound';
  Sound.setCategory('Playback');
  ****
  const [voice] = useState(
    new Sound(message, () => {
      if (!timeout) {
        setTimeoutValue(setInterval(() => {
          voice.getCurrentTime((pos) => {
            setCounter(Math.floor((voice.getDuration() - pos) * 10));
          });
        }, 500));
      }
    }),
  );
  ****
  const play = (): void => {
    voice.play(() => voice.release());
  };
  ****
```js
// Please post your code
```

:bulb: **Possible solution**

**Is your issue with...**
- [ ] Android
**Are you using...**

- [ ] React Native CLI (e.g. `react-native run-android`)

**Which versions are you using?**

- React Native Sound: "^0.11.0"
- React Native: "0.62.2"
- Android: 8.1.0

**Does the problem occur on...**
- [ ] Device

**If your problem is happening on a device, which device?**

- Device: Meizu x8

**Comment by KZinc** [comment]
I found that if I use 'Voice' I got needed result.

**Comment by anniewey** [comment]
@KZinc can you share your code? i'm facing same issue.

**Comment by KnowYourLines** [comment]
`Sound.setCategory('Voice');`  is what does the trick. It is not documented anywhere but it worked for me.
