### ISSUE TITLE
ComponenetWillUnmount realease but stop

### ISSUE THREAD

**Issue by rendiwijiatmoko** [zmxv/react-native-sound#694]
:beetle: **Description**

i want to play audio and when move to other screen i want still playing until i open agian or open oother file audio

:beetle: **What have you tried?**

i try to unsubscribe using willunmount

:beetle: **Please post your code:**

```js
componentWillUnmount(){
        if(this.sound){
            this.sound.release();
        }
        if(this.timeout){
            clearInterval(this.timeout);
        }
    }
```

:bulb: **Possible solution**

**Is your issue with...**
- [ ] Android

**Are you using...**
- [ ]  React Native CLI (e.g. `react-native run-android`)

**Which versions are you using?**

- React Native Sound: ^0.11.0
- React Native:0.53
- Android: 10

**Does the problem occur on...**
- [ ] Device

**Comment by akk7300** [comment]
You don't need to write release function for background playing;

`componentWillUnmount(){
        if(this.timeout){
            clearInterval(this.timeout);
        }
    }`
