### ISSUE TITLE
undefined RNSound.setLooping

### ISSUE THREAD

**Issue by huangzuizui** [zmxv/react-native-sound#7]
undefined is not an object (evaluating 'RNSound.setLooping')?

**Comment by zmxv** [comment]
I assume you're on iOS. What version of React Native and XCode are you using?

**Comment by huangzuizui** [comment]
react native is "^0.14.2" and xcode is "7.0.1", thank u

2015-12-25 14:39 GMT+08:00 Zhen Wang <notifications@github.com>:

**Comment by zmxv** [comment]
I was testing it with RN 0.17.0. I'll downgrade to 0.14.2 and try to reproduce the bug.

**Comment by huangzuizui** [comment]
i will try it with 0.17.0. by the way, u r from china?

2015-12-25 14:57 GMT+08:00 Zhen Wang <notifications@github.com>:

**Comment by zmxv** [comment]
I can't reproduce the bug after downgrading to RN 0.14.2, but commit 82209a0 might have fixed your issue. Can you upgrade to react-native-sound v0.7.2 and give it a try?

BTW, yes.

**Comment by zmxv** [comment]
@huangzuizui Can you please confirm?

**Comment by huangzuizui** [comment]
i try it on ios today with  RN 0.17.0 ,it works fine. and on android is ok. thank u..

**Comment by zmxv** [comment]
Thanks for the confirmation. I'm closing the issue.

**Comment by hasen6** [comment]
Getting this issue on 0.18
