### ISSUE TITLE
Project still maintained? 💀

### ISSUE THREAD

**Issue by pawelsas** [zmxv/react-native-sound#716]
Sadly, this project looks abandoned. 
@zmxv could you share your thoughts and plans for `react-native-sound`? There are plenty open issues and open PRs. If you don't have the time to maintain it maybe add maintainers with necessary rights for this repo and npm. Thanks!

**Comment by zmxv** [comment]
I'm no longer developing react-native-sound (or any other RN projects). However, there're four other maintainers.

**Comment by afilp** [comment]
@pawelsas I see the latest release on npm was on 2019, did you find any alternatives or any other solution? Thanks @zmxv for all your efforts, I hope the new maintainers can release new fixes for the issues.

**Comment by pawelsas** [comment]
@afilp I tried expo-av but like most of the expo stuff it didn't meet my requirements (production application at scale). So I fixed my issues with this library on my own and am still using react-native-sound.

**Comment by rdhox** [comment]
@pawelsas You should keep this issue open, we still have no news of the four other maintainers despite a good activity on this repo with a lot of PR. It'll be sad to see this library goes down when so many people actually produce PRs!
