### ISSUE TITLE
What is the proper way to read crashes from firebase crashlytics? and how to find out the exact cause of crash in your code?  as some crashes reported on firebase console are not always easy to understand.

### ISSUE THREAD

**Issue by TeamDlxx** [zmxv/react-native-sound#717]
![image](https://user-images.githubusercontent.com/52232678/104683534-ea7fae80-5718-11eb-9702-de5a73c620fe.png)

**Comment by RomualdPercereau** [comment]
It's probably not related to react-native-sound but probably directly to react-native : https://github.com/facebook/react-native/issues/25923
