### ISSUE TITLE
Android Run Error 

### ISSUE THREAD

**Issue by mehrshadpezeshk** [zmxv/react-native-sound#72]
Hi, 

I get this error when i try to run on android : 
- What went wrong:
  A problem occurred configuring project ':RNSound'.
  > Could not resolve all dependencies for configuration ':RNSound:_debugCompile'.
  > Could not resolve com.facebook.react:react-native:0.12.+.
   Required by:
       AloPeykCourierApp:RNSound:unspecified
    > Could not resolve com.facebook.react:react-native:0.12.0.
       > Could not get resource 'https://jcenter.bintray.com/com/facebook/react/react-native/0.12.0/react-native-0.12.0.pom'.
          > Could not GET 'https://jcenter.bintray.com/com/facebook/react/react-native/0.12.0/react-native-0.12.0.pom'.
             > Connection to https://jcenter.bintray.com refused

I'm on latest react version 0.34.1

Thanks

**Comment by peternann** [comment]
I got a highly similar error behind a corporate (ZScaler) firewall. (Though I ran into problems way earlier - I had modified a single project Gradle config, but needed to set globally)

Just in case it helps anyone, my fix (on Windows) was to create/edit "%USERPROFILE%\\.gradle\\gradle.properties and add config like so:

```
systemProp.http.proxyHost=<Your proxy host or IP>
systemProp.http.proxyPort=<Your http proxy port>
# Typical setting:
systemProp.http.nonProxyHosts=localhost|127.0.0.1|10.*.*.*|192.168.*.*

systemProp.https.proxyHost=<Your proxy host or IP>
systemProp.https.proxyPort=<Your https proxy port>
# Typical setting:
systemProp.https.nonProxyHosts=localhost|127.0.0.1|10.*.*.*|192.168.*.*
```

I also had to get Java to store a Zscaler Root CA in it's 'cacerts' file with 'keystore'. That is a longer topic than reasonable here...

**Comment by benvium** [comment]
Thanks @peternann. @mehrshadpezeshk I'm going to close this one for now, as it doesn't appear to be related to this library specifically.
