### ISSUE TITLE
Wav file not playing in iOS.

### ISSUE THREAD

**Issue by TheChanDI** [zmxv/react-native-sound#720]

**Comment by RomualdPercereau** [comment]
Hello, 
Waw is supported on iOS, do you have any code example?
Which version off react-native-sound and react-native are you using? 

List of supported audio formats https://developer.apple.com/library/archive/documentation/MusicAudio/Conceptual/CoreAudioOverview/SupportedAudioFormatsMacOSX/SupportedAudioFormatsMacOSX.html

**Comment by TheChanDI** [comment]
Hello @RomualdPercereau,
I am using a remote URL of type .wav format. In android, it is working fine but in ios, it doesn't play.
here is the audio: 
http://103.198.9.169/sherpadictionary-web-interface/content/view/sherpaDictionaryArchive/wordPronunciationClip/%E0%A4%9A%E0%A5%8D%E0%A4%AF%E0%A5%80%E0%A4%B5%E0%A4%A6%E0%A4%BE%E0%A4%B5%E0%A4%BE/%E0%A4%9A%E0%A5%8D%E0%A4%AF%E0%A5%80%E0%A4%B5%E0%A4%A6%E0%A4%BE%E0%A4%B5%E0%A4%BE_59719.wav

React Native version: 0.63.4
React native sound version: 0.11.0

**Comment by TheChanDI** [comment]
It looks like the remote URL is not supported for now. So I have to bridge to make it work in iOS.

**Comment by into-piece** [comment]
> It looks like the remote URL is not supported for now. So I have to bridge to make it work in iOS.

Same question. But I work fine in Simulator, though it doesn't work when running on device

**Comment by TheChanDI** [comment]
There isn't a fixed solution for this right now but we can get the solution in other ways.
