### ISSUE TITLE
Publish v0.8.4 to npm

### ISSUE THREAD

**Issue by rawrmaan** [zmxv/react-native-sound#73]
`0.8.3` doesn't contain `setCategory` for iOS, so i had to include this package in my `package.json` by using a recent commit ID. 

Also please consider making a change log, it's very helpful to know what's changed in each version.

Thanks for a great package!

**Comment by ninamanalo19** [comment]
yes, that'll be a great help

**Comment by jamesreggio** [comment]
Ping. Really should publish a version. There are changes over 6 months old which haven't been published.

**Comment by benvium** [comment]
@rawrmaan @jamesreggio Agreed. I've just joined the project and will release a new npm version as soon as I have the access I need. I've asked @zmxv for access to do so.

**Comment by zmxv** [comment]
0.9.0 already released on npm thanks to @benvium
