### ISSUE TITLE
RNSound.play must not be null

### ISSUE THREAD

**Issue by omerkok** [zmxv/react-native-sound#746]
:beetle: **Description**

I am trying to play sound in ios simulator, but I am getting an error as RNSound must not be null. I will ask you to help, there are no problems for android only ios. 

:beetle: **What have you tried?**

301 / 5000

-I did it with automatic linking at first, then I did the manual linking for ios.
-I deleted my project folder in -x code->Derivered Data and rebuilt the project.
-npm start -- --reset-cache
-watchman watch-del-all
-delete and rebuild the app
but none produced results. 

:beetle: **Please post your code:**

import Sound from 'react-native-sound';

const packageAudio = new Sound('audio1.mp3', Sound.MAIN_BUNDLE, (error) => {
  if (error) {
    console.log('failed to load the sound', error);
    return;
  }
});

    <TouchableOpacity
        onPress={() => packageAudio.play()}
        activeOpacity={0.6}
        style={[styles.exitButtonStyle, { backgroundColor: '#2c3e50' }]}>
        <IonIcon
          name='gift-outline'
          size={width * 0.06}
          style={{
            color: '#fafafa',
            alignSelf: 'center',
            marginRight: width * 0.02,
          }}
        />
        <Text style={styles.exitTextStyle}>control</Text>
      </TouchableOpacity>

:bulb: **Possible solution**

**Is your issue with...**

- [x] iOS
- [ ] Android
- [ ] Windows

**Are you using...**

- [x] React Native CLI (e.g. `react-native run-android`)
- [ ] Expo
- [ ] Other: (please specify)

**Which versions are you using?**

- React Native Sound:0.11.0
- React Native:0.62.2
- iOS:14.5
- Android:
- Windows:

**Does the problem occur on...**

- [x] Simulator
- [ ] Device

**If your problem is happening on a device, which device?**

- Device: iphone 11

**Comment by omerkok** [comment]
![Simulator Screen Shot - iPhone 11 - 2021-09-04 at 18 05 32](https://user-images.githubusercontent.com/48768206/132191499-779860cb-d744-44be-9154-38dc251f7c56.png)

**Comment by omerkok** [comment]
packageAudio.getDuration(), packageAudio.isPlaying() functions such as work only have a problem with play .

**Comment by MrRizton** [comment]
@omerkok Did you find any solution to your problem?

**Comment by dimaischenko** [comment]
@omerkok Did you solve the issue? I started getting these errors recently, although everything was fine before.

**Comment by inferusvv** [comment]
The same of me. Added. Made `pod install` and added file, but it crashes with error described above

**Comment by inferusvv** [comment]
Ah, ok. Typescript declaration is wrong.

It says that `onEnd` function is unnecessary: `play(onEnd?: (success: boolean) => void): this`

But for iOS you actually should define it: `yourSound.play(() => {});`

**Comment by dimaischenko** [comment]
Yeah, already figured that out, too. Thank you!
