### ISSUE TITLE
Can this library find .mp3 songs already on iPhone device?

### ISSUE THREAD

**Issue by quinnliu** [zmxv/react-native-sound#78]
First off great library! 

Question:
If I already have a file like `song.mp3` on my device from itunes is there anyway I can find the path to the song and play that song using this library? My goal is to play songs already on my iPhone where I can browse through them and then play one. If not do you know of any library you can?

Thanks,
Q

**Comment by benvium** [comment]
There's no support for this in the library at present.
It looks like this is possible using native iOS code: (https://developer.apple.com/library/content/samplecode/AddMusic/Introduction/Intro.html#//apple_ref/doc/uid/DTS40008845) but it's not something I've tried myself. Unless someone cares to send a PR it's unlikely to make it into this library I'm afraid.

**Comment by quinnliu** [comment]
thanks for the info!

**Comment by smithaitufe** [comment]
Please has this aspect been implemented?
