### ISSUE TITLE
[iOS] Possibility to play sound while listening to Spotify with phone locked

### ISSUE THREAD

**Issue by pedpess** [zmxv/react-native-sound#781]
:clipboard: **Description**

I have a use case where I would like to play sound with the app in the following state:

1. App is in the background
2. Spotify is playing music
3. Phone is locked
4. Sound from the app would stop Spotify, or duck the Spotify music in favor of the app sound

:microphone: **Motivation**

This would allow users to listen to more urgent sounds from the app even with other streaming audio players in the background. This is only an issue on iOS. For Android, the sound works as expected.

**Comment by ucheNkadiCode** [comment]
Check out the solution in https://github.com/zmxv/react-native-sound/issues/788, I layed out the steps of how I solved it with the OP's help

**Comment by pedpess** [comment]
Cheers @ucheNkadiCode! That's really what was needed. Thank you very much 🙏🏻
