### ISSUE TITLE
Cannot work on IOS10

### ISSUE THREAD

**Issue by gailufeng** [zmxv/react-native-sound#79]
react-native 0.34  ipad4
it works well on ios9 but cannot work on ios10

**Comment by dovy** [comment]
Same

**Comment by MadeInMoon** [comment]
still not working?

**Comment by IOSrobert** [comment]
`Signing for "sound" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.1'`

**Comment by IOSrobert** [comment]
`Signing for "soundTests" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 10.1'
Signing for "soundTests" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 10.1'
Signing for "soundTests" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 10.1'
Signing for "soundTests" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 10.1'`

**Comment by IOSrobert** [comment]
it work

**Comment by MadeInMoon** [comment]
works also in iOS 10.1 (RN38)

**Comment by benvium** [comment]
Has been working for us is iOS10 for some time, and several production apps are working. 
Closing. We can re-open if anyone finds a reproducible issue.
