### ISSUE TITLE
 Be warned, this software is alpha quality and may have bugs. Test on your own and use at your own risk!

### ISSUE THREAD

**Issue by rushilp2311** [zmxv/react-native-sound#804]
:beetle: **Description**

> Be warned, this software is alpha quality and may have bugs. Test on your own and use at your own risk!

Hey everyone, I wanted to know if this statement from ReadMe still holds true.

**Comment by rushilp2311** [comment]
@zmxv

**Comment by zmxv** [comment]
I can't speak to the quality of this repo any more as I haven't used it or React Native for a long time.

**Comment by rushilp2311** [comment]
@varungupta85 I saw you did some commit, what's your thought on this?
