### ISSUE TITLE
Can not build in Windows

### ISSUE THREAD

**Issue by lolohoang123** [zmxv/react-native-sound#828]
:beetle: **Description**

Using:
"react-native": "0.71.7",
 "react-native-windows": "0.71.13",

:beetle: **What is the observed behavior?**

Run [npx react-native run-windows] got the error

The type or namespace name 'ReactNative' could not be found (are you missing a using directive or an assembly reference?)	RNSoundModule	D:\2.Source\SoundProject\node_modules\react-native-sound\windows\RNSoundModule\RNSoundModule\RNSound.cs

Tried to run [npx react-native autolink-windows --sln...]
but still got the erroe

:beetle: **What is the expected behavior?**

:beetle: **Please post your code:**

```js
// Please post your code
```

:bulb: **Does the problem have a test case?**

 

:bulb: **Possible solution**

:bulb: **Is there a workaround?**

:bulb: **If the bug is confirmed, would you be willing to create a pull request?**

**Is your issue with...**

- [ ] iOS
- [ ] Android
- [ x] Windows

**Are you using...**

- [x ] React Native CLI (e.g. `react-native run-android`) : npx react-native run-windows
- [ ] Expo
- [ ] Other: (please specify)

**Which versions are you using?**

- React Native Sound:
- React Native:
- iOS:
- Android:
- Windows:

**Does the problem occur on...**

- [ ] Simulator
- [ ] Device

**If your problem is happening on a device, which device?**

- Device:

**Comment by AhmedMustafa505** [comment]
I have the same issue, still can't find the solution for that.

**Comment by lolohoang123** [comment]
> I have the same issue, still can't find the solution for that.

The problem is that RNSound doesn't support the Windows version. Please, find another LIB that supports the Windows version. I change to react-native-track-player LIB.

**Comment by AhmedMustafa505** [comment]
Can you please tell me how could you make react-native-track-player to work with windows, because I got this error :
Cannot read properties of undefined (reading 'CAPABILITY_PLAY')
