### ISSUE TITLE
Using buildin sounds ?

### ISSUE THREAD

**Issue by Gys** [zmxv/react-native-sound#90]
Hi !

I just need a simple sound notification to get the users attention. From what I understand so far, I have to supply my own sound. But how about using some simple buildin beep ?

**Comment by benvium** [comment]
We could do this, but it's likely that everyone would want a slightly different default sound. Also the sound would take up space in everyone's apps, so I don't think we're going to do this.  Thanks though.

**Comment by Gys** [comment]
@benvium Sorry, I meant accessing the sounds (or maybe just one of them) that are build into each OS. Not you adding files (and weight).
