### ISSUE TITLE
[Support] RN 0.40.0

### ISSUE THREAD

**Issue by Beingbook** [zmxv/react-native-sound#92]
[RN 0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0)
iOS native headers moved

This change affects all native modules and application code on iOS that refer to react native .h files
After e1577df, Native code on iOS must refer to headers out of the react namespace. Previously the following would work:
```
#import "RCTUtils.h"
```
But now all headers have been moved:
```
#import <React/RCTUtils.h>
```

**Comment by veddermatic** [comment]
Would the only change be updating the import headers in the `.h` and `.m` files? If so, this is easy, but what about backwards compatibility?

**Comment by randycoulman** [comment]
My understanding is that this is the only change required.  As near as I can tell from looking at other projects, backwards-compatibility is difficult or impossible.  Most projects are releasing a new major version with 0.40.0 support and updating their README's to suggest that people using older versions of RN should stick with older versions of the library.

**Comment by kevinnguy** [comment]
Does anyone have a pull request already with the RN 0.40 changes? The other React Native packages I'm using are not supporting backwards-compatibility and recommend sticking to an older version of their packages if need be.

**Comment by veddermatic** [comment]
I just submitted one: https://github.com/zmxv/react-native-sound/pull/98

If you need it to work *now*, it's really simple to fix locally.

**Comment by benvium** [comment]
@veddermatic @Beingbook The master branch now has this fixed. I'll push to npm as soon as I have access to do so.

**Comment by benvium** [comment]
Closing as 0.9.0 includes this feature.
