### ISSUE TITLE
Why dont play file?

### ISSUE THREAD

**Issue by shanematte** [zmxv/react-native-sound#94]
Hi.
var whoosh = new Sound('../media/music/all.mp3', Sound.MAIN_BUNDLE, (error) => {
  if (error) {
    //always a error
  } else { // loaded successfully
  }
});
Done correctly, but the error when downloading the file (probably). Why not play the file

**Comment by benvium** [comment]
Have you added the sound to your Xcode project? It looks like you're trying to load it from the RN source code tree which isn't fully supported.

**Comment by themakerman** [comment]
@benvium Can we use this lib to play files on local sdcard of android device? much like to make a music player?

**Comment by NooruddinLakhani** [comment]
@benvium I'm getting the same issue on IOS only, I've added mp3 file on XCode project folder.
