### ISSUE TITLE
Playing Multiple Sound files

### ISSUE THREAD

**Issue by Slooowpoke** [zmxv/react-native-sound#99]
Its pretty simple, I'm looking to reset the current sound that's playing or not playing and start playing a new one. However all my attempts to reset the variable seem to fall flat and I end up with the error:

"The callback play() exists in module RNSound, but only one callback may be registered to a function in a native module."

How would I go about resetting the file?  What am I missing here?

**Comment by helloncanella** [comment]
same

**Comment by Slooowpoke** [comment]
I sorted it in the end, it kinda went away? I can check tomorrow when I'm near my computer.

**Comment by benvium** [comment]
@Slooowpoke can you post some code?

**Comment by Slooowpoke** [comment]
Woops, forgot about this. Honestly not sure why it went away. I don't think I changed that much.
Using this (state.file is my sound file) code and then loading the new one seemed to work.
```
if(this.state.file != null){
      this.state.file.pause();
      this.state.file.release();
      this.state.file = null;
}
```

Some of it might be redundant but it seems to work. I chucked all of that in a reset method that I call when the component unmounts as well. After its called I just load the sound file in as usual.

**Comment by jwilbert** [comment]
@Slooowpoke I'm facing the same problem right now.  I'll have 100+ sound files, though. Did you pre load all of your sound files or how did you do it?
What would be the best way to create a playlist with various files?

**Comment by wandonye** [comment]
Mine is even more complicated since I have a dynamical list of sound files

**Comment by Slooowpoke** [comment]
@jwilbert Sorry I didn't see this sooner. Don't preload them all, it's too much. Instead load only the one that should be playing. It should reset with that code above, but I am now using an older version of React-Native (0.41). Hope this is a little bit more helpful.

@wandonye I think it should work the same? My lists is also dynamic

**Comment by paulmelnikow** [comment]
Hi! If you're still experiencing this, could you please open a new issue and include your code?
